### ISSUE TITLE
Import: [MS Datasets] Some fields of MR_Protocol are not presented or not correct in shanoir-ng

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#100]
Logs are added in Shanoir Old and NG to comparer fields stored in MR_Protocol during import.
Here is an example of the same import done in old and ng:
NumberOfAverages is 0 in shanoir-ng but should be 1 in Shanoir old log + UI.
filters is null in shanoir-ng but should be p4 M/ND in shanoir old log + UI.
All the units of mesure is missing in shanoir ng: how to display in front?

**Comment by yyao1231** [comment]
dcm4che version updated to the latest one but bug still there. 
2 dicom tags concerned: NumberOfAverages and filters(private siemens tag)

**Comment by michaelkain** [comment]
there remain some points with EnhancedMR, but this issue is solved
