### ISSUE TITLE
WebGUI: study tree: not updated after modification

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1010]
Hi Julien,
I hope you are doing good.
I have the following behaviour:

1. Open any study and expand the study tree until you see an examination
2. Click on view details and open exam
3. Edit the exam and e.g. change the date of the exam
4. Click on back, what brings you back to the study tree
5. Exam date remains still the old, what is a little confusing for the user (I had to entirely reload the tree to verify my change)

With kind regards,
Michael

**Comment by Nunien** [comment]
For me it's no longer relevant
