### ISSUE TITLE
No validation of User Expiration Date 

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#105]
In user.component.ts, isDateValid is always true.
The form's validation no longer checks the date format of datepicker.
see captures below:
![image](https://user-images.githubusercontent.com/12045953/51847388-e71c6e00-231b-11e9-9c34-72c250b27d6f.png)
and what we had on prod:
![image](https://user-images.githubusercontent.com/12045953/51847731-98bb9f00-231c-11e9-880f-f0bb4b52ce2f.png)
So I suppose that it's a regression.

**Comment by michaelkain** [comment]
expiration date works
