### ISSUE TITLE
shanoir-ofsep-qualif: nifti conversion does not seem to work

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1058]
Hi Jean-Come,
I have tested some imports using ShUp this morning.
For none of my latest datasets created I could download nifti files, what is strange.
I changed the converter to dcm2niix in my last import on the studycard, but it did not work either.
Could you please have a look?
Thank you and with kind regards,
Michael

**Comment by michaelkain** [comment]
done, hope it works

**Comment by jcomedouteau** [comment]
Résolution par Anthony, le dossier /var/datasets-data de la qualif ofsep était mal initialisé (chown absent):
Un bug dans l'initialisation des volumes overlayfs du script de déploiement de la qualif (il manquait un chown dans celui de l'ofsep).
C'est corrigé maintenant.

La prod n'est pas concernée (pas d'overlay, on monte directement les volumes du nas).
drwxr-x--- 1 500 500 256K oct.  20 13:26 /data/ofsep/prod/datasets-data/
drwxr-xr-x 1 500 500    0 avril 19  2021 /data/ofsep/prod/studies-data/
drwxr-xr-x 1 500 500 256K oct.  20 13:21 /data/prod/datasets-data/
drwxr-xr-x 1 500 500  460 oct.  13 14:41 /data/prod/studies-data/

Closing this.
Jean-Côme
