### ISSUE TITLE
Security: send token to ImageViewerServlet for papaya preview 

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#107]
without the token, there will be security issue for images.

**Comment by michaelkain** [comment]
Check if secured by Keycloak?

**Comment by michaelkain** [comment]
if it works only in the client, we can delete the method in ms import

**Comment by michaelkain** [comment]
https://github.com/fli-iam/shanoir-ng/blob/develop/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImageViewerServlet.java

**Comment by michaelkain** [comment]
/viewer/ImageViewerServlet/*

**Comment by michaelkain** [comment]
see doc of Papaya, if his url loading can be manipulated
