### ISSUE TITLE
Add concerned study and contact person in manage user menu

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1084]
The challenge and FLI-GME in waiting studies hosted at Neurinfo bring a lot of account requests that are not administrated by Neurinfo. Would it be possible to add in the manage user menu columns to identify the concerned study (should be specified at account request) and contact person so that we can quickly pick up those that are on our plate ?

**Comment by Nunien** [comment]
I agree, there could be a "Studies" column in the user list.
