### ISSUE TITLE
Download DICOM - Name datasets according to series description 

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1102]
Hi, 

I tried to download several datasets via the studies menu, selecting a few datasets with the checkbox and clicking on download selected datasets. 

Would it be possible when downloading several DICOM datasets to name the files (.dcm file or folder containing dataset with several files) according to the series description in addition to the subject name + ideally exam date ? If not we need to open them in a DICOM viewer and export them in hierarchical (not flat) mode, since the different datasets are difficult to identify based on the current name (see screenshot)

This is how DICOM exports works with DICOM viewers / workstations and at the acquisition console, 

Let me know if you need more details, 

Elise
<img width="855" alt="Capture d’écran 2021-11-18 à 17 51 04" src="https://user-images.githubusercontent.com/7511011/142460044-f28acb94-eb78-436b-9ea0-ea44feb5a40e.png">

**Comment by jcomedouteau** [comment]
Hello Elise,
Would you prefer a structure with the serie description:
subjectFolder
- serieDescription1
- - subjectName_examDate_serieUID.dcm
- - [...]
- serieDescription2
- - subjectname_examDate_serieUID.dcm
- - [...]

Or the file name containing the description:
subjectFolder
- subjectName_serieDescription_examDate_serieUID.dcm
- subjectName_serieDescription2_examDate_serieUID.dcm
- [...]

Thanks,
Jean-Côme

**Comment by jcomedouteau** [comment]
I think the first option is not a good one as the logical structure would not be truly respected.
One problem we could encounter is that the seriesDescription can be quite long and there's a limit of characters in the file name. We should also probably limit the subject name.

**Comment by ebannier** [comment]
Hi, 

I would prefer subjectName_serieDescription_examDate.dcm ideally. 
What do other users think ? 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays
