### ISSUE TITLE
Bug - Modifying member access

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1103]
Hello, 
I had to add rights for a member (receive import email) and when clicking on update, I get a pop up asking if I want to create a study card (see screenshot). This is probably a bug. 

<img width="777" alt="Capture d’écran 2021-11-18 à 15 51 52" src="https://user-images.githubusercontent.com/7511011/142460472-92b61476-e2eb-46c8-bc25-65ee6e0fcb67.png">
<img width="505" alt="Capture d’écran 2021-11-18 à 15 51 43" src="https://user-images.githubusercontent.com/7511011/142460474-c13e4f36-60a9-4d3e-b0cf-a84b771d89c9.png">

Let me know if you need more details, 
Elise

**Comment by jcomedouteau** [comment]
Bonjour Elise,
Ce bug a bien été identifié et corrigé par ce développement: https://github.com/fli-iam/shanoir-ng/pull/1095
Il sera donc corrigé à la prochaine release.
Merci pour ton retour !
Jean-Côme
