### ISSUE TITLE
Challenge subscription: receive member mail feature maybe not working

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1109]
Dear Jean-Come,

could you please in my absence have a look on the „Receive Member Mail“ feature?

It seems to work very well, when I edit a study and add a new member (see below),
BUT when somebody subscribes to a challenge and creates a new account, it does
not seem to work, or I do maybe just not receive the email in CC, what could be an
explanation too. I thought, I added the necessary code, when a challenge subscription
account request is validated by me, an email should be send too, but maybe there is a bug…

Thank you and with kind regards,
Michael

**Comment by jcomedouteau** [comment]
Yes I'll have a look.
Enjoy your holidays !

**Comment by michaelkain** [comment]
THX!!!

**Comment by jcomedouteau** [comment]
Took me some time, but when we're coming from the challenge, the "user" adding the new user, is actually nobody (as we're doing it after a rabbit MQ call).
So there was a NPE, that failed silently as it was after a rabbitMQ call.
