### ISSUE TITLE
Account expiration

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#1118]
Hi, 

Is the account expiration mail still sent 15 days before expiration ? From which address ? 
I regularly receive emails from users who ask to extend their account and do not remember receiving any account expiration warning. Maybe it is considered as a spam ? Do they also get a warning when logging on Shanoir ? 
Just to avoid any shanoir access interruption for the users, 

Elise

**Comment by jcomedouteau** [comment]
Hi elise,

A first mail is sent 1 mont before the account expiration from shanoir-admin email address.
A second on is sent 1 week before.
@michaelkain, your account expire on neurinfo quite soon, did you receive such email ?

I think something is wrong when we update directly a user by modifying its expiration date -> Then the mails are not sent anymore if they've been sent once.

They don't have a warning when connecting to Shanoir, that could be a good idea. We'll discuss this.

Jean-Côme
