### ISSUE TITLE
Export BIDS: ready for 25.03.2019

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#113]
As discussed with Yao:

1. Frontend dev: Manage Subjects add a button "Download BIDS" (with a link to ms datasets containing subjectId) to the table and add a call to DatasetService, probably a POST with a small json. (2-3d)
2. Prepare the data: download dicom files of transfmri in Neurinfo, create a zip with dicomdir, do a dicom zip import and create the subject and its exam:
Demo study - 1 subject - 1 exam - 2 datasets (anat) - T1 and T2
Configure RefMrDatasetNature manually in the database (1-2d)
3. Backend dev: add REST method to MS Dataset and write code that creates a tmp folder,
creates the folders for sub-, ses-, nii.gz data, and e.g. participants.tsv (2-3d)
4. Bonus: develop sync version, than async version

Question: can we change RefMrDatasetNature with the frontend?

**Comment by jcomedouteau** [comment]
I'm closing this as this is under developement on another issue.
