### ISSUE TITLE
Edit/Create new study as expert: avoid display of all subjects for experts

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1134]
Hi Jean-Come, could you maybe work on this? I have added Julien too, as he is our rights-access master to be sure, I am proposing the right thing.
I think for the expert role, when I open Manage subjects, I can only see the subjects from the studies I am member of, what is correct. On the other hand, when I create or edit a study I can add subjects from all other studies, what is not correct. An administrator should be able to put subjects from study to study, even when not being member of the study, but NOT the expert. This issue comes from the GME FLI and I think they are right.
Thank you and with kind regards,
Michael

**Comment by jcomedouteau** [comment]
I'm on it !
For such expert, at study creation, do we propose the subjects that the expert can
- see ? (list of all subjects in studies he is part of)
- manage ? (list of all subject  in studies he manages)
- nothing ? (no subjects at all, just remove this options to be able to add a subject to a study)

Thanks
Jean-Côme

**Comment by michaelkain** [comment]
"See" please, as you have implemented it, THX!
