### ISSUE TITLE
[NG-2021-25] Limit Access By Center

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1148]
The issue was brought by the CHUGA. We need set up a better isolation grain inside a study.
In some studies, the user that imports data from the center A should not be able to see and download data from the center B.

Another user should be able to see a group of datasets based and center, but not download data, etc.

At the moment, we have 3 rights:
- See all data of the study
- Download all data of the study
- Import data into the study.

There should be a way to limit the data access.

**Proposition 1: For every study user, define a list of centers that he has access to.**

Define an interface in the study configuration, where, for every user, you can choose between:
- All centers (no need to update it in case a new center is added to the study)
- A list of centers of the study (needs to be updated)

By default, a new user has access to all centers.

This list will be set in StudyUser Object OR in StudyCenter object (get a list of users that have access to this center) -> see investigators
When testing if a user has access to such dataset / acquisition / examination, test if the center is in the StudyUser list.

**Proposition 2: In every study, define some roles / teams where we will define specific rights and accessible centers.**

Define a new interface to create a "Profile" in a study. A profile has:
- A name
- A list of rights (that can be overridden user by user after creation)
- A list of centers (or "all centers")

Then, every user has to be in a given "profile".
We can define default profiles:
- ADMIN (all centers, can see, admin, download and import)
- IMPORTER (One center, can see, and import data)
- USER (?) (multiple centers, can see and download data)

When testing if a user has access to such dataset / acquisition / examination, test if the center is in the associated team of the user.

**Proposition 3 In every study, define some roles / teams where we will define specific rights and create sub-studies.**

Define a new interface to create a "Profile" in a study. A profile has:
- A name
- A list of rights (that can be overridden user by user after creation)
- A sub-study that will be part of the main study.

There is already an concept of parent / child study

**Comment by jcomedouteau** [comment]
+ Allow in study tree to be able to display by center with a little option.
study 
- Center
- - Subject 1
- Center 2
- - Subject 3

**Comment by jcomedouteau** [comment]
The problem is that we have no access to a link subject <-> center directly. Surpinsingly, the link is made in Examination object !

**Comment by jcomedouteau** [comment]
The idea will be to be able to define a User / Center list (in StudyUser entity?), and the user will only be able to see the data associated to this center.
Examination holds center_id so we'll be able to simply filter for every user.

**Comment by jcomedouteau** [comment]
Un investigateur ou tout intervenant d’une recherche spécifique à un centre (ARC, infirmier, TEC), n’a le droit de voir que les patients issus de son centre et strictement cela.
Des intervenants avec un profil autre (comme le relecteur centralisé par exemple pour Braini ou le chef de projet ou coordinateur) lui peut a priori accéder aux données de tous les patients à conditions que celles-ci soient anonymisées.

Dans l’idéal il faudrait créer plusieurs profils définissant les droits (c’est le cas des eCRF) :
(Pour précision : je mets importer pour pousser les images sur Shanoir et exporter pour récupérer depuis Shanoir ^^)

Investigateur (principal ou associé à voir si besoin de distinguer les deux) :
- peut importer
- ne peut pas exporter
- voir les données de son centre uniquement

ARC investigateur/TEC/infirmier de recherche (fonction support à la recherche) :
- peut importer
- ne peut pas exporter
- voir les données de son centre uniquement

Relecteur centralisé :
- ne peut pas importer
- peut exporter
- peut voir données de tous les centres ou d’une sélection de centre si besoin

Chef de projet :
- ne peut pas importer
- peut exporter
- peut voir données de tous les centres

ARC moniteur :
- ne peut pas importer
- ne peut  pas exporter
- peut voir données de tous les centres ou d’une sélection de centre


Si un investigateur ou un ARC investigateur (comme ça a été le cas pour Braini ou l’IP de Madrid s’est occupé de tous les scans espagnols) : il faudrait peut être pouvoir envisager de donner les droits pour plusieurs centres mais avec détermination des centres par le chef de projet (pas un truc binaire genre tous les centres ou aucun quoi).

**Comment by jcomedouteau** [comment]
Solution 1 seems to be the best solution for the moment.
/!\ We need to discuss with other users of their needs. Will we need to filter by dataset / examination / other one day ? How can we implement our development so that it adapts ?

Important points:
- Nothing has to change for a study that don't want to implement this

Technical points:
- A list of centers is hold by StudyUser entity.
- As StudyUser is duplicated over the different micro-services, the logic stays the same.
- By default, this list will be empty. an empty list means "all centers". -> This means no SQL update and a default to "all centers".

Subject filtering seems quite complicated as the relation with data is kept in examination entity. (So we need to check the associated centers using the list of associated examinations)

Filtering needs to be done (and associated paths of codes):
**Import**
- Select study cards (only associated centers)
- Select center for the import (CT, EEG, etc..)
- Select examination (if not on the adapted center, don't propose the examination)
- Select subject for processed dataset

**Study detail**
Study tree
- List of subjects (if the subject has no examination in the given center, don't display it)
- List of centers (do we really need ? We actually can display them all)
- List of study cards (only the one for the center(s)

Bids Tree
- Display only the subjects with examinations on the given center.

Subject list in edition -> We consider the administrator of the study (that can edit the study) actually has access to the whole study.


**List of entities**
- List of subjects
- List of examinations
- List of dataset acquisitions
- List of datasets
- Solr search
- List of preclinical subjects
- List of preclinical examinations

**Comment by ebannier** [comment]
+1
