### ISSUE TITLE
[NG-2022-5] Quality Control

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1151]
Lead developers: Julien+Michael
The idea of this roadmap issue is to increase the quality of the data **during the import**, with a kind of **quality control** for imported data, maybe during the import or via an email sent after the import to inform users to take some action.
Our idea is at the moment to extend study cards with so called „**quality check**“ rules, that should match during one
import. Maybe we will have to define such rules on a study level, to apply them for all data imported into one study.
Some ideas below from multiple Shanoir experts:

We could imaging establishing some "minimal rules" to be able to import:
- Serie name should be present
- Series should have at least X slices
- ex: l'idée serait de bloquer le transfert UCAN si il n'y a pas au moins:
(une séquence avec "TOF" OU "flight" ET au moins 50 images) AND (instead of OU (see mail))
(Séquence "gadolinium" OU "contrast" OU "enhanced"  OU " Gd"  ET au moins 50 images)
After having analysed multiple patients of UCAN each exam/time point shall contain 1 serie TOF + 1 serie GADO.

They could be defined at study level or center level.

The problem : to include patient in some clinical studies, constraints on imaging data must be validated such as **slice thickness / size / resolution  / modality, etc**. This could be done "a posteriori" but  it's very costly, and it does not inform **centers contributing data on the required data quality**. Checking QC **before** inclusion would lead to less data volume, better quality and better usage of the contributed data.

**Assumptions:**
- We start with a minimal set of checks, defined on **study level**, to see if the feature is really used in real life.
- Start on exam level: all sequences of protocol are present
- MR Image Enhanced (DICOM Enhanced) offers new possibilities of automation (develop first!)
- Quality control, see shanoir_downloader_check.py, can be done after the download as well, but the assumption here is to control already during the import for all newly arriving data and maybe retrospectively, see the re-application of study cards on already existing data.

**!Attention!** Quality study cards can be cross-modality, e.g. for MR,CT etc. but different
cards might be necessary for different modality, the check for sequences for MR might not
be the same check as the check for sequences for CT!

**Questions:**
- Quality control could be applied on dicom files and/or nifti files. I assume here, to start with dicom files is a good beginning point?
- Today study cards are only used for MRI imports, should this change to check quality for CT, PET imports as well?
- Do we want to apply the QC **retrospective**, on already imported data, and on new arriving data OR is it sufficient to apply it only to **newly imported data**, as nobody will clean up already imported data?
- To check at which moment? 1) directly after upload 2) during series selection 3) after import now clicked
- Check at which level: 1) sequence name only 2) check in dicom, more complicated -> pacs import not yet the dicoms
- For which import: 1) ZIP 2) PACS 3) ShUp
- Is it blocking all imports or allows imports, and sends warnings?
- Check quality after or before or parallel to the study card mechanism?

**Comment by jcomedouteau** [comment]
The problem we encounter with study card is that it is stored in Datasets microservice.
If we want to pre-analyze the dicom content, we need to do it in "import" state.

These rules should be defined at study level, or even maybe at center level. (We can imagine updating study_center entity to add these rules).

**Comment by jcomedouteau** [comment]
Study administrator should be informed.
Contraintes fortes ou non (au choix) -> Si un patient n'a pas tenu la séquence, il manque une série -> On doit les prendre quand même.

**Comment by michaelkain** [comment]
The idea is to start with the most simple and basic checks, see script developed by Malo.

**Comment by ebannier** [comment]
+1

**Comment by jcomedouteau** [comment]
We need to find a query builder in order to let an user build a query and be able to apply it in the back.

Proposition: https://zebzhao.github.io/Angular-QueryBuilder/demo/

There is an existing pull request to be able to display the query in human readable format
https://github.com/zebzhao/Angular-QueryBuilder/pull/191

This produces an usable query as json that can be stored and applied in the backend.

**Comment by jcomedouteau** [comment]
Screenshot of quality control edition with 3 levels 
- Valid: the serie respects the rule -> Default state if nothing applies
- Warning: the serie does not respect the rules but it's not blocking for the import
- Error: the serie does not respect the rules and it blocks the import
 
![QC_screenchot_study_detail](https://user-images.githubusercontent.com/7604176/174754653-b348f6e7-0344-4aa6-93a6-9539be6ee2f1.png)

When applying quality control post import, display flags on study tree:

![image](https://user-images.githubusercontent.com/7604176/174756447-7645ba29-3cc9-4fd3-b676-923f83450d8a.png)
