### ISSUE TITLE
Deleting Events older than 6 month? Are we sure ?

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1156]
We are currently deleting all event > 1 year. 
Do we really want to do this ? What about GDPR ?

**Comment by jcomedouteau** [comment]
Concerning GDPR, we have to keep between 6 month and 1 year of  data.
We decided with Michael to keep 1 year for the moment

**Comment by ebannier** [comment]
How do you mean concerning GDPR ? 
What infos are you refering to ? 
The DUA signature should be kept longer than a year I believe. 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
Hi Elise,
I was talking about journalisation: https://www.cnil.fr/fr/la-cnil-publie-une-recommandation-relative-aux-mesures-de-journalisation
It's the fact to keep every "action" done by the user in the application (creating a subject, deleting an examination, etc..)
It allows us to debug and follow history of a study or any other object too (we can know who deleted or modified a specific object for example.)
We were currently keeping only 6 month of history, but GDPR allows us to kep 1 year, so we'll extend it.

DUA signature is kept longer, I even think there is no limit for the moment.
Do you think there should be one ?

Have a nice day,

Jean-Côme

**Comment by ebannier** [comment]
Thank you Jean-Côme. 
DUA should be kept without limit for now. 
Is there a limit to keep the data ? None for now but should there be one ? 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays
