### ISSUE TITLE
subject-study-list component: selectableList not refreshed after removing item

### ISSUE THREAD

**Issue by marjolaineBodin** [fli-iam/shanoir-ng#118]
In the study form or subject form (resp.), if we add a new subject/study linked to the study/subject, this selected subject/study is disabled in the subjects/studies list. That's fine.
Then if we remove this user/study, we can not select it anymore, as it is still disabled in the list.
cf fix to be added in subject-study-list.component.ts, removeSubjectStudy()

**Comment by yyao1231** [comment]
new bug found about the same component: the subject study rels already existing are not disabled in the selectableList

**Comment by yyao1231** [comment]
corrected on bugCorrection branch
