### ISSUE TITLE
[BIDS] Fully integrate BIDS into Shanoir

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1184]
**Integrating / exporting data as BIDS in Shanoir.**

At the moment, in Shanoir, BIDS export is highly related to Shanoir structure, depending in DICOM.
In a future, we have to plan to have some BIDS structure based on nifti only. This will change the reference.

We can imagine two situations:
- Shanoir can become some kind of "file storage". The BIDS dataset can be modified and we keep the full structure of the imported BIDS.
- We adapt the shanoir structure to be able to fit with BIDS structure (creating a "BidsDataset" based on nifti) and a better way to manage files.

**Massive import from BIDS**

Main objective: Do not alterate the BIDS validity. Eventually propose a really simple import that iterates over the folder to directly import data.

Configure:	
- A study
- A study card
- A prefix for the subjects

-> Examination are automatically created
-> Subject are automatically named with prefix + index

BidsDataset are created -> Numerous files will be associated to such dataset.
We can add a new DatasetExpressionFormat -> BidsFile
The most important thing is to be able to keep the path of the file in the folder to be able to reconstruct it therefore.

We have to adapt the way we are currently treating BIDS display too.
We will duplicate the folders, and keep the files in the same way we are currently doing it. Shall we ?

Do we really need to create a dataset ? Keep all zipped to gain space ?
In a "BIDS study", actual Shanoir structure has almost no interest

-> Creating a subject seems quite important
-> Associating an examination could be interesting (for every data ? How to discriminate ?) -> Examination could totally correspond to session 
session-upload
session-pre-processing
session-processed
etc..

DERIVATIVES
An interesting point is the derivatives folder. This one should contain results of dataset processing (But potentially with others)

Question: What to do with "source" data that is not NIFTI ?
-> In "sourcedata" folder, we can store such DATA.

**Comment by michaelkain** [comment]
Hi Jean-Come,
please find below my first feedback. It is a mixture of a started analysis of your PR and some thinkings:

- General focus
	- The DICOM import from the clinical PACS remains the main focus (ShUp: pacs/folder + WebGUI: zip), multi-center
	- We get the DICOMs and import them into our PACS (from the hospital, where they do not even know the word BIDS, into research, our main focus)
		- sharing and managing file trees can be done best with SFTP
	- Shanoir helps to generate a BIDS tree using the study_cards OR the auto-series-type-detection tool developed by OFSEP
	- On using Shanoir-NG the study owners can share a BIDS tree (NIfTIs only) without any effort on how to format/construct it
	- We will ignore the /sourcedata folder for the moment an leave it empty
	- Important
		- We should introduce a new RIGHT -> DOWNLOAD BIDS/NIfTI
		- This could be genius
			- We have one study in Shanoir
				- One type of member == ARC in the hospital can_import only DICOM into study
				- One type of member == external researcher, image processing, can_download only the NIfTI files as BIDS
					- for the challenges we shared for security reasons only the NIfTI files
- The BIDS tree is generated as following
		- light-weight items (README, dataset_description.json, participants.tsv): to discuss: either each modification
		  on the original shanoir entity leads to an update in the file system of the BIDS tree
		- OR we export it on the fly each download, to be up-to-date with the latest changes
		- heavy-weight items (NIfTI files)
			- linked from the NIfTI storage folder of shanoir-ng???
- Good point: /var/datasets-data is removed from studies and the docker named volume is only used by MS datasets! Well done!
- We will take care later of /DERIVATES == processed datasets in Shanoir
	- it will already be a milestone, if we can generate a clean BIDS tree for raw data (== only converted NIfTIs)
- A BIDSDataset == a study in Shanoir
	- We could extend Edit study, maybe with a separate tab (not to pack even more into edit study)
	- to manage the following fields
		- License 
		- Authors
		- Acknowledgements 
		- HowToAcknowledge 
		- Funding
		- EthicsApprovals 
		- ReferencesAndLinks
		- DatasetDOI
- We have to define precisely together which version of BIDS we are currently supporting and implementing
	- I propose v1.6.0, as it is the latest version today
	- we will stick to that version, until we have finished the current devs
- docker-compose/database/db-changes/datasets/0009_#605_BIDS_dataset.sql
	- seems to be related only to tags, not sure, why it appears in the PR for BIDS
- BidsApi
	- generateBIDSByStudyId
		- called with studyId and studyName, but normally MS datasets knows already the study_name?
- BIDSServiceImpl
	- exportAsBids
		- dataset_description.json MUST contain
			- "Name": "USPIO" (== study.name in shanoir-ng)
			- "BIDSVersion": "1.6.0" (normally)
			- "DatasetType": "raw" (for the moment)
		- README
			- we could extend the study object in Shanoir with a free text field studyDescription, what is usually in the papers
		- LICENSE
			- == DUA file if existing!

**Comment by jcomedouteau** [comment]
TODO list to be transformed in issues:
1) Import from nifti only
-> As BIDS can contain only nifti, we need to be able to import from nifti only.
-> Import from Shanoir Uploader is necessary as BIDs folder are generally big.

2) Advertisement
-> BIDS video
-> Publish it on shanoir website
-> Better access to shanoir uploader

**Comment by michaelkain** [comment]
Hi Jean-Come,
I finished my local tests and unfortunately the result is missing quite some items, sorry.
Please see below:
- Testing on local machine
	- Test SC created, no rules
	- Import DICOM sample.zip
	- New subject + new exam created: MK-2022-01-21-1
	- Import successful
	- MAJOR ERROR:
		- **I can not open/use the NIfTI file, downloaded!**
		- single file download used, by click on nifti file
	- **BIDS tree verification**
		- OK 1 serie found in "undefined"
		- **ERROR, to correct:** file names finish json/gz, "." is missing
			- already written by email
		- **Minor error**: click on README: nothing happens
		- Test of download dataset_description
			- OK, download .zip and json opened
			- **Minor error**: missing: "DatasetType": "raw"
		- participants.tsv
			- OK, download .zip and .tsv opened, in Numbers
			- **ERRORS, to correct**:
				- participant_id does NOT start with sub-1
				- see spec of BIDS
					- The purpose of this RECOMMENDED file is to describe properties of participants such as age, sex, handedness. If this file exists, it MUST contain the column participant_id, which MUST consist of sub-<label> values identifying one row for each participant, followed by a list of optional columns describing participants. Each participant MUST be described by one and only one row.
				- MISSING: age + sex + both hemi-dominances, if existing
		- stud-1_DemoStudy_scans.tsv
			- Error: file names finish json/gz, "." is missing
		- sub-2_MK-2022-01-21-1_scans.tsv
			- ERROR, to correct
				- file is empty, BUT should contain one serie?
		- NIfTI and JSON files download
			- Error to correct:
				- gz.zip is wrong as the downloaded file name
- Possible extension proposal
	- Link to subject view, when clicking on the folder of the subject "sub-2-MK-2022-01-21-1"

**Comment by michaelkain** [comment]
done
