### ISSUE TITLE
Pseudonymization profile: study-specific

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1200]
Today, when importing DICOMs with the WebGUI of shanoir-ng, by default, the pseudonymization profile "Neurinfo" is used.
ShanoirUploader uses the profile, depending on the profile selected during beginning, e.g. Profile OFSEP, for OFSEP.
The pseudonymization happens in **MS IMPORT**, when using WebGUI (in ShanoirUploader when using ShUp).
**WebGUI import:**
The "Profile Neurinfo" is hard coded in startImportJob in
https://github.com/fli-iam/shanoir-ng/blob/develop/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
and used in
https://github.com/fli-iam/shanoir-ng/blob/668588ffc2062c3fa3ec3b5c6d7ff4afde6fa4f0/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java#L111
What is necessary for this feature:
- add a database table for pseudonymization profiles (ID, Name) into **MS STUDIES**
- new profiles, can only be added via database scripts, not via the web GUI, to protect them
- display in Edit/View study the list of profiles available, that for EACH STUDY one profile can be configured
- add into the General tab a line: Pseudonymization profile: select-box of profiles available in the database
- add a new column with the profile name to the Excel in
- https://github.com/fli-iam/shanoir-ng/blob/668588ffc2062c3fa3ec3b5c6d7ff4afde6fa4f0/shanoir-ng-anonymization/src/main/resources/anonymization.xlsx
- commit the Excel
- add a join colum to study and make by default all studies to profile "Neurinfo"
- use RabbitMQ to replicate the info into **MS IMPORT**, that MS Import knows the profile for the study
- change the import, that it looks up the studyId and finds the profile to use in the Excel during import

**Comment by michaelkain** [comment]
Hi Feten, one more idea: please pay attention, that not really all dicom fields can be deleted, when configured in the Excel. Yes, the pseudonymization module will delete them, but the end of the import in **MS Datasets** STILL require some fields. E.g. studyDate is such an example, when you delete it from the dicoms in the pseudonymization, the import will not finish, as it requires some fields mandatory to construct the tree, see MrDatasetStrategies in MS Datasets.

**Comment by IlhemSouissi** [comment]
Hi Michael,

Thank you for your answer. It is quite clear about the anonymization profiles.
However, I need some information regarding the pseudonymization, particularly the Patient_ID. 
According to discussions with our compliance team, I understood that the neurinfo profile uses one hash function to generate the PHK that is supposed to be stored into the correspondence table in which we found also the PID. I analyzed the database to find out this table. I think that it is the table ‘pseudonymus_hash_values’. 
My questions are:

-	Why the table is empty although we have already imported DICOM datasets?
-	Is there any difference, in terms of pseudonymization (PID), between the import using Shanoir uploader and the import from DICOM?
-	How can we switch to OFSEP profile to reinforce the pseudonymization by applying two hash functions?

**Comment by michaelkain** [comment]
Link to GitHub issue: https://github.com/fli-iam/shanoir-ng/issues/703

**Comment by michaelkain** [comment]
The important line in MS Import is: https://github.com/fli-iam/shanoir-ng/blob/059b3664c4281cafaedc352e0624ff7d02bb1755/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java#L150

**Comment by michaelkain** [comment]
this hard link, should be read from the configuration in the MS Import database: https://github.com/fli-iam/shanoir-ng/blob/059b3664c4281cafaedc352e0624ff7d02bb1755/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java#L276

**Comment by jcomedouteau** [comment]
@pierrehenri-dauvergne 
Step 1: Get profile when loading studies
In clinical-context.abstract.component.ts we load studies and centers in methods 
fetchStudies -> completeStudyCenters -> this.studyService.getStudyNamesAndCenters()
You have to update this call to load the profile along with center list.
In order to do this:
StudyApiController:findStudiesNamesAndCenters is the called method.
You have to update IdNameCenterStudyDTO.java class to add Profile attribute
Then update StudyDecorator.java class to complete the profile attribute in studyToExtendedIdNameDTO method.

Step 2: Set profile in importJob

On the front side, update dicom-data.model.ts to add profile attribute
In basic-clinical-context.component.ts class, in buildImportJob() method, you have to set importJob.profile = context.study.profile;
On the back, update ImportJob.java to add profile attribute

Then, you can remove the line michael was talking about:
[shanoir-ng/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java](https://github.com/fli-iam/shanoir-ng/blob/059b3664c4281cafaedc352e0624ff7d02bb1755/shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java#L276)
Line 276 in [059b366](https://github.com/fli-iam/shanoir-ng/commit/059b3664c4281cafaedc352e0624ff7d02bb1755)
 importJob.setAnonymisationProfileToUse("Profile Neurinfo");

**Comment by michaelkain** [comment]
- rename to Pseudonymization profile, not Anonymization profile
- create study: selecte profiles available in database
- edit profile: not possible after study creation, to avoid confusion
- ms studies: delete study_profile, add instead attribute to study table
- ms import: profile send inside import-job.json, via front-end
- for the future: migration of Excel table into database possible
- add profile to study level, for the future, different studies on the
same server might have different profiles

**Comment by michaelkain** [comment]
- prepare db-changes sql script to set automatically all servers to profile Neurinfo
- send a separate script to Anthony to change for shanoir ofsep server to profile OFSEP

**Comment by michaelkain** [comment]
furthermore I propose to delete the following lines from ImporterApiController:
			if (!importJob.isFromShanoirUploader()) {
				importJob.setAnonymisationProfileToUse("Profile Neurinfo");
			}

It is confusing, that this code is in the ApiController, but the actual pseudonymization is done in ImporterManagerService.
We should then replace the following line:

if (importJob.getAnonymisationProfileToUse() != null && !importJob.getAnonymisationProfileToUse().isEmpty()) {

with

if (!importJob.isFromShanoirUploader()) {

From now on the front-end sets for all DICOM imports (MR/CT/PT/NM) the profile to use, depending on the study.
We just need to be sure in case of ShanoirUploader (pseudonymization already done by him), we do not again pseudonymize (important).

**Comment by michaelkain** [comment]
just to keep note: we need to take into consideration the new multi-exam zip import as well
