### ISSUE TITLE
Importing new data for an existing subject: bug with scroll list

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#1201]
Hi, 
Sorry, but I will explain this in French ;)
Lors de l'import d'un nouvel examen pour un patient déjà existant dans UCAN, lorsque je clique sur la liste des " subjects" je vois les patients UCAN déjà créés, pas de soucis. Mais lorsque je sélectionne celui que je veux, là rien ne se passe et la liste se ferme. Si je l'ouvre de nouveau, je vois la liste de tous les patients ICAN et non UCAN ! Je ne trouve donc plus le patient voulu...
Cela ne marche pas non plus si je saisi le numéro de patient.

Désolée si je ne suis pas claire, ce n'est pas évident à expliquer !

Best regards

Solène

**Comment by jcomedouteau** [comment]
Bonjour Solène,

J'ai essayé de reproduire le comportement que tu décris, mais je n'ai pas réussi !
Il est bien possible de sélectionner un sujet pré-éxistant lors de l'import chez moi.
Sur quel navigateur utilises-tu shanoir ?
Utilises tu les flèches pour naviguer entre les sujets ? Si oui, peut-être changes tu d'étude sélectionnée ?
Si ce n'est pas le cas et que le bug se reproduit, je suis disponible pour faire une visio rapide pour que tu me montre.

Bonne journée,

Jean-Côme Douteau
