### ISSUE TITLE
[Dataset] Cannot download dataset with name with '/'

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1234]
dataset 115896 cannot be downloaded
-> If download name contains '/' -> replace it with a  '_'
-> Disallow '/' char from dataset name ?

**Comment by jcomedouteau** [comment]
Does not work if comment contains "/" too ?

**Comment by Nunien** [comment]
Il comment is used to build the file url, then it doesn't work either

**Comment by jcomedouteau** [comment]
Yep, that was the problem on the dataset yesterday.
I'm correcting it.
