### ISSUE TITLE
shanoir-ng-dev: Keycloak admin change pw or test access from outside

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#124]

**Comment by michaelkain** [comment]
Close open ports from outside

**Comment by Nunien** [comment]
Delete in *.sql + history
* Studies
* Center
* Acquisition Equipment

**Comment by Nunien** [comment]
Password has been changed

**Comment by Nunien** [comment]
TODO : filter keycloak web ui access by ip (probably in docker-compose/nginx/nginx.conf)
