### ISSUE TITLE
ohif viewer unusable with dicom study > 9

### ISSUE THREAD

**Issue by a-ba** [fli-iam/shanoir-ng#1261]
When requesting a dicom study with an id greater that 9, eg: https://shanoir-test.irisa.fr/viewer/10
the viewer fails with: *Failed to retrieve study data*

We have an error 500 in the nginx log:
```
"GET /dicomweb/studies/%C3%97/series HTTP/1.1" 500
```
The viewer requests `/dicomweb/studies/%C3%97/series` instead of `/dicomweb/studies/10/series`

On the other hand if we request a study with a lower id: https://shanoir-test.irisa.fr/viewer/9 then the viewer works well, and the log contains:
```
"GET /dicomweb/studies/9/series HTTP/1.1"
```

I suspect this is due to the fact that the id is expected to be StudyInstanceUID (which means starting with a well-formatted org root)

**Comment by michaelkain** [comment]
tested, now working on qualif
