### ISSUE TITLE
Import email: wrong user name in email

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1268]
found on shanoir-ofsep.irisa.fr, reported by SL
the import email is sent to the right importing user email address, but in the email a wrong user name appears

**Comment by michaelkain** [comment]
Error is here, when MS Import finishes, he sends via RabbitMQ to MS Datasets, and when MS Datasets starts:
2022-04-12 01:57:03.985  INFO 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#10-1] .s.n.d.c.DatasetAcquisitionApiController 

Start dataset acquisition creation of importJob: /tmp/**164**/3170791382475603180 for user **59**

**Comment by michaelkain** [comment]
UserId is only used for mail sending in MS Datasets, so no deeper impact of that issue.

**Comment by michaelkain** [comment]
solved, but PR to clean up

**Comment by jcomedouteau** [comment]
I feel that the rabbitMQ header encoding / deconding may have a weird comportment sometime:
https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/415

For the import, the event has adapted user_id as it comes from the shanoir-event transmited in the importJob request.
We should just use it.

**Comment by michaelkain** [comment]
Hi, if I remember right, this issue has been solved. With kind regards, Michael
