### ISSUE TITLE
Import from PACS Neurinfo: how to check studycard compatibility without dicom tags info

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#128]

**Comment by michaelkain** [comment]
I checked in ShUp, as the pacs is not returning these infos by default and maybe not even if asked in the query on the series level. I tested and added the fields to the query on series level. ManufacturerModelName has been returned, but not the DeviceSerialNumber.

**Comment by michaelkain** [comment]
This check will have to be done with the values from the downloaded dicom files for all dicom imports. I will harmonise this in the spec. No need for this issue anymore.
