### ISSUE TITLE
Massive downloading with archive configuration - new design proposal

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#1286]
These are my thoughts and research about a new downloading feature. It would allow to download as many files as needed and to configure the folder structure. It would produce many zip files (as there is a size limit), all downloaded at once. Then the user would have to unzip them all at once.

* group downloads ? / 1 dataset per dl
* back zips it with - the back has more memory available
    * the zip has a batch name
    * content is the series in the specified directory(ies)
* the user unzip a entire batch

* ui spec
    * uri : /xxxx/yyyy/zzzz/abc.dcm
    * general rule ? conditional rules ?
        * conditional rules are much more complexe to implement & store
    * insert "variables" in the uri
        * < and > are disallowed in uri
        * uri exemple
            * rule : /dataForStudy<study_name>/<subject_name>/<dataset_id>.dcm
            * result : /dataForStudyEmisep/Subject006/1246879514.dcm
        * variables : (easier to use shanoir variables than dicom variables)
            * <serieDescription> (dataset.getUpdatedMetadata().getName())
            * <instanceUID> 
                * it's in the url stored in the db
                * relative to study, subject, serie, ...
            * <dataset_name>
            * <subject_name>
            * <study_name>
            * <dataset_id>
            * <subject_id>
            * <study_id>
            * <examination_id>
            * <dataset_acquisition_id>
            * <equipment_serial>
            * <equipment_brand>
            * <modality>
            * ...
    * open a page with the list of selected datasets
        * same table as "selection" (solr sopping kart)
        * deselect datasets option
        * select a ruleset
            * separate tab
            * rulsesets are stored in db as [id, name, rule]
            * linked to a user or shared over a study ?  
        * edit a ruleset
        * test it ?
            * the backend performs a simulation
            * instead of dl zips, returns the tree representation of the result
            * opens a new page
            * provides a download button
        * download
            * first, display a information msg
                * mutiple files will be downloaded
                * how to unzip them
            * dl mutiple files
                * works with all files at once
                * maybe wait for a file to dl before dl the next one ?
        * unzip all files at once
            * on ubuntu
                * the default tool create top folder named after the zip name, we don't want that
                * solution, move zips to the destination folder, then use command "unzip \*.zip"

* now
    * shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java - downloadDicomFilesForURLs
    * String name = subjectName + "_" + examDate + "_" + serieDescription + "_" + instanceUID;
    * The zip content uri is defined by 
        * ZipEntry zipEntry = new ZipEntry(pp.relativize(path).toString());
        * in DatasetApiController

**Comment by a-ba** [comment]
IMHO the right way to cope with the aforesaid "size limit" is just avoid making intermediate copies of the downladed files.

The zip file should be built on-the-fly with a ZipOutputStream and immediately streamed. This is a very common practice, see: https://simplesolution.dev/spring-boot-download-multiple-files-as-zip-file/#implement-download-file-service

This way:
  - there is no need to store a copy of the download files
  - there is no need to store a copy of the generated zip file
  - the service is more efficient because the download starts immediately (otherwise the server has to wait until the whole zip file is built before starting serving it)

**Comment by michaelkain** [comment]
Solved by Jean-Come, now we stream.
