### ISSUE TITLE
Bug : Selected dataset DICOM Download via Study Tree 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#1287]
![MassiveDownload](https://user-images.githubusercontent.com/36895591/166417335-525b9a67-b3d5-40f0-8594-25017b7a35d1.png)

Hi, 

I wanted to download a certain dataset via the study tree (sometimes easier to pick the several datasets we are looking for than with SOLR) but when I click on download selected dataset the attached windows shows up and I cannot select DICOM or Nifti. By default (pressing ok), nifti is downloaded. 
It used to work before. 
Could you please check and make it work again ? 
Thanks in advance 

Elise

**Comment by jcomedouteau** [comment]
Hello Elise,
I think we already corrected this bug, this is quite strange. We'll have a look!

Jean-Côme

**Comment by ebannier2018** [comment]
Thanks Jean-Côme. 
Yes we already reported this bug but it does not seem to be corrected :) 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays
