### ISSUE TITLE
Bug - Nifti download via subject tree - several results 

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1311]
Hi, 

I downloaded a nifti 3D T1 from the PERINE study via the subject tree and got 2 3D T1 as a result _0 and _1.nii. 
There is only one 3D T1 volume though. 
My guess is that the data was converted with several nifti converters and we get both when ask for nifti download. 
There used to be a pop up to ask for which converter we wanted to use (already converted data or extra conversion), but not anymore. 

Is this correct ? If yes, how can we figure out which converter was used ? Could it be added in the file name ? 
Other than that the users do not know which one to use and choose randomly. 

If this is not the explanation, what is the reason ? 

Elise

**Comment by jcomedouteau** [comment]
Hi Elise,

Can you give us the dataset id so that we can analyze the problem ?
Thanks !

Jean-Côme

**Comment by jcomedouteau** [comment]
Elise,

En effet c'est un bug qu'on a identifié avec Michael récemment, qui déclenche deux téléchargements en un. Le bug est corrigé, la correction sera mise en production Mercredi prochain normalement.
Depuis le détail du dataset, le bug ne se déclenche pas normalement.

Jean-Côme
