### ISSUE TITLE
Import impossible ( red folder name)

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#1341]
It is impossible to import any of my new folders ( .zip ok with dicom files ok) since last friday.
At the first step: the name of my folder turns
 red and I don't underdand why .
![Uploading Captureshanoir 130622.JPG…]()

**Comment by jcomedouteau** [comment]
Hi Solène,
We are investigating the problem, thank you for your feedback. We'll keep you updated.

Jean-Côme Douteau

**Comment by solene2020** [comment]
New import, it is the opposite! The zipped folder without dicomdir doesn't work but the same one with dicomdir does...
