### ISSUE TITLE
Account management issue

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1343]
- shanoir.irisa.fr: accept account request, seems to work, but throws error "the user with id is not "on demand" ", see my mail
- shanoir-ofsep.irisa.fr: account request can be created, but email send does not contain password
- shanoir-ofsep.irisa.fr: create new user does not work
![create_user_issue](https://user-images.githubusercontent.com/4560288/173596177-6a535089-6e08-4082-b855-767d3d7baddb.png)

**Comment by michaelkain** [comment]
Dear Jean-Come,
would it be okay for you to have a look on that issue please? Let me know if otherwise.
Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
Yes, I'm on it !

**Comment by michaelkain** [comment]
FIXED by Anthony: In the import process (in the new keycloak container), the 'init' stage was skipped (in the SHANOIR_MIGRATION variable) before doing the 'import' stage. The consequence is that the admin account in the master realm was not created.
