### ISSUE TITLE
Accept extension request: error thrown in GUI

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1349]
Dear Julien, dear Jean-Come,
there are still user management errors unfortunately even after the correction of Anthony.
When I validate account requests/extensions, the below error is thrown, but it seems to work.
Maybe it has to do with the new error message handling?

Uncaught (in promise): PA: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":422,"statusText":"OK","url":"https://shanoir.irisa.fr/shanoir-ng/users/users/387/confirmaccountrequest","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://shanoir.irisa.fr/shanoir-ng/users/users/387/confirmaccountrequest: 422 OK","error":{"code":422,"message":"The user with id 387 is not 'on demand'","details":null}}

Thank you and with kind regards,
Michael

**Comment by jcomedouteau** [comment]
I'm on it !

**Comment by jcomedouteau** [comment]
@michaelkain I tried to reproduce the bug on qualif with your account, I effectively had an error, but that was not the one you described.
What I think is that you had this error the first time:
![image](https://user-images.githubusercontent.com/7604176/175492024-510b01e3-4b49-4d0f-ac38-5699eb0275b3.png)

Then you clicked a second time on "accept" -> then the second error appeared (as the user was actually already accepted at this time).

I created a pull request to correct the first one :)
