### ISSUE TITLE
Asynchronous multi-dataset/study (mass data) downloading

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#136]
* The user should be able to launch a big custom export and download the result once it is ready.
* Ideally he will be notified when an export is ready.
* The pending exports could be visualized along with other async jobs such as imports.
* A front end template has been made, see pull request https://github.com/fli-iam/shanoir-ng/pull/117

**Comment by michaelkain** [comment]
The first feature of this ticket should be the download of multiple datasets asynchronously

**Comment by michaelkain** [comment]
Closed, because of other issue.
