### ISSUE TITLE
[NG-2022-9] Towards FAIR datasets in Shanoir: step 1 "Findable"

### ISSUE THREAD

**Issue by cmaumet** [fli-iam/shanoir-ng#1363]
This issue will contribute to the long-term goal of facilitating data sharing using Shanoir following the [FAIR principles (FAIR=Findable Accessible Interoperable Reusable)](https://www.go-fair.org/fair-principles/).

The goal of this particular issue would be to focus on the F (for Find) of FAIR. To this aim, we could create a new page on Shanoir to list all datasets that are available for sharing. 

This page should include:
 - Basic information about each dataset possibly using an existing schema (such as DATS or dandi datasets), e.g. number of participants, type of acquisitions, number of sites, etc.
 - A link to access the data (that will likely require having a Shanoir account).
 
These would include for instance the datasets shared by Michel Dojat or Hydrops (PI: Arnaud Attyé), or the MICCAI challenges (if publicly available).

**Comment by michaelkain** [comment]
Starting point based on exchange with Alban, introduce "DataCatalog" of schema.org:
The idea is to declare a local Shanoir server instance as a DataCatalog, according to schema.org,
what will allow machines (web bots) to automatically identify our both production servers as data catalog.

**Comment by albangaignard** [comment]
Here is the proposed markup as a first iteration : 

```
{
 "@context": "http://schema.org"/;,
 "@id": "[https://shanoir.irisa.fr/"](https://shanoir.irisa.fr/%22);,
 "@type": "DataCatalog",
 "dct:conformsTo": "[https://bioschemas.org/profiles/DataCatalog/0.3-RELEASE-2019_07_01"](https://bioschemas.org/profiles/DataCatalog/0.3-RELEASE-2019_07_01%22);,
 "description": "TODO",
 "keywords": [
 "Medical Imaging",
 "Neuroimaging",
 "Neuroinfirmatics"
 ],
 "license": "[https://www.gnu.org/licenses/gpl-3.0.en.html"](https://www.gnu.org/licenses/gpl-3.0.en.html%22);,
 "name": "Shanoir",
 "provider": [
 {
 "@context": "http://schema.org"/;,
 "@type": "Organization",
 "dct:conformsTo": "[https://bioschemas.org/profiles/Organization/0.2-DRAFT-2019_07_19"](https://bioschemas.org/profiles/Organization/0.2-DRAFT-2019_07_19%22);,
 "description": "France Life Imaging [...]",
 "name": "France Life Imaging"
 },
 {
 "@context": "http://schema.org"/;,
 "@type": "Organization",
 "dct:conformsTo": "[https://bioschemas.org/profiles/Organization/0.2-DRAFT-2019_07_19"](https://bioschemas.org/profiles/Organization/0.2-DRAFT-2019_07_19%22);,
 "description": "Inria [...]",
 "name": "Inria"
 }
 ],
 "url": "[https://shanoir.irisa.fr/"](https://shanoir.irisa.fr/%22);
}
``` 

As soon as the sample Schema.org markup is online, we should advertise it on the Bioschemas website : https://bioschemas.org/developer/liveDeploys#nav-profile

**Comment by michaelkain** [comment]
Hi Camille, hi Alban,
Pierre-Henri has implemented the DataCatalog aspect and we will release it with the next deployment.
I have asked now Pierre-Henri to analyze at first, if Shanoir could create DOIs and become a DOI registry somehow, just to start a technical specification on that. I think to find and access data, the DOI creation (if possible) might be a nice aspect. If you prefer extending on schema/catalog aspects in this issue as well, it would be great to know, what you see as next steps. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
Dear Pierre-Henri, could you have a look on the advertising comment of Alban please. As soon as deployed, we might register on their website right? Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
that looks very promising: https://doi.datacite.org/

**Comment by cmaumet** [comment]
@michaelkain -- thanks for this! Is there a way for me to look a demo? If I get a better understanding if what is implemented, it will be easier for me to reply to your comment :) Thanks!

**Comment by michaelkain** [comment]
Hi, after the production release of the public catalog, I will open a new issue for that, with the same topic, where we will work on the DOI topic with Pierre-Henri. With kind regards, Michael

**Comment by albangaignard** [comment]
Hi @michaelkain, I could not retrieve any schema.org markup from https://shanoir.irisa.fr/shanoir-ng/welcome. Is it already online ?

**Comment by michaelkain** [comment]
Hi @albangaignard, could you maybe try https://shanoir.irisa.fr/shanoir-ng/index.html? It is our login page, that contains the markup. In case it does not work, I will ask Pierre-Henri to move it now into the welcome page. Do not hesitate to contact Pierre-Henri for further questions (@pierrehenri-dauvergne) Thank you and with kind regards, Michael
