### ISSUE TITLE
Delete examination - Best way to proceed ? 

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1384]
Just wondering what is the cleanest way to delete an examination from the database point of view. 

Because of a error when importing a dataset (subject code was wrong), I was ask to delete an examination. 
When this is a recent import I can go to the examination menu, find the examination in the latest Ids and delete it. Subject has to be deleted separately. 
Words of caution : 
1. I have not checked if this was still true but a subject cannot be deleted when there are examinations attached and those examinations need to be deleted first. This is a safety step that I think should be kept since there is no Undo. 
2. Answer from Shanoir is not immediate and clicking twice can delete the following examination on the list (taking into account the second click after page refresh, when the examination has disappeared and the following one takes its place). Again there is no undo. 

When the import is older, there is no search in the examination menu to find it and we need to scroll through all the pages. 
I managed to delete the datasets via Solr but this does not delete the examination itself. I can delete it via the subject tree by deleting the subject directly. 

Do you have any recommendations on other ways / the best way to proceed ? 
Thanks in advance

**Comment by jcomedouteau** [comment]
Elise,

> I have not checked if this was still true but a subject cannot be deleted when there are examinations attached and those examinations need to be deleted first. This is a safety step that I think should be kept since there is no Undo.
-> This is not true anymore. When deleting a subject, all associated examinations are also deleted.

> Answer from Shanoir is not immediate and clicking twice can delete the following examination on the list (taking into account the second click after page refresh, when the examination has disappeared and the following one takes its place). Again there is no undo.
-> The little gear on the top right of the screen indicates you that the deletion is ongoing, knowing that, you should not click twice.
The examination is removed only when fully deleted from the application so:
If you click a second time on the same bin, before the removal in the table, nothing happens.
If, by error, you click on the "next" one, after the first deletion, you still have the warning box "Do you really want to delete examination with id XX", this should be a sufficient safety step.

It's true that it's not always easy to look up for examination in the application.
- On solr search, you can search by study / subject / examination comment. But then it misses a direct link from a dataset detail to its examination or at least a link dataset -> acquisition -> examination.
I'm creating an issue about this.

The other possibility is to search from the study tree, and get directly to the examination.

Jean-Côme

**Comment by michaelkain** [comment]
I am closing this issue, because of the new issue with the same subject. https://github.com/fli-iam/shanoir-ng/issues/1474
