### ISSUE TITLE
TypeError: when column reset in manage study members table

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1390]
- Open study details, go to members table
- Click on the Reset columns icon
- TypeError shown, see screen shot
![Screenshot from 2022-09-01 10-21-44](https://user-images.githubusercontent.com/4560288/187868128-14350cb0-2d4f-4972-b513-3d03710fde6b.png)

**Comment by michaelkain** [comment]
same error for column size modification

**Comment by michaelkain** [comment]
same error for solr search as well, could not extend dataset name size column to better see results

**Comment by julien-louis** [comment]
From what I see it's fixed now
