### ISSUE TITLE
Clinical context: create subject/exam, pre-selection lost

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1399]
- user type expert used
- with CT dataset
- upload file and go to clinical context
- create a new subject (works), BUT
- error: pre-selection is lost, and newly created subject has to be selected again
- same for exam creation: subject + exam have to be selected again
- to finish import user has to create and select twice the subject
- then import works on qualif

**Comment by michaelkain** [comment]
during CT import, this error de-selected the already selected center for import

**Comment by jcomedouteau** [comment]
Corrected by pull request #1400
