### ISSUE TITLE
Include dataset size in Stats export

### ISSUE THREAD

**Issue by ecaruyer** [fli-iam/shanoir-ng#1402]
Dear Shanoir developers,

As we discussed together with @michaelkain, it would be useful for us to access the size of a dataset. Short term objective for us would be to have this in the Stats export tool, but I guess this is also a useful information for users downloading a collection of datasets.

Happy to discuss possible use cases for this to better specify the feature.

Best,
Manu.

**Comment by jcomedouteau** [comment]
Dear Emmanuel,
This is an interesting feature, that we planned a long time ago, in order to be know the datasize for a given study.
This is actually quite 'easy' to setup for newly imported data, but not that much for existing data as there is no possibility in our PACS to get this information.

**Comment by michaelkain** [comment]
We will have to work on that

**Comment by michaelkain** [comment]
@ecaruyer Dear Emmanuel, we will start to work on that feature, that will be important for all installations of Shanoir in any case. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
for the moment, we will calculate new arriving data, then extend to existing data and then see, what we can propose to somebody who downloads a collection of datasets, how we could display him the upcoming size of his selected download (very nice feature)

**Comment by youennmerel** [comment]
See PR https://github.com/fli-iam/shanoir-ng/pull/1422

**Comment by michaelkain** [comment]
Hi, I am closing this issue, as we are actively working on the overall issue https://github.com/fli-iam/shanoir-ng/issues/248 to display the size of each study in Shanoir.
