### ISSUE TITLE
CarminDatasetProcessing creation error 

### ISSUE THREAD

**Issue by KhalilKes** [fli-iam/shanoir-ng#1425]
While trying to save a carmindatasetprocessing from the webapp interface, the object seems to be facing a circular  / cyclic object value 
![image](https://user-images.githubusercontent.com/44404385/193801927-f3fda52e-731b-46fa-b2ab-263b26a5676a.png)

The object in question: 
![image](https://user-images.githubusercontent.com/44404385/193801535-3be89e28-9d36-4fcd-b346-2536b9c43d98.png)

the cyclic values seem to be: 
- subjectStudyList in the study object
- subjectStudyList in the subject object
- studyCenterList

As a hotfix we chose to empty those values as so : 

![image](https://user-images.githubusercontent.com/44404385/193802470-40442713-bca0-4560-a982-b42baab5ec77.png)

**Comment by jcomedouteau** [comment]
Thanks for the issue @KhalilKes,
We will look for a smoother solution soon.

Jean-Côme
