### ISSUE TITLE
[Subject] subject view --> error when clicking on the eye = BUG

### ISSUE THREAD

**Issue by icorouge** [fli-iam/shanoir-ng#1435]
Hello,

In a study, in the subject list view ( see attached), clicking on the eye to get the details of a particular subject produces an error.

Isabelle.

**Comment by icorouge** [comment]
with an illustration
![Capture d’écran 2022-10-18 à 14 52 49](https://user-images.githubusercontent.com/8049026/196435699-20506377-20e1-444f-bfc7-da28765b2be4.png)

**Comment by michaelkain** [comment]
Dear Isabelle, Jean-Come has already solved that. Julien will test it and we will fix it for next week normally.

**Comment by michaelkain** [comment]
solved, and deployed
