### ISSUE TITLE
Use a code quality tool (e.g. SonarQube) and correct major flaws

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#144]

**Comment by jcomedouteau** [comment]
The first step should be to use https://www.sonarlint.org/ and check/correct every modified/new file.
(And use checkstyle ?)
For more quality code:
-> Define coding rules
-> Stick to them by making code review mandatory
-> More unit tests (Tools of coverage)
-> Integrate the project in a continuous integration tool (E.G. jenkins)

**Comment by jcomedouteau** [comment]
It has to be done localy by developpers, see: https://github.com/fli-iam/shanoir-ng/wiki/Code-convention-and-best-practices

Furthermore, I corected a whole bunch of sonarlint deteted flaws in preclinical huge pull request.
Closing this
