### ISSUE TITLE
DUA in Shanoir - Tracking subject consent for data re-use

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#1444]
In our latest IRB approved studies, when asking participants for their consents to take part in the study we ask two questions, according to the openbrainconsent proposal (https://github.com/con/open-brain-consent)
- do you agree to take part in this study
- do you agree for your data to be re-used in the context of research in (say neuroscience, medical imaging)

Participants check one or both checkboxes and we think it would be useful to track in Shanoir whether they agreed for data re-use or not, i.e. adding checkboxes when importing the data and creating the subject/examination.

**Comment by michaelkain** [comment]
Dear Elise, thank you for this issue. Interesting! and not complicated to realize.
One option could be to use the already existing "tags" in shanoir on the study level and create two tags:
tag 1) "agreed-on-participation" tag 2) "agreed-on-data-re-use"
Each subject can then during the import tagged today already with tag 1) only, or both tags.
See import: clinical context and "Subject data relative to this study (optional)", to select the tags for each import.
Just an idea. We can hard-code this as well on the subject, no problem. Just listing options.

**Comment by ebannier** [comment]
Thanks for getting back on this positively. Happy to discuss it further and see what others think the best implementation would be.

**Comment by michaelkain** [comment]
closed, as no further activity/feedback/vote
