### ISSUE TITLE
OHIF viewer optimizations

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1462]
- We will have to make the new image viewer OHIF accessible from the Search table, what avoids users to click down in the tree.
- The measurement tool does not allow for multiple measurements at the same time. Yes, a more sophisticated annotation tool will be necessary.
- We cannot visualize different images at the same time. Multi-timepoint comparison is an interesting extension to work on as well, unfortunately not out-of the box in the viewer itself

**Comment by michaelkain** [comment]
Dear Pierre-Henri,
thank you for your PR for the examID and the viewer into the search! I will have a look on your PR soon.
In the mean time could you please try some of the above optimizations:
1) try if you can update the viewer to a new version and what result you get (https://github.com/fli-iam/shanoir-ng/blob/develop/docker-compose/nginx/Dockerfile, line 13 and try a new version of the Docker image). Updates are always good especially with a viewer, that has a lot of developers.
2) try, if you can open a DICOM serie (== dataset_acquisition in Shanoir). I would like to open dataset acquisitions in Shanoir, what means individual DICOM series/sequences == seriesInstanceUID in the OHIF viewer world. Today we open one examination in Shanoir (== study in DICOM containing all sequences). It could be great to open only one serie, if the user only wants to examine, e.g. only the T1 modality and not all sequences/series. The last time I checked, this was not working for me, but maybe you will find a way. search for seriesInstanceUID addressing with OHIF viewer
3) check if there are more viewer plugins, we can activate by default in the app-config.js with the new viewer version, maybe more plugins could be interesting for our users
Thank you and with kind regards, Michael

**Comment by pierrehenri-dauvergne** [comment]
To be able to open only one serie, we need to implement what's at the bottom of this page : https://v3-docs.ohif.org/configuration/url/ 
We need to call the viewer like this: /viewer?StudyInstanceUIDs=1.4.9.12.34.1.8527.examinationId&SeriesInstanceUID=1.4.9.12.34.1.8527.seriesId

But ! As written here: https://v3-docs.ohif.org/deployment/docker/ the available image in docker is based on the master branch (which is v2: https://v3-docs.ohif.org/versions/ even if docker tag says it's v4.12).
This means that as long as the available image of OHIF viewer in docker is not up to date with the documentation, we can't call the viewer like expected.
We have to wait for the new OHIF viewer docker image

**Comment by michaelkain** [comment]
all done or other existing issue
