### ISSUE TITLE
Derived study [NG-2023-04]

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1466]
Hi, 
A few years back we had a functionality to create a derived study and share a subpart of a study (given subjects and/or given sequences) without having to duplicate the data. I have cases in mind where this could still be useful. Would it be possible to reinstate it ? 
Regards, 
Elise

**Comment by michaelkain** [comment]
Dear Elise, I would like to prepare that issue for the roadmap vote. Could you please give us more details on it?
- is a Derived study - a completely new and independent study (name, starting/end date, new DUA, new members etc.) or is there a link, e.g. for the DUA and more meta-data of studies) with the "mother" study?
- do you want as in shanoir-old to select on datasets, you want to share from the mother study, or on subjects or examinations, or acquisitions
- do you want to use Solr to select the dataset for the child-study OR use the tree to do that?
- for me this is only retrospective: e.g. we select at a given time point some datasets/subjects/exams and related it with the child study; when new datasets arrive on the mother study, they are not part of the child study, but have to be added later
Thank you for your answers, I will integrate the others into that discussion and with kind regards,
Michael

**Comment by michaelkain** [comment]
We are in the **specification phase** and this issue will have to be voted, @pierrehenri-dauvergne Hi Pierre-Henri, I have assigned you to that issue for the moment, as I think, it has a strong relation with open data and sharing (FAIR), so it could be great if we could work together to specify, with all members, what might be required for that issue? Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
@cmaumet Dear Camille, I am directly adding you into the loop of this discussion. With kind regards, Michael

**Comment by ebannier** [comment]
Dear Michael 
My answers below, 
Globally the implementation in Shanoir-old was satisfying, 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays 

> De: "michaelkain" ***@***.***>
> À: "fli-iam" ***@***.***>
> Cc: "elise" ***@***.***>, "Author" ***@***.***>
> Envoyé: Vendredi 24 Mars 2023 10:24:49
> Objet: Re: [fli-iam/shanoir-ng] Derived study (Issue #1466)

> Dear Elise, I would like to prepare that issue for the roadmap vote. Could you
> please give us more details on it?

>    * is a Derived study - a completely new and independent study (name,
>    starting/end date, new DUA, new members etc.) or is there a link, e.g. for the
>     DUA and more meta-data of studies) with the "mother" study?

We can think of both. Can you elaborate on the advantages/difficulties for you for both scenarios ? 

>    * do you want as in shanoir-old to select on datasets, you want to share from
>     the mother study, or on subjects or examinations, or acquisitions

I would like to select specific datasets for specific subjects. Here are two use-cases : 
- share only specific datasets in the study with collaborators that will process a certain kind of sequence only, as the data is being collected and only give them access to what they need // Data Management Plan and Risk analysis. 
- at the end of the study, share a clean version of the study, only keeping the series/subjects that have passed QC and were included for analysis / data corresponding to what is presented in a publication 

>    * do you want to use Solr to select the dataset for the child-study OR use the
>     tree to do that?

Both if possible. I have more control on what I do with the tree that with SOLR. 

>    * for me this is only retrospective: e.g. we select at a given time point some
>    datasets/subjects/exams and related it with the child study; when new datasets
>    arrive on the mother study, they are not part of the child study, but have to
>     be added later

Yes, for me too.

**Comment by michaelkain** [comment]
Dear Elise, thank you for your above answer and sorry for my late answer. I would like to finish the specification of this feature issue. So I propose the following for version 1.0:

- to keep things simple: a "Derived study" is a study like any other study and therefore independent, no special link to "mother" study stored in Shanoir. Why? The members for the derived study will be very different, I imagine, from the mother study. DUA might maybe not exist for the mother study, but might be created/managed for the derived study. Tags etc. might be wanted to be configured differently etc. So, no link between and same study as other studies today.
- only implemented adding datasets from Dataset search (Solr) in version 1.0: we add a new button to the search interface, called "Link to study". The user selects all the datasets (no limit), he wants to link into the derived study, see tab "Selection", clicks on "Link to study" and selects the derived study afterwards (block adding datasets to their own, mother study). The executing user, needs to be study_admin on mother study AND study_admin on derived study to link the datasets.
- A new database table stores the link between the derived study and its datasets
- When a new user is created and becomes member of the derived study, he has access to these datasets, depending on his rights in the derived study
- To remove datasets, that are linked, the study admin of the derived study has to delete the datasets, what deletes the link

Happy to discuss this with all of you, with kind regards, Michael

**Comment by michaelkain** [comment]
Dear Pierre-Henri (@pierrehenri-dauvergne), it would be great to estimate a task list for this issue and estimate the required time for realization please? Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
Dear Pierre-Henri (@pierrehenri-dauvergne), it would be great to analyse as well, if maybe creating a new relation "study_subject" is 1) necessary, or not 2) what else is required to implement it. With kind regards, Michael

**Comment by michaelkain** [comment]
Dear Elise (@ebannier), please let us know if the version 1.0 above is a good starting point? With kind regards, Michael

**Comment by ebannier** [comment]
Yes, this looks like a good starting point. Are there differences with the old implementation ?

**Comment by michaelkain** [comment]
Additional specification information: example:
Study M) is mother study, already existing in Shanoir
Study D) is derived study, create new study (same study as all other studies), has its own member list, with the members having their own rights in this study

The old implementation was based on the selection of a list of datasets (related_datasets), that were added to the table related_datasets (today in MS Datasets), see below:

describe related_datasets;
+------------+------------+------+-----+---------+-------+
| Field      | Type       | Null | Key | Default | Extra |
+------------+------------+------+-----+---------+-------+
| **study_id**   | bigint(20) | NO   | MUL | NULL    |       |
| **dataset_id** | bigint(20) | NO   | MUL | NULL    |       |
+------------+------------+------+-----+---------+-------+
2 rows in set (0.005 sec)

We can image to use Solr to select a list of datasets and add them as related_dataset into study D, using the Dataset search (Solr) interface (selection) for this purpose and adding a new button "link to new study".

**Comment by michaelkain** [comment]
To propose a correct display of the tree in Shanoir, we will have to extend more:
For MS Studies we might create a new table **related_subjects**, that is used to display the tree:
study_id
subject_id
When datasets are added to study D) in MS Datasets, a rabbitMQ message is sent to MS Studies to add all subjects, that are the subjects, that are behind the datasets from the selection.

**Comment by michaelkain** [comment]
we need to analyze study_subject
create two buttons: link to study and unlink from study

**Comment by michaelkain** [comment]
find a solution for solr indexation

**Comment by michaelkain** [comment]
for version 1.0 of the implementation, I propose for the backend:
MS Studies: we use subject_study for this purpose, as already existing (== related_subjects)
MS Datasets: create new tables: related_examinations, related_dataset_acquisitions, related_datasets
Use these tables in the tree view to display the tree
Use the rights on the study (derived D) to validate the rights on the related items
