### ISSUE TITLE
Traceability optimizations

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1469]
The idea of this issue:
- trace all downloads from shanoir, by user, on all file types and ways of downloads: datasets (DICOM+NIfTI), extra data, study files etc.
- correspond to HDS criteria, to be at any moment capable to know, who did what with the data
- allow a sys admin to visualize, download these numbers at any time

**Comment by jcomedouteau** [comment]
We currently have access to such information when someone downloads data (DICOM or NIFTI) from the application with DOWNLOAD_DATASET_EVENT. It traces all datasets ID I think. We don't have such information for extra-data and study files.

Jean-Côme

**Comment by michaelkain** [comment]
Closed, as current implementation sufficient for the moment.
