### ISSUE TITLE
Account request 

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1470]
Hi, 
While thinking about updating the account request process, could you also update the text fields that are collected when creating an account : 

    Contact: --> Study manager ? Shanoir manager ?
    Function: --> Expertise
    Institution: --> Employer ?
    Service: --> nécessaire ?
    Study:
    Work: différence avec Function ? Upload ? Download + Processing ?
    Challenge: --> dans Study

We sometimes get empty fields because people do not know what the expected answer is, 

Cheers, 
Elise

**Comment by ebannier** [comment]
Shanoir Study Manager alors sinon confusion avec chef de projet réglementaire ou investigateur principal (médecin). 

Et plutôt qu'employeur si tu n'aimes pas : structure d'appartenance ? 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
For the moment, I set this:
![image](https://user-images.githubusercontent.com/7604176/204235149-d0632201-a590-4f70-b977-82a69e4fde1d.png)

Would it be OK for you ?

**Comment by ebannier** [comment]
Tu as quoi dans list of available studies ? Ceux visible par défaut ? Est ce que tu peux mettre un texte libre ? 
Shanoir study manager ne peut pas être obligatoire, cela nous facilite les choses mais par exemple pour le challenge le nom de l'étude suffit. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
Oui, il y a la liste des études disponibles par défaut. Si la personne vient d'un lien d'invitation, ce champ est caché. L'objectif étant de pouvoir faire directement une demande d'accès vers une étude, on ne peut pas trop mettre un champ libre, la personne risque sinon de se tromper, s'il doit renseigner le nom exact de l'étude.
Ok pour le study manager / contact

**Comment by ebannier** [comment]
Le champ libre est en général bien rempli, les gens ne se trompe pas ou alors d'un - pour un _ et on se renseigne toujours avant de donner accès si on ne connait pas déjà la personne et son rôle dans l'étude, 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
Enfait, on a 2 cas d'usage:
- Une personne est invitée par un study manager -> Elle reçoit un mail avec un lien, durant la création de compte, le champ 'étude' est déjà pré-renseigné, elle n'a pas à le remplir.
- Une personne qui a trouvé des infos sur une étude "publique" (challenge ou normale) décide de s'inscrire à Shanoir, elle doit pouvoir retrouver le nom de l'étude qu'elle cherche lors de son inscription, elle n'a aucune info sinon.
Si de notre coté, on veut pouvoir faire un lien direct, pour que le manager d'étude Shanoir puisse accepter/refuser directement la requête sans avoir à passer par l'admin d'étude, il faut avoir une liste pré-rmplie.

Se tromper "juste d'un caractère", ca complique déjà beaucoup les choses pour faire ce lien direct ! (On doit chercher l'étude qui ressemble le plus à ce que la personne a tapé dans le champ ??)

**Comment by michaelkain** [comment]
Hi, I am closing that issue as feature delivered and in prod. Thank you and with kind regards, Michael
