### ISSUE TITLE
DUA and yousign

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1472]
Hi, 
I was just told by a user that he could not read the DUA and download it as he wanted to before signing it. 
Could you check ? 
Also, as discussed at the last user meeting, would it be possible to 
1. add a yousign function to sign the DUA 
2. track at the study responsible level who signed the DUA and when / download the signed DUAs ? 
Happy to discuss it further, 
Cheers, 
Elise

**Comment by jcomedouteau** [comment]
Hi Elise,

Can you tell us on which study the DUA wasn't accessible ? It should be visualisable on the application and downloadable..
Thanks,

Jean-Côme

**Comment by jcomedouteau** [comment]
Hello Elise,

I checked for this study, and the DUA seems to be missing on our side.
I tried to reproduce the problem, but could not obtain this state. I've seems that you've created this study recently, when did you add the DUA ? With which account (you've made multiple updates with both your account, admin and not admin) ?
Do you still have this PDF, can you re-upload it ?

Concerning yousign, it's interesting, they even have an API to implement that we could maybe use, but.. It's a company and for our usage, we would need to pay ~100€/month, I don't know if we have the budget for this!
We can discuss this later if you want

Jean-Côme

**Comment by michaelkain** [comment]
Hi Elise (@ebannier), I hope you are doing fine. I will bring up the point of the missing DUAs in the next consortium meeting. Could you add a DUA for the study you mention above? Do you want us to keep this issue as potential issue for the roadmap or do you consider, that paying a private company for our purpose might not be worse it? Thank you and with kind regards, Michael

**Comment by ebannier** [comment]
Hi, 

Paying 100€/month is not worth it but I maintain tracking who signed and when at the study responsible level (with a signed pdf) would be useful if you have a free way of providing that. 
I am ccing the DUA I had added to the study last november. This is not a final version of the document, I am still expecting a feedback from Anne Hespel ***@***.*** Rennes) to complete it but working with this excerpt in the meanwhile. I believe I used my expert user account (ebannier) to add the document, 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays
