### ISSUE TITLE
Examination search

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1474]
Hi, 
When an import was done with the wrong subject number is needs to be done again since renaming in Shanoir does not rename the DICOM files. It would be usually to allow searching examination by Ids (and subject name) in order to erase them. If there have been many imports since, we need to scroll all the pages to find the correct id and if we need to suppress several examinations, suppressing/refreshing can lead to errors = suppressing the wrong id. 
A search would allow to make sure we suppress the correct files, 
Subjects can only be deleted after the corresponding examinations are deleted,  
Cheers,
Elise

**Comment by michaelkain** [comment]
Hi Youenn (@youennmerel), if there would be a waiting time upcoming for the OFSEP pipeline, it would be great to work on that issue, from Elise. It is true, the examination list does not have any filter to delete more precisely exams, what would be an advantage. Thank you and with kind regards, Michael

**Comment by youennmerel** [comment]
Logically, the rights that will apply will be the same as those associated with the "Delete" button in the examination details view.

**Comment by ebannier** [comment]
Go for it then ! :)
