### ISSUE TITLE
Study and subject list takes way too long to load

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1492]
Investigate this problem.

**Comment by jcomedouteau** [comment]
- No pagination (easier research)
- Mapping to DTO is way to long (no searching in DB) -> Why ?

**Comment by jcomedouteau** [comment]
Reopen as we now load all subjects

**Comment by michaelkain** [comment]
Hi Jean-Come, I still have this error in the GUI on the subject list: TypeError: this.studiesICanAdmin is undefined
Thank you and with kind regards, Michael
