### ISSUE TITLE
Date format in Solr

### ISSUE THREAD

**Issue by mgaubert** [fli-iam/shanoir-ng#1513]
Hello,

Just a comment: in Solr, in the main result table, the date format is MM/DD/YYYY for "ExamDate" field, while in the selection menu on the left ("Creation Date") it is using the format  DD/MM/YYYY. It is very confusing.

Also, I don't understand how the expert mode works for Date.
I tried these sequences
_datasetEndDate:4/14/2015
datasetEndDate:04/14/2015
datasetEndDate:14/04/2015
datasetEndDate:14/4/2015
datasetEndDate:"2015-04-14T22:00:00.000Z"_

But none is working. While entering "14/04/2015" in field "to:" for "Creation Date" works fine.

Thanks for your help.

Best,
Malo

**Comment by jcomedouteau** [comment]
Hello Malo,

Thanks a lot for your issue

> Just a comment: in Solr, in the main result table, the date format is MM/DD/YYYY for "ExamDate" field, while in the selection menu on the left ("Creation Date") it is using the format DD/MM/YYYY. It is very confusing.

This point is totally true, we will correct this as soon as possible as it's quite easy to do.

Concerning the second point, I don't really know why we did put these two fields datasetEndDate and datasetStartDate, they are unexisting fields, and cannot be queried ! 
We will remove them from the description and add an example on how to do with dates !
Available date fields are datasetCreationDate and examinationDate

Concerning date, you can check on https://solr.apache.org/guide/6_6/working-with-dates.html#working-with-dates

Have a nice day !

Jean-Côme

**Comment by mgaubert** [comment]
Hello Jean Côme, 

Thank you for your answer.

While waiting for the example, could you just let me know how the Expert mode works right now for date? 
Let's say I want to retrieve a scan with "ExamDate"=3/21/2014 in main table.
I tried multiple things according to your reference but could not find the good solution.

Thanks! 

Malo

**Comment by jcomedouteau** [comment]
You're right, it's not really easy. The solution I found was to do: 
examinationDate:[2014-03-21T00:00:00Z TO 2014-03-22T00:00:00Z]

**Comment by mgaubert** [comment]
OK, thanks.
Have a good day !

**Comment by mgaubert** [comment]
While testing, I found an unusual behavior.
I have a subject scanned the 4/27/2016 according to "Exam Date" field.
And here are the results of different tests:

_examinationDate:[2016-04-26T00:00:00Z TO 2016-04-28T00:00:00Z]_ the scan is returned as it should be
_examinationDate:[2016-04-27T00:00:00Z TO 2016-04-28T00:00:00Z]_ Nothing returned (=issue)
_examinationDate:[2016-04-26T00:00:00Z TO 2016-04-27T00:00:00Z]_ the scan is returned as it should be
_examinationDate:[2016-04-26T23:00:00Z TO 2016-04-27T00:00:00Z]_ Nothing returned (=issue)

So it looks like the scan can be found the 26th of April but the 27th as it should be.

Maybe something to look at next time you modify the management of date in Solr.

**Comment by mgaubert** [comment]
I tested on the qualification and the date is working with the "from" "to". I mean, if I search for a scan of the "07/02/2023", and entered: 

_examinationDate:[2023-02-07T00:00:00Z TO 2023-02-07T23:00:00Z]_ 

and it finds my acquisition.

Of note: I don't know how the hours/minutes are managed. I seems that the scan of the "07/02/2023" is actually 2023-02-07T00:00:00Z. So when trying: 

_examinationDate:[2023-02-07T**00:00:00**Z TO 2023-02-07T**00:00:00**Z]_

it is also ok.

But not : 

_examinationDate:[2023-02-07T**00:00:10**Z TO 2023-02-07T**23:00:00**Z]_
