### ISSUE TITLE
[Processed dataset] Cannot download processed dataset

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1515]
As dicom -> This is quite normal, but we need to display a correct warning / error

As nifti, the rights check fails:

> java.lang.NullPointerException: null
        at org.shanoir.ng.dataset.security.DatasetSecurityService.hasRightOnEveryDataset(DatasetSecurityService.java:382)

This is due to the fact that the dataset acquisition is null  for processed dataset.
-> check on parent dataset

**Comment by michaelkain** [comment]
Perfect, it would be great to solve that for the V1 of the GME FLI and to complete this functionality on processed datasets
