### ISSUE TITLE
[VIP - Shanoir] Multiple datasets pipeline

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1517]
This issue is a first specification for multi-dataset processing between Shanoir and VIP.

This is a simple first development -> We want to be able to launch a single dataset pipeline with multiple datasets in parallel.
Example: RHU primus, launch the Pixyl's pipeline on all 3D flair of a study.

- Select datasets (Ok from solr, TODO from a study)
- Get the pipeline (ok, TODO: get input arguments)
- Show the list of pipelines that will be launched (or informations concerning all -> if it's too much, don't show all) (TODO)
- Launch the pipeline (TODO: Launch multiple)
- Update the job progression (-> Not o be done yet)
- Retrieve the jobs results and create processed datasets according. (TODO for multiple results)

**Previous development:**
Make a fake VIP API to return a simple pipeline, and publish a result file.
This will allow to make a full pipeline execution.

Technical specification

## I. Dataset selection

From Study

In study detail, add a button "Apply a pipeline on selected datasets" -> link this to pipelines

## II. Retrieve VIP pipeline
- Display the list of parameters in entry. Also display the list of selected datasets.
- Create a modifiable map of parameter -> value (possibly dataset if file in entry, something else otherwise) 
- Display a matching tree of parameters / datasets (or value) for every pipeline that will be executed

## III. Launch pipeline
When executing the pipeline, we need to load ALL datasets one by one.
execution.component.ts l.81
We Iterate over parameters here, we want to iterate over adapted parameters
-> We will iterate over the map of parameter -> dataset

## IV. Get pipeline results
When loading pipeline results, iterate over multiple files to load each execution.
ExecutionStatusMonitor.java l.114 + CreateDatasetProcessing
Create a new dataset processing for every processed dataset instead of keeping the "BIG" processing if necessary
Retrieve the input dataset from file meta-data and not from parent dataset processing

**Comment by jcomedouteau** [comment]
This issue is a first specification for multi-dataset processing between Shanoir and VIP.

This is a simple first development -> We want to be able to launch a pipeline with a single dataset in entry with multiple datasets in parallel.
Example: RHU primus, launch the Pixyl's pipeline on all 3D flair of a study.
- Select datasets (ok for solr, TODO from a study)
- Get the pipeline (ok, TODO: get input arguments)
- Show the list of pipelines that will be launched (or informations concerning all -> if it's too much, don't show all) (TODO)
- Launch the pipeline (TODO: Launch multiple)
- Update the job progression (-> Not o be done yet)
- Retrieve the jobs results and create processed datasets  according. (TODO for multiple results)

Technical specification

I. Dataset selection

1) From Solr

2) From Study

II. Retrieve VIP pipeline
-> Adapt the front

III. Match arguments

IV. Launch pipeline

V. Get pipeline results

**Comment by youennmerel** [comment]
Done
