### ISSUE TITLE
Center name is too long

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1519]
While editing a study, open the dropdown menu to pick a study. Some center's name are too long to fit in the width of the dropdown menu. See picture below

![image](https://user-images.githubusercontent.com/117283961/215488261-ac238a2c-8741-42d8-b8c8-df6e0ff9e84c.png)

**Comment by jcomedouteau** [comment]
On the same type of problem:
When the dataset name is too long (processed dataset) and contains no space, we cannot select it (the "+" does not appear)
![image](https://user-images.githubusercontent.com/7604176/215736994-99f067df-ac99-4129-939e-304e9bb80ba0.png)
