### ISSUE TITLE
Examination list: missing exams

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1524]
- I used an admin account
- click on examinations, see list, check latest ID
- open dataset search SOLR, check latest dataset, check examination, ID higher than in exam list
- missing exams somehow

**Comment by michaelkain** [comment]
Dear Jean-Come, if okay for you please have a look. If not no worries, I will check.

**Comment by jcomedouteau** [comment]
I'll have a look !
Jean-Côme

**Comment by jcomedouteau** [comment]
It seems that new examinations are tagged as preclinical = true -> We can't see them in normal examination list.

But, nothing seems to have changed in DB:
![image](https://user-images.githubusercontent.com/7604176/215984440-f351b92b-9bbb-4385-a062-73971a526530.png)

I'll check further what could have provoked the change.
