### ISSUE TITLE
Add uploader user id in export statement

### ISSUE THREAD

**Issue by arthursw** [fli-iam/shanoir-ng#1533]
Add the id of the person who uploaded the datasets in the export procedure (the `administration > export statistics` feature).

= Add `select u.username as identifiant from users.events e, users.users u where e.event_type = 'importDataset.event' AND e.object_id = examination_id AND u.id = e.user_id;` in `docker-compose/database/3_add_statistics_procedure.sql`

**Comment by jcomedouteau** [comment]
Hello @arthursw, en général la requête se fait sur beaucoup de sujets en parallèle ?
Pour le user_id, on remonte uniquement jusqu'en 2021 je crois, du coup on doit faire un left join (si on ne trouve pas, on met null pour avoir quand même la ligne -> Ca prend quand même pas mal de temps..
Est-ce que c'est embêtant de ne l'avoir que depuis 2021 ?

Jean-Côme

**Comment by arthursw** [comment]
Salut ! J'ai pas les réponses à tes questions ; c'est pour Romain, je lui demande plus d'info lundi prochain quand je reviens de vacances ; )

**Comment by jcomedouteau** [comment]
Won't do
