### ISSUE TITLE
bad cert for https://shanoir.org

### ISSUE THREAD

**Issue by a-ba** [fli-iam/shanoir-ng#1535]
The new welcome page `welcome.component.ts` links to https://shanoir.org which has uses an invalid certificate (not valid for shanoir.org).

Possible solutions:
- fix the cert
- replace the link with https://project.inria.fr/shanoir/ (https://shanoir.org actually responds with a 301 redirect tot this page)

**Comment by michaelkain** [comment]
Hi Anthony, should be fine now. Cheers, Michael
