### ISSUE TITLE
OFSEP: import dates missing on dataset acquisitions

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1538]
on the latest imports with ShUp for OFSEP prod
Céline told me, that the import dates are all missing on the dataset acquisitions

**Comment by jcomedouteau** [comment]
From Céline:
It is not from the latest imports but for datasets for the following studies :
Cohorte Principale - CHU Fort-de-France
Cohorte Principale - CHU Reims
Cohorte Principale - CHU Toulouse

**Comment by michaelkain** [comment]
Jean-Come has analyzed your demand. The missing import dates are "normal":
All imports done before we introduced the feature and changed the code are
having empty dates, as we do not know them. We might be able to reconstruct
them from our log files, but this would be very time demanding. You will be able
to estimate the import dates from your exports, or at least bring them into a time range.

Therefore I will close the issue, as the feature works today.
