### ISSUE TITLE
[prod] Access request: issues

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1544]
Hi Jean-Come,
thank you, I can now validate or refuse extension requests as admin, what is fine. Great!
But I am having issues on the prod with some access requests. I think I can validate new
user access requests, e.g. made on one of the challenges. What does not seem to work:
- existing user, already in one study (e.g. id 209), ask for access to study id 208, failure!
/accessrequest/resolve/2 500, when I click on "accept" as study admin (mkain account)
and after the access request is gone, what is weird too
- I had the same issue for some reason, with a newly created account too, same 500
- as sys admin I can not delete anymore users, that are duplicated
- in the email sent to the study admin, after I added a new member to my study, I do not
have my account, with my email in the confirmation mail, but shanoir-neurinfo-adm@lists.gforge.inria.fr
I will send you the screens, as I do not want to share them publicly because of user infos.
With kind regards, Michael

**Comment by jcomedouteau** [comment]
I'll check, thanks for the screenshots.

**Comment by michaelkain** [comment]
Dear Jean-Come @jcomedouteau, thank you for your fix. Have you verified, concerning the issue, that your flag was NULL (on_demand), if the behaviour changes with an anonymous user outside and an existing user, already logged in, that asks for access?

**Comment by jcomedouteau** [comment]
I normally checked for both locally, and both weren't null. That's my current problem. Could you reproduce the email problem by the way ?
