### ISSUE TITLE
Preview + OHIF viewer - error (ofsep site)

### ISSUE THREAD

**Issue by chomo-ofsep** [fli-iam/shanoir-ng#1556]
Hello,
I have an error message and cannot preview the images on the ofsep site and the OHIF viewer has the message "failed to retrieve study data".
Thank you for your help,
Céline

**Comment by michaelkain** [comment]
Dear Céline, I will close that, as it was link to an environment issue on that specific day, not to the software itself. Thank you and with kind regards, Michael
