### ISSUE TITLE
Subject creation: buggy required fields 

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1558]
When creating a new subject, by default "Living human being" is selected and first name/last name/common name/birth date all require a value.
Switch imaged object category to "human cadaver" and all required field are kept.
Click another time on the dropdown menu and pick again "human cadaver" in the list. The fields are not required anymore (' * ' is disappearing), it shouldn't behave like that.

![image](https://user-images.githubusercontent.com/117283961/222401104-276752ea-4597-42aa-90cc-c4aae49ad3e4.png)
![image](https://user-images.githubusercontent.com/117283961/222401172-06c051b6-eaaa-4955-bb73-b8cb27780611.png)
![image](https://user-images.githubusercontent.com/117283961/222401243-f5c8ef9b-4f0f-43c0-871e-7f744d7e0e14.png)

**Comment by michaelkain** [comment]
Dear Pierre-Henri, very good finding! I think it would be a great thing for you to enter into the clinical context component, that is one of the hearts of Shanoir frontend, when not THE HEART. It would be great if you could fix that. Thank you and with kind regards, Michael
