### ISSUE TITLE
Missing profile_id in study in demo data 

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1559]
In [import.sql](https://github.com/fli-iam/shanoir-ng/blob/develop/shanoir-ng-studies/src/main/resources/scripts/import.sql), 2 profiles are created (L122) but no ID is linked to the study `DemoStudy` through `profile_id`.

This causes an error when importing DICOM on this study.

Solution : 
- Move the profile creation query before the study creation query
- Correct the study creation query to include a profile_id (1 for example)

**Comment by michaelkain** [comment]
Dear Youenn, thank you, happy to see your issues here. It would be great if you could fix this directly and create a new PR, that we can get rid of the problem, once found. Thank you and with kind regards, Michael

**Comment by youennmerel** [comment]
https://github.com/fli-iam/shanoir-ng/pull/1561

**Comment by michaelkain** [comment]
THX! FIXED.
