### ISSUE TITLE
Access request: refuse throws error on prod (new demand)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1560]
Hi Jean-Come, a new user tries to access to a study. I refuse the access as study admin, I get an error on prod.
could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"

**Comment by michaelkain** [comment]
the weird thing is, the access request throws an error, but is not available anymore on my list of access requests to process. when I log in as sys admin I can still see the demand, but I can not delete/deny the creation anymore

**Comment by jcomedouteau** [comment]
Michael,
It seems to be same problem I tried to correct last time.. I'm on it ! (user can't be deleted if it has an existing access_request)
Jean-Côme

**Comment by jcomedouteau** [comment]
This is normaly solved. Closing it.
