### ISSUE TITLE
Naming of zip containing nifi file 

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1562]
Hi, 
I thought I already submitted an issue but cannot find it, maybe it was just in my mind. Here it is (again ?) 
I still use the study tree to download individual nifti files, especially for optimisation tests where we try different sequences modifying one or the other parameter and the tree help track with series by displaying the whole series name in acquisition order, which would be more complicated in SOLR. 
The nifti download results in a zip file containing a nifti file. 
The nifti file name contains the subject name but the zip files does not. 
My question is : Would it be possible to use the same file naming also for the zip file so that we can more easily keep track when downloading individual files from different subjects ? 
Thanks in advance for your feedback, 
Regards, 
Elise

**Comment by ebannier** [comment]
Hi, 

Thank you Jean-Côme. It would be great already for single dataset download, 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 75 05 (Empenn) - Fridays

**Comment by michaelkain** [comment]
Dear Jean-Come, dear Elise, thank you for your exchange. @jcomedouteau if okay for you, it would be great to realize that feature please? Thank you and with kind regards, Michael

**Comment by youennmerel** [comment]
Hi, 
As discussed with JC, I will add the subject name in the zip name. This will cover NIFTI & DICOM single dataset download.

**Comment by youennmerel** [comment]
See https://github.com/fli-iam/shanoir-ng/pull/1580

**Comment by youennmerel** [comment]
I'm closing this issue as the associated PR has been successfully merged.
