### ISSUE TITLE
[Import/BUG] If storeSCU fails, log correctly the error

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1575]
When the PACS fails to store some dicom, the "exitCode" is still 0:
![image](https://user-images.githubusercontent.com/7604176/223996646-704658e5-6d9b-46d5-8848-7bbe8676d724.png)

So errors are not correctly displayed and import is marked as finished whereas is should not.

Analyse StoreSCU (see Anthony's proposition):

> J'ai eu ces problème en faisant des transferts avec dcmqr : la commande termine systématiquement avec le code 0 dès lors qu'elle arrive a établir une association avec le serveur, mais derrière il faut parser la sortie pour détecter les erreurs du genre :
> 
>     INFO   - DCM4CHEE(1) >> 2:C-MOVE-RSP[pcid=9, remaining=null, completed=724, failed=1191, warning=0, status=b000H
> 
> En revanche je n'ai pas observé ce comportement avec storescu : il me retournait systématiquement un code différent de 0 en cas d'erreur. Cela dit je la lançait individuellement sur chaque fichiers et non sur un répertoire tout entier (ça joue peut-être).
> 
> Ce que je peux suggérer dans l'immédiat c'est de rajourter l'option « -ll warn » à la commande storescu pour limiter la sortie aux warnings et de la logger avec la fonction « LOG.warn() » plutôt que « LOG.debug() ». Comme ça, quand il y a un problème en production, ça nous permet déjà d'avoir une trace.
> 
> Un autre solution possible est de parser la sortie storescu et de logger les lignes commençant par "D:" ou "I:" avec « LOG.debug() » et de logger tout le reste avec « LOG.warn() ».

**Comment by michaelkain** [comment]
Hi Jean-Come (@jcomedouteau), it would be great to solve this issue. Hopefully by trying to get the code from the command line? Maybe you can get an exitMessage and parse it for error codes? Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
So for the moment, the installed storeSCU is 5.21.0, which does not have the logging option. So for the moment we have no way to check for an error.
We should discuss about upgrading storscu (in dockerfile) to be able to get the last version and a better logging system ?
Jean-Côme

**Comment by michaelkain** [comment]
Hi Jean-Come, thx for your comment. From my side there is now issue to upgrade. Why not just upgrading? and use the new version with better error codes? Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
Done
