### ISSUE TITLE
CORS error when listing pipelines from VIP

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1592]
Continued from https://github.com/fli-iam/shanoir-ng/pull/1574

![image](https://user-images.githubusercontent.com/59697998/225934009-3c4cd796-2a82-40ee-b37f-f19cba33e278.png)

**Comment by michaelkain** [comment]
Hi Youenn (@youennmerel), it would be great to bring this to run during this week please. Have you checked if host and origin are correct from our side? Thank you and with kind regards, Michael

**Comment by youennmerel** [comment]
There was an error in the VIP ws path. Thanks to Axel, it's now corrected.

We are now receiving a 401 Unauthorized, which is logical as we still have to connect our 2 Keycloak to share authentication.

**Comment by youennmerel** [comment]
I've configured a VIP client on our qualif, and sent the JSOn config to Axel.
Waiting for his feedback.

**Comment by michaelkain** [comment]
Now working
