### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by icorouge** [fli-iam/shanoir-ng#1593]
Hello,

I want to change my passord. When I log and do to my profile, I don't see any ways  to change password. Would it be possible to add this functionality ?

In the meantime, is "forgot password" (though i did not forget mt passwd) the only way ?

Thank you,
Isabelle.

**Comment by michaelkain** [comment]
Dear Isabelle, thank you for your issue! I have to confirm, that in the mean time only "forgot password" is the right way to change your password, as far as I know. @pierrehenri-dauvergne Hi Pierre-Henri, Keycloak proposes already a feature to reset a password, maybe we can even use the same GUI, that is behind "forgot password". It would be great to add that feature, as the dev effort might be quite low, now. Thank you and with kind regards, Michael
