### ISSUE TITLE
Test DICOM web import for heart MR/CT images

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1605]
Hi Youenn (@youennmerel), I hope you are doing fine. I will share some images with you. It would be great, as I had an error with them on qualif, if you could check what is wrong and try to fix it please. All in the idea to prepare Shanoir for other organ acquisitions, we might not be familiar with. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
Hi Youenn, have you tried both DICOM "study", the first for MR (IRM Coeur) and the second for CT (TDM Cardiaque)? Normally, we can only import one at a time and maybe CT is the problem. With kind regards, Michael

**Comment by youennmerel** [comment]
@michaelkain :
As seen together, I don't reproduce this problem on my dev.

I've tested the case on qualif, and it's OK too.

So, if that's all for you, I propose to close this issue.
