### ISSUE TITLE
solr - multiple download shows "NaN" in progress bar

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1621]
On solr page, select multiple datasets and click "download as dicom". Before the file is ready  to download, a progress bar appears on screen, it displays "NaN%" for a while:

![image](https://user-images.githubusercontent.com/117283961/229120911-0856c18e-e8ca-41d5-9ec4-5af2714a9a6f.png)

**Comment by jcomedouteau** [comment]
For this one, I think that we need to know the content size we are sending, which is possible... with youenn's PR !
So we will wait a bit
