### ISSUE TITLE
Form error on Bruker import

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1624]
When trying to import bruker :
- creating a new acquisition equipment won't work (will be created  [?] but not displayed in the list)
- creating a new subject will work, but : 
  - the field will be disabled
  -  the "acquisition equipment" field will be voided
  - the following error will occur : 
```
Error: Uncaught (in promise): rC: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"OK","url":"https://shanoir-qualif.irisa.fr/shanoir-ng/datasets/examinations/subject/undefined/study/204","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://shanoir-qualif.irisa.fr/shanoir-ng/datasets/examinations/subject/undefined/study/204: 500 OK","error":{"code":500,"message":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"undefined\"","details":null}}
```
- if creating a new examination, "create" will be directly enabled, but the follwoing error will occur on creation :
```
Error: Uncaught (in promise): rC: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"OK","url":"https://shanoir-qualif.irisa.fr/shanoir-ng/datasets/examinations","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://shanoir-qualif.irisa.fr/shanoir-ng/datasets/examinations: 500 OK","error":{"code":500,"message":"The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!","details":null}}
```

**Comment by michaelkain** [comment]
Hi Jean-Come (@jcomedouteau), I hope you are doing fine. It would be great to solve that issue please? This issue is not urgent, but if we want to open a study for the group SAIN (meeting last week), it might be important to bring back that feature. It would be great to combine that fix with the integration of the new converter of your colleague, that does Bruker2DICOM as well, if I am not wrong? Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
Hi Youenn,
I tried to reproduce the problem as an exert on qualif and could not reproduce.
Do you remember the study you used ? 

I wonder if this is not linked to the issue with  the center with no equipment.. #1625
