### ISSUE TITLE
Can't create acquisition equipment from DICOM import when none exist

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1625]
When importing DICOM in a study without existing acquisition equipment, the field "Select an acquisition equipment" will not be displayed.

It should be possible to create an equipment from here.

![image](https://user-images.githubusercontent.com/59697998/229131478-ea3fc010-b8b1-4af3-85a4-39f7f32f39af.png)

**Comment by michaelkain** [comment]
Hi Pierre-Henri (@pierrehenri-dauvergne), it would be great please, if you could have a look on that issue? My understanding is: this happens only with CT imports, when no equipment is assigned to a newly created center? With MRI DICOM imports the user is asked for the creation of a new study card, that forces to select a center + an acquisition equipment. The above case is very rare in reality, as people normally create an equipment (CT) for the center(s) they add to the study. So, there is normally always an equipment. I think it might be interesting, same as for missing study card, to ask the user for the creation of an equipment to his center selected above. Thank you and with kind regards, Michael
