### ISSUE TITLE
carmin-client: qualif: widget with pipeline details not visible without scrolling

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1655]
Hi Youenn (@youennmerel), I hope you are doing fine. With all the pipelines, that are available to me now on qualif, when I click on one pipeline, the widget is not visible in Firefox and I have the impression, that it does not work, but it is on the outer right side of my screen. It would be great to fix this behaviour please? Thank you and with kind regards, Michael

**Comment by youennmerel** [comment]
Hi @michaelkain,

As we discussed with @jcomedouteau, the "Pipeline description" box displayed on the right is not a very good design.

I think we should modify the "Processing" view so that the description is displayed under the pipelines icons.

**Comment by michaelkain** [comment]
Perfect, thank you!

**Comment by youennmerel** [comment]
Merged on develop
