### ISSUE TITLE
Have link in fields in dataset Solr view

### ISSUE THREAD

**Issue by youennmereljourdan** [fli-iam/shanoir-ng#1656]
In the Solr Search view, the following table field :
- Study
- Subject
- Center
- Exam

could be links to the details view of these objects.
![image](https://user-images.githubusercontent.com/59697998/232067048-f62c4c35-3763-485e-bdfe-79426b48ca19.png)

For a working example, see what's done in the "Manage examinations" view for fields "Research study" and "Center".

![image](https://user-images.githubusercontent.com/59697998/232066742-d7cfa399-f1bb-40d2-a3f9-a77ad8a6579c.png)

**Comment by michaelkain** [comment]
Hi Pierre-Henri (@pierrehenri-dauvergne), I hope you are doing fine. I think, this would be a great extension for the Dataset search (Solr) page, that user can get rapid access to the entities. @youennmerel thx for the good proposal! With kind regards, Michael

**Comment by pierrehenri-dauvergne** [comment]
This has been developped in issue #1642
