### ISSUE TITLE
Don't display "Run a process" button for user with insufficient rights 

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1663]
If authenticated user has no expert or higher rights, the "Run a process" button in the Solr search view should not be displayed.

![image](https://user-images.githubusercontent.com/59697998/232723615-37ae4ae9-a313-4ccd-8a5a-7f0201bef555.png)

**Comment by michaelkain** [comment]
Dear @youennmerel, thank you for this very good finding. It would be great, if you could work on that as part of the entire "processing" integration please? Could you please add your definitions for running pipelines under https://github.com/fli-iam/shanoir-ng/wiki/Roles-and-rights-specification and sync them with Julien (our rights master) please? Thank you and with kind regards, Michael

**Comment by youennmerel** [comment]
As discussed with Michael, rights for creating pipeline processing should be :
ADMIN or ((USER or EXPERT) and CAN_ADMIN)

CAN_IMPORT would be sufficient for pipeline that only create new processed dataset, but for OFSEP pipeline we would like to directly edit an existing dataset, and that should require CAN_ADMIN rights

**Comment by youennmerel** [comment]
Has discussed with Julien, the rights should rather be `ADMIN or (EXPERT and CAN_ADMIN)`
