### ISSUE TITLE
Import of ACTIDEP pulsatilite cmrr dataset

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#167]
Import failure with pulsatilite cmrr AP dataset from the ACTIDEP_VS01 subject in ACTIDEP study, from PACS Neurinfo. Study card from Rennes. Ends after a very long time with 504 Gateway Time-out. 
Potential issues adressed by Anthony and Yao (thank you +++ to both of you)
Study card rule : Always, Transmission Coil = BODY also used in ADDICTO study with same cmrr sequence also longer repetition time. Since defined as always should not rely on the DICOM tags at all, whether the coil is defined or not, at least to my understanding. 
Besides, all other datasets in the same examination went through (same rule applied). 
The study will start in september and 60 subjects will be included both in Rennes and Tours with the same imaging protocol exactly (both have Prisma scanners). We need to be able to upload the data and make a nice impression in Tours with Shanoir. :)
Yao, I let you complete with what you found.

**Comment by yyao1231** [comment]
two errors in the log: 

- [org.shanoir.core.action.impl.MrDatasetAcquisitionHome]

          setFieldsByStudyCard : Error : the value is null for element
          className=org.shanoir.core.model.mr.MrProtocol,
          field=transmittingCoil, value=BODY

- [org.shanoir.core.action.impl.MrDatasetAcquisitionHome]

          createMrDataset : Important warning: the list of nifti files
          is empty for the serie PULSATILITE CMRR AP

**Comment by yyao1231** [comment]
First one resolved. In fact there is no coil found with the same manufacturer model(Siemens Prisma 3T MR 166066), center(Rennes) and coil name(BODY), as asked by the studycard. One sql script should be executed to correct the pb:  INSERT INTO COIL VALUES('106', NULL, '1', '39', '1', '166066', 'BODY').
For the moment I suggested Elise to remove the "Transmission Coil = BODY " to avoid this error.

**Comment by yyao1231** [comment]
Second one analyzed, the serie which causes problems of timeout is the "PULSATILITE CMRR AP" (see capture below)
![Capture1](https://user-images.githubusercontent.com/12045953/61859796-1c6bd800-aec9-11e9-9443-643548233766.PNG)
All other series are imported successfully in the examination 12/07/2019, ACTIDEP (id = 11554).
I will wait for Michael for debugging. If Elise you could tell us which is the particularity of this serie, it will help a lot!

**Comment by yyao1231** [comment]
Import done successfully with the "PULSATILITE CMRR AP.zip" in local dev environnement of Michael, also on shanoir neurinfo in the examination 11554. However, more than 500 datasets were created for this serie, which is strange. It explains maybe the timeout during the conversion nifti or application of studycard for so many datasets at time.
![Capture2](https://user-images.githubusercontent.com/12045953/61875925-f86dbe00-aeeb-11e9-8555-2f855067c24c.PNG)
![Capture3](https://user-images.githubusercontent.com/12045953/61875932-fd327200-aeeb-11e9-8b51-51d30d36d11a.PNG)

**Comment by ebannier** [comment]
Problem solved (Thank you Yao!) : bold (or another key word in the list) must be specified for the DICOM series to be converted as a 4D nifti and not a set of several (510) 3D niftis. I renamed the file before import and it all went through smoothly. I will also ask Tours to add bold in the sequence name.
