### ISSUE TITLE
White page issue

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1678]
Dear @youennmerel, I hope you are doing fine. I am having that issue now every day and it is quite annoying for our users. It would be great to solve it please, see my screenshot. Do not hesitate to exchange with Anthony about it. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
![Screenshot from 2023-04-19 15-08-51](https://user-images.githubusercontent.com/4560288/233568250-4d014382-92c3-465c-83bd-546c22813ce0.png)

**Comment by youennmerel** [comment]
It's indeed linked to a cache problem.

Angular generate new file name for ressources at each build, the browser can't find them under their new name.

Maybe this solution will work : https://stackoverflow.com/questions/55517060/clear-browser-cache-in-angular

**Comment by youennmerel** [comment]
No it won't, `outputHashing`is already set.

I think this is more like it : https://stackoverflow.com/questions/49267451/is-angular-clis-output-hashing-always-supposed-to-work-with-lazily-loaded-mod

**Comment by michaelkain** [comment]
Did not happen again to me on qualif since fix
