### ISSUE TITLE
CT datasets import and CT Acquisition equipment not defined - Yet CT Dataset available in study card

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#168]
CT acquisition equipment does not exist in Shanoir and users that want to import CD data define the equipment as MR acquisition equipment instead. Yet, in the study card CT dataset can be defined. 
It would be nice to add a CT acquisition equipment entry to define the equipments properly, together with the CT dataset tag in the study card. A minimal solution would do.

**Comment by michaelkain** [comment]
Hi Julien, hi Jean-Come, in any case we would have to wait for the feedback of the testers, I think the most important next feature is the import of CT Datasets, a very minimal version. Today the users are used to import CT files as MR Datasets, just to have the files in Shanoir. There are multiple examples in Neurinfo, I will have to find again. The idea is to have clearly identified CT Datasets, that are much lighter concerning metadata and everything than MR. I see it coming, that when we go live, the users could be surprised, that it does not work as before. The new import excludes CT series for the moment. I think it would be a great idea if you both could work on that feature as a kind of pair-programming project, if okay for you.

**Comment by jcomedouteau** [comment]
@Nunien can close this ?
