### ISSUE TITLE
Coil creation in user interface

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#169]
It is not possible to create coils for new acquisition equipments on Shanoir old / neurinfo. According to Yao, this was dealt with by Julien is ready for deployment but not deployed yet.

**Comment by yyao1231** [comment]
`According to Yao, this was dealt with by Julien is ready for deployment but not deployed yet.` 
Interface developed since long time, needed to be deployed on the hybride system shanoir old/ shanoir ng of neurinfo.
For me, issue added to the Roadmap of shanoir ng defined by Julien since last year.
