### ISSUE TITLE
[Related datasets] Error while loading examinations in import context with study with related datasets

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1695]
GIVEN
A user with rights on a study A
This study has related datasets on a study B
When trying to load examinations linked to a subject and a study (study tree OR import context)
-> An error occures.

1) Create a new method or add a boolean to know if we want the related datasets or not
2) Check user rights on related dataset studies before returning them

**Comment by youennmerel** [comment]
Ok in qualif when authenticated as the affected user

**Comment by youennmerel** [comment]
See https://github.com/fli-iam/shanoir-ng/pull/1696
