### ISSUE TITLE
Failing import Select all for TENSOR and Spectroscopy datasets

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#170]
The TENSOR and Spectroscopy datasets are not images and cannot be converted to nifti. We noted that the DICOM download of several of these files at a time was not working. Yet they can be downloaded individually. 
For the diffusion data (TENSOR is a derived dataset from the diffusion data) it is recommended to start from the native diffusion dataset for the processing, recomputing the TENSOR dataset from the bval and bvec information found in the DICOM tags.

**Comment by michaelkain** [comment]
Spectroscopy is solved, now working (original dicom + enhanced versions), I will have a look on tensor
