### ISSUE TITLE
huge dicom files

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#1702]
we recently had an issue importing big (3GB) DICOM diffusion data and also downloading them. More info in a direct message.

**Comment by michaelkain** [comment]
Hi @youennmerel, it would be great to test the import please. Thank you, Michael

**Comment by youennmerel** [comment]
The issue was linked to the size of the DICOM files : 28 GB, too much for the mounted filesystem size.

We tested it by temporarily increasing the allocated size, and the import went well (it took 30 minutes).
