### ISSUE TITLE
Failing password reset reported

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#171]
A user reported not receiving an email after clicking on reset password. 
This has happened in the past when the email landed in the spam folder/was blocked. 
Or when the account had expired : no clear error message there to tell the user to report to us (no contact form either) to extend the account once it has expired 
Anthony went through the logs and did a reset of some kind. 
I changed the user type and the mail was received.

**Comment by michaelkain** [comment]
I hope this is working now
