### ISSUE TITLE
blank page and error shown when opening a public study for which we don't have access

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1750]
Study list shows:
 - studies for which we have access
 - public studies for which we don't have access

Opening the 2nd should show access-request page and not a blank page

**Comment by jcomedouteau** [comment]
This is linked to the new tab clic, but I'm frankly quite lost on how it works currently !
We don't use the goToViewFromEntity method defined after onRowClick..
