### ISSUE TITLE
Bug - Acquisition equipment creation

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#176]
Etude Braini. Message de Grenoble : Comment ça se fait que la Brillance Philips qui est un équipement CT de Madrid apparaisse ici avec le no de série de notre achieva 38325 (qui est donc en double dans les numéros de série)? On vient de le créer - sans numéro de série, on ne le connaît pas encore - et on a vraiment mis Madrid comme centre... 
C'est ce qui apparaît quand on regarde les centres associés à l'étude Braini mais quand on regarde le centre et l'équipement, c'est bon... :-\

**Comment by michaelkain** [comment]
I think this has been solved by Julien recently.
