### ISSUE TITLE
[Deployment] dcm4chee 5.14 not in maven repo anymore for anonymization maven profile

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1784]
Change maven pom.xml dcm4chee version in anonymization to 5.27

**Comment by michaelkain** [comment]
Hi @jcomedouteau, I will do that on my PR for multi-frame optimization. I increased dcm4che3 already to 5.30.0 in import. With kind regards, Michael

**Comment by michaelkain** [comment]
and will do so in other pom.xml (datasets, exchange etc.)

**Comment by jcomedouteau** [comment]
Ok, i'm closing this one.
