### ISSUE TITLE
CRUD of manufacturer model is KO

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1825]
- Creating/updating/deleting a new manufacturer
- Creating/updating/deleting new manufacturer model 
- Displaying a manufacturer

fail with the error : 

```
{
	"code": 500,
	"message": "Cannot invoke \"org.shanoir.ng.manufacturermodel.repository.ManufacturerRepository.save(Object)\" because \"this.repository\" is null",
	"details": null
}
```

**Comment by michaelkain** [comment]
I will try to solve this before my holidays.

**Comment by michaelkain** [comment]
perfect, thank you @pierrehenri-dauvergne !

**Comment by pierrehenri-dauvergne** [comment]
Fixed in this PR : https://github.com/fli-iam/shanoir-ng/pull/1794
