### ISSUE TITLE
Remove CAN_SEE_ALL right as admin of study

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1828]
- Create a study (as expert)
- Remove 'CAN_SEE_ALL' rights for yourself (keep all the others)
- Error is thrown and I can't see the study I just created

**Comment by michaelkain** [comment]
Hi @pierrehenri-dauvergne, I hope you are doing fine. Thank you, that you found this error. If @julien-louis, master of roles and rights, agrees on this, I propose to disable the removal of that flag for a member. When I am not completely wrong, it was like this before. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
@pierrehenri-dauvergne It would be great to integrate this aspect and definition into https://github.com/fli-iam/shanoir-ng/wiki/Roles-and-rights-specification
