### ISSUE TITLE
[Talk] Subject and studies

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1839]
Hello,

This issue is here so that we can talk about Subjects in studies.
Currently, one subject can be part of multiple studies. In a study details, subject tab, we can add a subject in the study and we can set a "subject id for this study" (change the name of the subject in shanoir for this particular study).
One issue is that inside a DICOM, there's a field called "patient name" and sometimes, if another id is set to this subject, the subject name (in the study) and the patient name (in the DICOM) are different and that can cause a mess.

Should we allow subjects to be part of multiple studies ?
Should we allow subjects to have different names (one per study) ?
Is this feature used ? If so, how ? 

Maybe we can find a better way to do things for people who need this feature.

Thoughts ?

**Comment by ebannier** [comment]
As far as Neurinfo is concerned, this feature is not used. A subject can be part of multiple studies but will have a different code for each study (as determined by the study)
