### ISSUE TITLE
[preclinical] Cannot create a new pathology model

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1847]
Connect -> preclinical subjects -> choose one -> edit -> add pathology -> click on "+" on pathology model
Try to create one -> error
![image](https://github.com/fli-iam/shanoir-ng/assets/7604176/1ee9abde-aa68-4294-88c0-ea8a6ac01a18)

"Validation failed for classes [org.shanoir.ng.preclinical.pathologies.pathology_models.PathologyModel] during persist time for groups [jakarta.validation.groups.Default, ]\nList of constraint violations:[\n\tConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=pathology, rootBeanClass=class org.shanoir.ng.preclinical.pathologies.pathology_models.PathologyModel, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}\n]"

This is weird, as we send all what's necessary.

**Comment by pierrehenri-dauvergne** [comment]
Other issues related to preclinical:

- No options in "dose unit" field (preclinical subject > edit > add therapy):

![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/74d64920-f58c-46a2-acf1-54cf9cac9039)

- Lines of tables (pathology and therapy) shouldn't be clickable:

![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/bf0a096b-9f9a-4522-a457-6c0735e9e406)

- Edit and existing pathology, change a value and update. The existing pathology appears twice in the table:
 
![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/92edd1ef-4e92-4169-a911-db13375d53ea)
