### ISSUE TITLE
Index 0 out of bounds for length 0 during import

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1905]
After import from PACS, this error is shown:

![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/d8375744-a62e-49b8-9d13-12c8358fe510)

**Comment by pierrehenri-dauvergne** [comment]
Another issue is that when importing, if there are multiple examination and the user select only one, the import ends up in error.

**Comment by ebannier2018** [comment]
We often have multiple exams for the same subject. Two for subject MAPMS_0138 in particular : MAP-MS MOELLE and 
MAP-MS ENCEPHALIQUE. MAP-MS MOELLE was imported without any issue, MAP-MS ENCEPHALIQUE keeps failing. In the past, we could import one or the other without any problem. Has something changed in the code in this regard ?
