### ISSUE TITLE
Download dataset and check for CAN_DOWNLOAD right

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1919]
I belong to a study with CONFIRMED and CAN_SEE_ALL rights. All other rights are not available.
I can see the datasets in solr, select them and click download

The job end-up in error with unrelated message:

![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/a8fd3256-69d8-4562-8b0c-bec13255fb7e)

**Comment by jcomedouteau** [comment]
This is corrected too.
