### ISSUE TITLE
Import Processed Datasets: migrate code into sh-ng

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#194]

**Comment by michaelkain** [comment]
Hi Jean-Come, lets at first exchange on this with Julien in the daily, where we are today.

**Comment by michaelkain** [comment]
Hi Jean-Come, we have to exchange on this with Arthur too. Maybe he already implemented all this on his Boutiques branch.

**Comment by arthursw** [comment]
I'm not sure, what is "Import Processed Datasets" exactly? A way of importing and processing data?
