### ISSUE TITLE
Challenges: processed datasets has multiple inputs migrate into sh-ng

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#195]

**Comment by michaelkain** [comment]
And keep link with pipeline, e.g. from Boutiques, that has been used.

**Comment by michaelkain** [comment]
change this together with the import of processed datasets in NG, change the model in a way, that one processed datasets can have multiple datasets as origin

**Comment by jcomedouteau** [comment]
Do you want me to start / continue (as i had already started) the migration of processed datasets ?

**Comment by michaelkain** [comment]
Implemented with multiple dataset processing PR.
