### ISSUE TITLE
Download issue: Chrome with unzip=true

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1968]
see email from CH

**Comment by julien-louis** [comment]
mail :

Bonjour Julien,

 

Je viens d’essayer et ça a fonctionné. J’ai refait en cliquant unzip et certains dossiers sont vides (ne contiennent pas les fichiers dicom). J’ai aussi eu le cas la semaine dernière où il y avait les fichiers dcm mais ils faisaient 0ko…

Ci-dessous les erreurs :
![image](https://github.com/fli-iam/shanoir-ng/assets/21199767/4593bf44-d8c2-4e67-9b9f-2cc9c99bd825)

Le problème n’est pas systématique.

**Comment by michaelkain** [comment]
Hi @julien-louis, is this issue solved?
