### ISSUE TITLE
Create Acquisition Equipment Shanoir NG

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#198]
Would it be possible to add a wildcard search in the center field and in the acquisition equipment field? The list of equipments and centers is getting long and we need to read it all to find the one we are looking for. For the equipment, knowing the device name (i.e. the first letter) we can scroll directly to these letters but for the centers, naming can be random and we need to read them all.

**Comment by ebannier** [comment]
Actually the list of equipments is chronological (date of creation), not alphabetical. If you could change it to alphabetical it would be a good start. Wildcard could come later. 
For centers, it is alphabetical, but we do not know which first letter to look for so wilcard would be very useful.

**Comment by jcomedouteau** [comment]
In the center and equipement lists, you can now do a wildcard search and order following the field you want.
In select boxes, @Nunien has developed a powerfull search bar.

Closing this
