### ISSUE TITLE
ShUp: check quality cards in ShUp

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1980]
Hi Laurent, I hope you are doing good.
It would be great, if you could, as already asked by you, have an intro on quality cards with Julien.
I merged today into develop the last version, so you can work on and with qualif.
My idea is
- extend ShUp, as it queries today for the list of study cards, to query the quality cards, that are "for-import" for the study selected to import
- use the ExaminationAttributes structure from Julien, to read locally the dicoms and check their quality, and refuse the import in case
- use the code from MS Datasets, as max, as possible
With kind regards,
Michael

**Comment by LaurentPV** [comment]
Hi Michael, 
what do you mean by "MS Datasets" ?

**Comment by michaelkain** [comment]
DICOM patient == subject
		DICOM study == examination == importJob	
			serie == acquisition
				volume == dataset
					instances==images

- ImportFinishActionListener: add method qc after prepareImportJob (now complete),
before starting runnable thread (to avoid unnecessary pseudonymization or upload to server)
- in case of KO: display pop-up with QC error and create new state in imports tab-table
QC_ERROR
- ImportJob extend: qc-done already in ShUp
- allow re-try of exam import (ImportJob) in case error on server in quality card
- selection of study in ImportDialog: searches quality card to use from server
- create ExaminationAttributes only with acquistion attributes and ignore conditions on datasets for the moment
