### ISSUE TITLE
ShUp: basic.properties, found key= in my basic.properties

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1982]
Hi Laurent, my tests went fine on your PR, thx.
But I am finding now in my basic.properties an entry "key=xxx", that comes from another file. I think, there might be a minor issue, that we mix up some key-values from another file, or this key, was only in the memory before and now he is written to the basic.properties. With kind regards, Michael

**Comment by LaurentPV** [comment]
I just tested again and do not have this issue. I'll keep on checking.
What do you mean when you say that the entry comes from another file ?
