### ISSUE TITLE
Quality cards: probably a logical error with and-conditions

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1985]
Hi @julien-louis, I hope you are doing fine.
I think, there might probably remain a logical error within one quality card rule, please see my screenshots.
I want to tag an exam as "error", when it does not contain any TOF (1 dataset) AND not contain any GADO (1 other dataset).
All exams, that contain one TOF, but no GADO serie, are NOT tagged with "error". I would expect it to be tagged with error,
when all AND conditions are fullfilled? see my second screenshot of exam  id = 5283, that does not contain any GADO.
![Screenshot from 2023-12-13 13-40-54](https://github.com/fli-iam/shanoir-ng/assets/4560288/c58b5e89-4ab6-4022-a71d-aceb8a2fa166)
![Screenshot from 2023-12-13 13-42-20](https://github.com/fli-iam/shanoir-ng/assets/4560288/52b51621-7a2e-4bf3-8c44-7101a57439ed)

**Comment by julien-louis** [comment]
I think we can close this one
