### ISSUE TITLE
Study card AND, OR, NOT conditions

### ISSUE THREAD

**Issue by ebannier** [fli-iam/shanoir-ng#199]
Following a discussion with JL last week, when creating a study card, and the use of AND conditions : 
- we can do ANDs when adding conditions 
- we do not need ORs necessarily since we can create multiple conditions with the same outputs, still if not too much work it could be nice to have this OR available
- yet when we have a T2 keyword and a T2* or T2STAR keyword, with different outputs (resp. T2 contrast or T2* contrast), a priority (if it exists) or a NOT condition (T2 NOT STAR NOT *) would be useful.

**Comment by Nunien** [comment]
Ok, I see what you mean. I will look if there is a better solution for that. Thank you for your feedback. 

Julien

**Comment by jcomedouteau** [comment]
Solved by @Nunien
