### ISSUE TITLE
Propagate study suppression to other microservices, eg. ms datasets

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#200]
One study could be deleted today in shanoir ng. But it does not propagate to other microservices. For example, study suppression should also clean datasets of this study. 
To be decided, if datasets of one no-more-existing study should be removed, or these datasets should become standalone (studyId = null in dataset table).

**Comment by jcomedouteau** [comment]
This is done with rabbitMQ now. Closing this.
