### ISSUE TITLE
Boutiques polishing: test, CSS, refactoring, error management...

### ISSUE THREAD

**Issue by arthursw** [fli-iam/shanoir-ng#201]
- Finish development of Boutiques API / Microservice with Spring boot: 3 days,
 - Write backend tests? 3 days,
 - Mastering RxJS: 2 day,
 - Write CSS: 3 days (CSS is not friendly),
 - Handle errors correctly on the Backend and Frontend: 2 days

Total:  13 = 2 weeks and 3 day.

The time estimation is pessimistic, nevertheless the development will probably take longer than expected; as always.

**Comment by michaelkain** [comment]
Closed as old.
