### ISSUE TITLE
oneshot script wasn't executed ?

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#2037]
Currently the O....EP prod instance is at version NG_v2.0.7-0-gbfe725b0c

This "one shot" sql script is present in that version : https://github.com/fli-iam/shanoir-ng/blob/bfe725b0c5807adf30bc7a9c76655586a0e42f62/docker-compose/database/oneshot-updates/clean_up_studycards.sql

but I think it was not executed. For exemple, if I execute the first sql command on the prod mysql (replacing delete by count(*)) I have 

```
mysql@shanoir-2016 ***ep-prod-datasets> select count(*) from study_card_condition_join where study_card_rule_id in (select id from study_card_rule where id not in (select rule_id from study_card_assignment));
+----------+
| count(*) |
+----------+
|     3444 |
+----------+
1 row in set (0,055 sec)
```

it should be 0

same for the other sql commands in the script.

**Comment by michaelkain** [comment]
No Anthony, you are right. oneshot is for manual execution only. I close.
