### ISSUE TITLE
Delete examination cause FK constraint fail (dataset_property)

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2095]
Lors de la suppression d'un examination:

> 2024-02-22T11:15:09.928+01:00  INFO 1 --- [http-nio-9904-exec-2] o.s.n.dicom.web.service.DICOMWebService  : Rejected from PACS: http://pacs:8080/dcm4chee-arc/aets/AS_RECEIVED/wado?requestType=WADO&studyUID=1.4.9.12.34.1.8527.5294640950452055218079679608723825499290&seriesUID=1.4.9.12.34.1.8527.6034874622579783855177980777501232182217&objectUID=1.4.9.12.34.1.8527.9316395253399234628067140650340561318386&contentType=application/dicom
> 2024-02-22T11:15:09.957+01:00  INFO 1 --- [http-nio-9904-exec-2] o.s.n.dicom.web.service.DICOMWebService  : Deleted from PACS: http://pacs:8080/dcm4chee-arc/aets/AS_RECEIVED/wado?requestType=WADO&studyUID=1.4.9.12.34.1.8527.5294640950452055218079679608723825499290&seriesUID=1.4.9.12.34.1.8527.6034874622579783855177980777501232182217&objectUID=1.4.9.12.34.1.8527.9316395253399234628067140650340561318386&contentType=application/dicom
> 2024-02-22T11:15:11.265+01:00 ERROR 1 --- [http-nio-9904-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot delete or update a parent row: a foreign key constraint fails (`datasets`.`dataset_property`, CONSTRAINT `FK1mcyt0h60808jmj3shlvge9c8` FOREIGN KEY (`dataset_id`) REFERENCES `dataset` (`id`))
> 2024-02-22T11:15:11.366+01:00 ERROR 1 --- [http-nio-9904-exec-2] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service.
> 
> org.springframework.dao.DataIntegrityViolationException: could not execute statement [Cannot delete or update a parent row: a foreign key constraint fails (`datasets`.`dataset_property`, CONSTRAINT `FK1mcyt0h60808jmj3shlvge9c8` FOREIGN KEY (`dataset_id`) REFERENCES `dataset` (`id`))] [delete from dataset where id=?]; SQL [delete from dataset where id=?]; constraint [null]

**Comment by michaelkain** [comment]
Hi @youennmerel, I hope you are doing fine. It would be great to solve this issue as soon as possible, as it blocks deletion of now nearly all exams on ofsep-prod. Thank you and with kind regards, Michael
