### ISSUE TITLE
Delete entities from the table

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#21]
for subject: Status Code: 204 from the back
for study: Status Code: 403 from the back
for examination: no request sent to the back, "An unexpected error occured" displayed in the front
for dataset: same as for examination
for center: Status Code: 422 from the back, "This center cannot be deleted. It is associated with acquisition equipment(s) and study(ies)" warning displayed in the front. => seems perfect
for acquisition-equipment: Status Code: 200. maybe we could display a message to confirm the deletion?
for coil: Status Code: 200. Message confirms the deletion "The coil sucessfully deleted". => seems perfect

we need to uniform the behavior of back and front for all these deletions.

**Comment by Nunien** [comment]
Should be reevaluated after the role & rights pull request is accepted

**Comment by Nunien** [comment]
* subject : 204 :heavy_check_mark:
* study: 204 :heavy_check_mark:
* examination: no request sent to the back, "An unexpected error occured" displayed in the front
* dataset: no request sent to the back, "An unexpected error occured" displayed in the front
* center: 204 / 422 from the back, "This center cannot be deleted. It is associated with acquisition equipment(s) and study(ies)" warning displayed in the front. => seems perfect :heavy_check_mark:
* acquisition-equipment: Status Code: 200. maybe we could display a message to confirm the deletion?
* coil: 204 :heavy_check_mark:

**Comment by Nunien** [comment]
All fixed, a pull request will come soon.
