### ISSUE TITLE
NIFTI conversion fails (Missing start boundary)

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#2128]
For some datasets on OFSEP, the NIFTI conversion (with any converter) will fail.

The following logs are written in MS datasets :

```java
ofsep-prod-datasets-1  | 2024-03-05T11:03:59.632+01:00 ERROR 1 --- [nio-9904-exec-3] o.s.ng.download.WADODownloaderService    : A dicom file could not be downloaded from the pacs:
ofsep-prod-datasets-1  | 
ofsep-prod-datasets-1  | jakarta.mail.internet.ParseException: Missing start boundary
ofsep-prod-datasets-1  | 	at jakarta.mail.internet.MimeMultipart.parse(MimeMultipart.java:667)
ofsep-prod-datasets-1  | 	at jakarta.mail.internet.MimeMultipart.getCount(MimeMultipart.java:324)
ofsep-prod-datasets-1  | 	at org.shanoir.ng.download.WADODownloaderService.extractDICOMFilesFromMHTMLFile(WADODownloaderService.java:421)
ofsep-prod-datasets-1  | 	at org.shanoir.ng.download.WADODownloaderService.downloadDicomFilesForURLs(WADODownloaderService.java:282)
ofsep-prod-datasets-1  | 	at org.shanoir.ng.dataset.service.DatasetDownloaderServiceImpl.reconvertNifti(DatasetDownloaderServiceImpl.java:262)
ofsep-prod-datasets-1  | 	at org.shanoir.ng.dataset.service.DatasetDownloaderServiceImpl.massiveDownload(DatasetDownloaderServiceImpl.java:158)
ofsep-prod-datasets-1  | 	at org.shanoir.ng.dataset.controler.DatasetApiController.downloadDatasetById(DatasetApiController.java:330)
ofsep-prod-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ofsep-prod-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
ofsep-prod-datasets-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ofsep-prod-datasets-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

The error occurs in `WADODownloaderService.extractDICOMFilesFromMHTMLFile(...)`, when `MimeMultipart.getCount()` is called.

These methods are only used when reconverting to NIFTI (see `DatasetDownloaderServiceImpl.reconvertNifti(...)`), and the mass download is OK for these DICOMs otherwise. Shouldn't we use the same method for all download, those for internal use included ?

**Comment by mgaubert** [comment]
Hello,
This issue is closed but I still have errors. I tried again to download some NIFTI images on shanoir-ofsep (using shanoir_downloader) and it failed while DICOM are available (datasetId: 186542 for example). 
This update has not been released yet?
Malo

**Comment by jcomedouteau** [comment]
Bonjour Malo ! 

En effet, ce problème est résolu, mais le fichier nifti pour ce dataset ne semble pas disponible. Tu peux le reconvertir en passant une argument converterId pour spécifier le convertisseur dicom -> nifti.
1 -> dcm2nii_2008-03-31
2 ->  mcverter_2.0.7
4 ->  dcm2nii_2014-08-04 
5 ->  mcverter_2.1.0 
6 ->  dcm2niix 
7 ->  dicomifier   
8 ->  mriconverter  

Jean-Côme

**Comment by mgaubert** [comment]
Tu veux dire faire la conversion dans SolR? 
J'ai >300 images, ça risque d'être un peu fastidieux de cliquer sur tous. :confused: 
Et aussi, je voulais reprendre le même schéma de téléchargement que les autres, notamment parce que j'ai des scripts derrière pour réorganiser les données comme je veux.
Mais si ça n'est pas possible de télécharger directement les NIFTI depuis Shanoir, je me débrouillerais.

**Comment by jcomedouteau** [comment]
L'idée serait de le faire via shanoir-downloader, il faut juste rajouter un argument dans l'appel http:
(à la ligne 310, essaye de modifier comme ceci: 
params = dict(datasetIds=dataset_ids, format=file_format, converterId=6)

Jean-Côme
