### ISSUE TITLE
Copy of dataset fails [Duplicate entry for key]

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2157]
After a bootstrap --clean, copy of dataset fails

1. Database is not the same in local and qual (UNI / MUL key for origin_metadata and updated_metadata)

![image](https://github.com/fli-iam/shanoir-ng/assets/117283961/6209df64-b355-454c-8290-fe2c8f4b8b19)

2. Mr_Protocol constructor should call a new origin_metadata constructor
3. Check in prod if there are no issue with copied datasets

**Comment by julien-louis** [comment]
notes : 
to check duplicates in the db : 
```select origin_metadata_id, count(origin_metadata_id) as cnt from mr_protocol group by origin_metadata_id having (cnt > 1);```

fortunately no copies has been done yet in prod
