### ISSUE TITLE
Dicom Metadatas don't appear in study/quality card condition dropdown menu

### ISSUE THREAD

**Issue by LaurentPV** [fli-iam/shanoir-ng#2167]
The metadata "number of slices" in a TOF Dicom dataset cannot be used in a quality card or study card for now because some manufacturer such as Philips use the tag 2001,1018 to store the information but this tag does not appear in the Shanoir dropdown menu.
![Capture d’écran 2024-03-28 à 10 20 06](https://github.com/fli-iam/shanoir-ng/assets/26709236/0a82bd60-f6f2-493e-8b9a-969c42c2a1f5)

**Comment by LaurentPV** [comment]
Issue closed because no solutions are ideal for this problem.

**Comment by julien-louis** [comment]
@LaurentPV We could totally maintain a proprietary dicom tag list. Do you know if these tags can overlap from a compagny to another ?

**Comment by LaurentPV** [comment]
Yes, that's the problem, metadata are too heterogeneous, I closed the issue because Mickael is right, we have to calculate this value when importing to set a new datasetAcquisition variable.
