### ISSUE TITLE
new UCAN user: study list empty

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#2171]
A new Shanoir UCAN user tells me he's having trouble selecting the study in the "context" tab:
"I switched from firefox to Chrome and it gives me an error when I go to study selection "error"
is displayed at the bottom in a red banner.
With firefox, he has ab empty list in "select a research stdy" in set clinical context.
I did add it as a UCAN member 
guillaume Charbonnier, besançon center, g1charbonnier@chu-besancon.fr

Can you please help me find out what the problem is?
Thank you

**Comment by pierrehenri-dauvergne** [comment]
I gave him the "Can see all" right, maybe it will help.
