### ISSUE TITLE
HTTP 500 ERROR when trying to request DICOM Metadata endpoint

### ISSUE THREAD

**Issue by LaurentPV** [fli-iam/shanoir-ng#2215]
In production and qualif, using the "Show DICOM Metadata" button from the Dataset page returns an http 500 in more than half of the datasets. 
Same problem when trying to directly request the endpoint datasets/datasets/dicom-metadata/{dataset_id}

When testing in local after importing one of those dataset everything works fine.

examples of dataset ids that have the issue : 
475826
439966
407524
457001
441044
471207
419475
436917
451134
439232
471947
477589
479610
479744

**Comment by pierrehenri-dauvergne** [comment]
Actually, every dataset of examination 19953 and 21616 and returning this error. I'm guessing many other examination are concerned

**Comment by LaurentPV** [comment]
When reimporting the dataset in qualif then we have access to the metadata tab again.
On the Dataset service, the error log is : 
ERROR 1 --- [tomcat-handler-7] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service.
org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"errorMessage":"No matches found."}"

**Comment by LaurentPV** [comment]
The issue cannot be reproduced on the new neurinfo qualif hosted on Eskemm.
I close the issue.
