### ISSUE TITLE
Show import date of exam and user who did the import

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2224]
The idea is to trace the importing user and the date and display it somewhere in the model/pages. Demand of CG.
Also consider #1796
Hi @jcomedouteau, do you think you could specify this and think of where to put the information?

**Comment by jcomedouteau** [comment]
On dataset entity, we have creation date field which corresponds to examination date. This should not be the case probably. This is already displayed in shanoir on dataset detail:
![image](https://github.com/fli-iam/shanoir-ng/assets/7604176/3f42e68e-5637-4ae5-a4d7-f23c243178b5)
We need to update it to correct #1796 
We have to change it here:
![image](https://github.com/fli-iam/shanoir-ng/assets/7604176/308a51bf-ba43-48a2-80b1-3698346ad6b4)

In dataset microservice, we have no link to user (nothing in DB), I don't know if it's a good idea to specifically display it on dataset page.

On an other hand, I was thinking of something like displaying an "history" based on either an object or a study.
We could imagine having a "History" tab in study detail, displaying all the events linked to this study (and thus "sub" objects linked to this study)
Then we would be able to look for a specific event on a specific ID or something like this.
We need to check that this does not overwhelm events table (and create adapted indexs)

**Comment by jcomedouteau** [comment]
After discussion with Michael, here is what we've reached:
- Rename in solr the column "creation date" in "series date" (this column is hidden by default and it's a good thing, it is rarely different from examination date)
- Add a new column in solr to track dataset_acqusition.import_date that is currently existing
- Add a new attribute "user" as string (username) in dataset_acquisition. Fill it in every place we create a dataset acqusition (mainly dataset_acquisition_strategy implementations)
- Display this attribute on dataset_acqusition detail
- Add a solr column with this username in solr
 
Not mandatory:
- Add a SQL script to update existing acquisitions with user, something like (to be completed and tested of course)

update dataset_acquisition a set user = (select username from users.user u where u.id = (select user_id from users.events ev where ev.event_type = "importDataset.event" and ev.object_id  = a.examination_id))

Another issue will be created for study history
