### ISSUE TITLE
Implement DataOf

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#223]
see in OLD Dataset.java :

```
/** list of the studies for which this dataset is a data. */
@OneToMany(cascade = CascadeType.ALL, mappedBy = "dataset")
@Cascade( { org.hibernate.annotations.CascadeType.SAVE_UPDATE, org.hibernate.annotations.CascadeType.DELETE_ORPHAN })
private List<RelStudyDataset> relStudyDatasetList = new ArrayList<RelStudyDataset>(0);
```

This is linked to a functionality that record a dataset a data of another study. One use is to search datasets as "data of" a certain study (see OLD dataset list page).

TODO : 
* See what other uses this relationship had in OLD
* Implement it if needed

**Comment by yyao1231** [comment]
2530 datasets concerned today in Shanoir Neurinfo DB.

**Comment by Nunien** [comment]
MySQL [shanoirdb]> select study_id, name from STUDY where STUDY_ID in (select distinct STUDY_ID from REL_STUDY_DATASET);
+----------+-----------------------------------+
| study_id | name                              |
+----------+-----------------------------------+
|       85 | *Volontaires Sains                |
|        9 | 3D T1                             |
|       32 | ASL SENSE 2                       |
|       14 | asl_SEP                           |
|       80 | AVCPOSTIM MORPHO                  |
|       94 | EMISEP                            |
|      160 | EMISEP_Derived_DiffusionVS        |
|      124 | ICAN                              |
|       51 | IQALY-SEP+                        |
|       39 | NCE MRA                           |
|       58 | NCE MRA PHANTOM                   |
|      140 | Sharing_SynesthesiaFunctionalData |
|      134 | Sharing_SynesthesiaStructuralData |
|      126 | test                              |
|      145 | Tests_Prisma                      |
|      127 | Test_DerivedStudy                 |
|       11 | Transfert                         |
|       18 | USPIO-6 ASL                       |
|       59 | USPIO-6 C                         |
+----------+-----------------------------------+

**Comment by jcomedouteau** [comment]
Implement this for Michel Dojat Synesthesia study

**Comment by jcomedouteau** [comment]
Editing a dataset, it is possible to link it to another study:

![image](https://user-images.githubusercontent.com/7604176/103626681-d8de2000-4f3c-11eb-9eed-b3c8b850ff08.png)

Then, it appears in the study detail and a user can see this dataset.
