### ISSUE TITLE
Export table contents as .csv

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#2246]
Add a generic functionality that allow a user to export the content of a table as a .csv file.

Design proposition :
![image](https://github.com/fli-iam/shanoir-ng/assets/59697998/aaf42175-a603-481c-b98e-7a628a54c259)

**Comment by pierrehenri-dauvergne** [comment]
Fixed by https://github.com/fli-iam/shanoir-ng/pull/2384
