### ISSUE TITLE
dicom-metadata error on shanoir-ofsep for datasets processed with VIP

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2288]
Hi @youennmerel, hi @jcomedouteau,
there seems to be an issue with all datasets, that have been processed by VIP.
The click on dicom-meta-data leads to an error.
14:22 - Error from datasets server 
2024-07-02 14:22:38
[500] INTERNAL_SERVER_ERROR
https://shanoir-ofsep.irisa.fr/shanoir-ng/datasets/datasets/dicom-metadata/778024
message : 404 Not Found: "{"errorMessage":"No matches found."}"

**Comment by jcomedouteau** [comment]
Found the root of the problem, solution may have to be discussed:
![image](https://github.com/fli-iam/shanoir-ng/assets/7604176/9e7d912b-3ea8-4997-98e4-ac990cbb30b4)

We updated this for exam deletion, we need to update it to be adapted for both
