### ISSUE TITLE
UCAN account expired

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#2299]
UCAN user Pierre Thouant (pierre.thouant@chu-dijon.fr) has asked 3 times to extend his account, and receives the following response: "extension request is awaiting validation by an administrator...".
For my part, I don't see any validation possible.
Can you please help us?
Thank you !

Solène

**Comment by jcomedouteau** [comment]
Hi Solène,
The account was extended, we will update our interface so that admin better see extension requests.
Have a nice day,

Jean-Côme
