### ISSUE TITLE
when I go back to the home page, I get this error "folderIconPath" in the console:

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#23]
![capture](https://user-images.githubusercontent.com/12045953/47142082-6aacd480-d2c2-11e8-8d8c-a806191939a9.PNG)

_Originally posted by @yyao1231 in https://github.com/fli-iam/shanoir-ng/pull/19#issuecomment-430925731_

**Comment by Nunien** [comment]
It's simply a missing picture. I will fix this.
