### ISSUE TITLE
[OHIF] Do not propose ohif viewer for every dataset. (EEG typically)

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#2301]

**Comment by pierrehenri-dauvergne** [comment]
I feel like it is already the case?
![image](https://github.com/user-attachments/assets/f76f7b57-f811-420f-a27a-416dee879882)

**Comment by michaelkain** [comment]
Hi @pierrehenri-dauvergne, thx for your analysis. Could you close the issue in case already done?
