### ISSUE TITLE
Import microservice uses more and more memory at each upload

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#231]
Every time I upload an archive (and then I abort the import) the memory used by the import docker container increases.

Use the command `docker stats` to see memory consumption.

**Comment by jcomedouteau** [comment]
Some file stream are not always closed, but it's not really relevant.
--> At some point, the MEM_USAGE stops to rise (~18%)
Cannot really reproduce.

**Comment by michaelkain** [comment]
same for me, I monitored constantly with many big data from ShUp and others, no increase seen over as J-C writes around 20%, so I close it as not reproducable
