### ISSUE TITLE
ShUp - NullPointerException on Subject.getSex() when no existing subject is selected

### ISSUE THREAD

**Issue by LaurentPV** [fli-iam/shanoir-ng#2342]
When trying to create a new Subject from ShanoirUploader Import Dialog we have the following error : 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.compareTo(String)" because the return value of "org.shanoir.ng.importer.model.Subject.getSex()" is null

The new way of managing subject in ImportFinishActionListener seems to cause this issue.

Also when this occurs the Import Dialog stays open without any Error message but only the greyed Import button.

**Comment by LaurentPV** [comment]
in ImportUtils.initUploadJob() we do uploadJob.setPatientSex(subject.getSex()); but the subject is not created at this point and we should get the sex from ImportJob.getPatients().getSex() instead.

**Comment by michaelkain** [comment]
Hi @LaurentPV, I think the issue comes from the sex == "O" for OTHER from our test data. It is not correctly translated yet in ShUp as the mapping is missing. It would be great to update this. In human clinical routine this does not play a big role, but for quality control data it might be interesting. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
sorry, strange: first I created during my tests multiple subjects on my local server, new subjects and used existing ones, and I did not have the above error, and my info above is out-dated, as I added already the sex "O" to ShUp.

**Comment by michaelkain** [comment]
have you tested with n-exams n-patients? this would explain it: 
				if (firstPatient.getPatientID().equals(patient.getPatientID())) {
					importJob.setSubject(firstSubject);
				} else {
					return; // multi-patient not yet implemented, stop here
				}

**Comment by michaelkain** [comment]
the subject is set before the initUploadJob

**Comment by LaurentPV** [comment]
No, I just tested different imports from PACS or from dicom file. It occurs when creating a new subject on Neurinfo profile, not selecting an existing one already created on the study.

**Comment by michaelkain** [comment]
we will discuss during our meeting this afternoon :-), I tested profile Neurinfo this morning with new subject, on my local branch, hm, interesting

**Comment by michaelkain** [comment]
I tested my local state, from pacs + from disk, with Neurinfo-Qualif (real server, not locally) and I could import twice

**Comment by michaelkain** [comment]
solved on GitHub PR #2063, missing patientSex in DicomDirGenerator (import no-dicomdir), successfully tested by Laurent
