### ISSUE TITLE
New OHIF viewer: issues

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2350]
Hi @pierrehenri-dauvergne, I hope you are doing fine.
I tested yesterday with Youenn on ofsep-qualif the new viewer with examination 69946.
- It did not display the list of series, BUT in prod I can see the series list and it works
- this must be solved before going to prod please
- furthermore could you test if the endless??????? question marks error occurs as well in their docker locally, without Shanoir, maybe something is wrong with our integration and the reverse proxy config in nginx
- T1 VIBE3D30° relaxo seriesDescription (correct in shanoir, not in viewer)

**Comment by pierrehenri-dauvergne** [comment]
Opening the viewer from an exam's tree sends the user to a wrong URL

**Comment by michaelkain** [comment]
I close this to work with specific issues only
