### ISSUE TITLE
Vertical slider to the new tree view + keep buttons visible

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2392]
Hi @julien-louis,
I tested with Ican and to reach the bottom of the new tree view took very long.
Do you think you might please add a slider?
Thank you and with kind regards, Michael

**Comment by pierrehenri-dauvergne** [comment]
Sometimes studies have a lot of subject and you have to scroll a long time in the tree-view to find where you are. 
Could we make the tree-view auto-scroll to wherever you are in the tree?
