### ISSUE TITLE
Cant download Data from study 

### ISSUE THREAD

**Issue by alexpron** [fli-iam/shanoir-ng#2399]
During test session on ofsep qualif I could not download data from the study (Download error) 
![image](https://github.com/user-attachments/assets/4503648f-02fd-45f3-a79c-7a8223e78588)

**Comment by michaelkain** [comment]
Hi @jcomedouteau, I hope you are doing fine. I think I asked Pierre-Henri already to remove this button, as downloading an entire study might not be the best idea. With kind regards, Michael

**Comment by jcomedouteau** [comment]
Ok for me
