### ISSUE TITLE
Cannot download ofsep statistics

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#2402]
datasets-1  | java.io.FileNotFoundException: /tmp/202/shanoirExportStatistics.tsv (No such file or directory)
datasets-1  | 	at java.base/java.io.FileInputStream.open0(Native Method)
datasets-1  | 	at java.base/java.io.FileInputStream.open(Unknown Source)
datasets-1  | 	at java.base/java.io.FileInputStream.<init>(Unknown Source)
datasets-1  | 	at org.shanoir.ng.dataset.controler.DatasetApiController.zipSingleFile(DatasetApiController.java:512)
datasets-1  | 	at org.shanoir.ng.dataset.controler.DatasetApiController.downloadStatistics(DatasetApiController.java:638)

Zip seems to be generated.
But tsv is not generated correctly.

![image](https://github.com/user-attachments/assets/02350dfc-9132-412a-af08-22bb9fe6cc0d)

**Comment by jcomedouteau** [comment]
Actually it seems to be working with a simpler request. Maybe my request is not OK

**Comment by jcomedouteau** [comment]
The Cohorte Principale.* request seems to fail everything (the other ones are OK, CISCO.* for example)

**Comment by pierrehenri-dauvergne** [comment]
Request durations in stats export should be fixed by https://github.com/fli-iam/shanoir-ng/pull/2416

**Comment by jcomedouteau** [comment]
Corrected
