### ISSUE TITLE
Production start : Shanoir OLD -> NG database migration

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#241]
From the meeting : 
18/12/2019 - Shanoir NG migration - Y. Yao, A. Masson, M. Kain, M. Simon

- Run the creation script on the new Shanoir -NG database
- Copy User + Study into Shanoir-NG database
- Create Import and Dataset databases
- Apply migration scripts: sql (to create/update schemas) and python to migrate data from OLD to NG database.
- Run Spring Boot microservices, configured to 'VALIDATE'

**Comment by michaelkain** [comment]
Implemented, see qualif
