### ISSUE TITLE
Are acquisitions names in tree bad ?

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#2437]
Names are actually set by the backend :

https://github.com/fli-iam/shanoir-ng/blob/b3d798cbce60741fd49951015c3568a97e194f64/shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/ExaminationDatasetAcquisitionDecorator.java#L82

When saving segmentation datasets from the OHIF viewer, names can get a bit long : 
 
> made some measure in OHIF viewer, that create new dataset in the acquisition. The name of the acquisition node is concatenated with all datasets (here, "abcdef", "abc", "a", "aa", etc. are all datasets of modality type "measurement"):
![image](https://github.com/user-attachments/assets/8c8eadce-f355-4c3b-96c5-5d1d566843dd)

@pierrehenri-dauvergne was asking if this is really what we want

**Comment by michaelkain** [comment]
Hi, please make the names short again :-), thank you!
