### ISSUE TITLE
New tree view: order of subjects is not alphabetically anymore

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2458]
Dear Julien,
I had my meeting at Neurinfo.
The order of the subjects for VHD is not alphabetically anymore since the new interface,
what is very confusing for many users, we really need to solve this as soon as possible please.
With kind regards, Michael

**Comment by Unknolwn** [comment]
hello, do you have any news on this issue ?

**Comment by michaelkain** [comment]
Hi, yes, normally it should be fixed with tomorrow's release.

**Comment by michaelkain** [comment]
fixed
