### ISSUE TITLE
Testing: Selenium tests to verify installation is working

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#247]
see with J-C where his test suite is
- we will need this to verify 1) our installation for Neurinfo 2) the installation at the operator

**Comment by jcomedouteau** [comment]
Test suite is in shanoir-ng/shanoir-ng-tests/tests/test.py
Launch them using
`python test.py --remote -b chrome -a https://shanoir-ng-nginx -u {USERNAME} -p {PASSWORD} -s {TYPE}`
with {TYPE}: users, preclinical, entities, import, all
