### ISSUE TITLE
Exam deletion not working

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2492]
Deleting an examination is stuck:
![image](https://github.com/user-attachments/assets/05f36b77-61b0-4748-b565-f4a69e5e41eb)

![image](https://github.com/user-attachments/assets/d8257451-337a-43fe-b08a-acf75fa653ce)

Error thrown:
```
datasets           | 2024-11-08T12:46:59.001Z ERROR 1 --- [        async-3] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void org.shanoir.ng.examination.service.ExaminationServiceImpl.deleteExaminationAsync(java.lang.Long,java.lang.Long,org.shanoir.ng.shared.event.ShanoirEvent)
datasets           |
datasets           | java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "examinationUID" is null
datasets           |    at org.shanoir.ng.dicom.web.StudyInstanceUIDHandler.extractExaminationId(StudyInstanceUIDHandler.java:220)
datasets           |    at org.shanoir.ng.dataset.security.DatasetSecurityService.hasRightOnExamination(DatasetSecurityService.java:1104)
```

**Comment by michaelkain** [comment]
Hi, your bug is here:
public interface ExaminationService {

	/**
	 * Delete an examination.
	 * 
	 * @param id examination id.
	 * @throws EntityNotFoundException
	 * @throws ShanoirException 
	 */
	@PreAuthorize("hasRole('ADMIN') or (hasRole('EXPERT') and @datasetSecurityService.hasRightOnExamination(#id, 'CAN_ADMINISTRATE'))")
	void deleteById(Long id, ShanoirEvent event) throws ShanoirException, SolrServerException, IOException, RestServiceException;

	@PreAuthorize("hasRole('ADMIN') or (hasRole('EXPERT') and @datasetSecurityService.hasRightOnExamination(#id, 'CAN_ADMINISTRATE'))")
	void deleteExaminationAsync(Long examinationId, Long studyId, ShanoirEvent event);

**Comment by michaelkain** [comment]
you use #id instead of #examinationId, what injects an empty string and calls another sec method, that is used by dicomweb only

**Comment by michaelkain** [comment]
in deleteExaminationAsync
