### ISSUE TITLE
Remove center from a study

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2520]
Open a study with multiple centers
Edit study
Remove a center
Update study

In qualif and prod: green message is displayed saying the study was correctly updated but the removed center is still here

![image](https://github.com/user-attachments/assets/ea9feffe-f29a-40cf-a730-a9de8111b414)

![image](https://github.com/user-attachments/assets/fa3bc5cc-ddf2-47a4-962d-132cb8e33258)

![image](https://github.com/user-attachments/assets/830d13c0-05d1-4d06-aeb0-c10b52e4f19c)

**Comment by pierrehenri-dauvergne** [comment]
This might be fixed with https://github.com/fli-iam/shanoir-ng/pull/2522

**Comment by julien-louis** [comment]
will be fixed by https://github.com/fli-iam/shanoir-ng/pull/2525
