### ISSUE TITLE
Silent fail when importing data - dataset creation step

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#259]
When importing DICOM, you can go to "import now" button and click on it without an error.
Datasets microservice may fail, you'll still have the message stating "datasets were successfully created [...]".

![image.png](https://images.zenhubusercontent.com/5d95fbff4e1ec400011c4fee/13b2053a-9a66-4cb9-aca6-e7b0466d3e95)

-> Datasets microservice failed because "MBSENSE" was not  defined in ParallelAcquisitionTechnique.java but the user had no clue (no datasets were actually created)

At least the user should have a message in case of failure saying the the import is a fail and that he should inform the support

**Comment by michaelkain** [comment]
Hi Jean-Come, I can close this issue, as I think with your async message notification, the user now has a notification if an error has been raised? I guess this is on your branch appning already?

**Comment by jcomedouteau** [comment]
Yes it is.
