### ISSUE TITLE
SU-NG: Centers are not correctly loaded

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#261]
In Shanoir-Uploader, centers in a study are mapped:
```
	@JsonProperty("studyCenterList")
	private List<Center> centers;
```
But in Shanoir-NG
```
	/** Relations between the investigators, the centers and the studies. */
	@NotEmpty
	@OneToMany(mappedBy = "study", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private List<StudyCenter> studyCenterList;
```

In the HTTP response we have:
```
   { 
      "id":1,
      "name":"NATIVE Divers",
      "studyCenterList":[ 
         { 
            "id":1,
            "center":{ 
               "id":1,
               "name":"CHU Rennes"
            },
            "study":{ 
               "id":1,
               "name":"NATIVE Divers"
            }
         }
      ]
   },
```
That can't be mapped directly, so the list of center in a study is a list of "null" elements.
See ShanoirUploaderServiceClientNG.findStudiesWithStudyCards.

=> Make a specific deserializer ? (example following)
```
public class CustomCarDeserializer extends StdDeserializer<Car> {
     
    public CustomCarDeserializer() {
        this(null);
    }
 
    public CustomCarDeserializer(Class<?> vc) {
        super(vc);
    }
 
    @Override
    public Car deserialize(JsonParser parser, DeserializationContext deserializer) {
        Car car = new Car();
        ObjectCodec codec = parser.getCodec();
        JsonNode node = codec.readTree(parser);
         
        // try catch block
        JsonNode colorNode = node.get("color");
        String color = colorNode.asText();
        car.setColor(color);
        return car;
    }
}
```
Or change model to add StudyCenter and depreciate Shanoir-neurinfo's one.

**Comment by michaelkain** [comment]
Hi Jean-Come, for ShUp and the auto-import or import in general for the moment (and for longer later, I guess) it is not relevant, that the list of centers is correctly mapped. In my pull request I fixed the ClassCastException and now on using sh-ng with uploader it remains only the introduction for SEF. So I propose to close this issue as not relevant for the moment.

**Comment by michaelkain** [comment]
The center of the newly created exams comes from the studycard, so no need for studies centers during the import.

**Comment by jcomedouteau** [comment]
OK for me to close the issue.
Jean-Côme
