### ISSUE TITLE
For coil, acquisitionEquipmentModel dropdownlist display

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#27]
For coil, pass an acquistionEquipment object instead of a manufacturer model object for the acquisitionEquipmentModel dropdownlist and reuse the acquistion-equipment-pipe for the display.
The pipe could be used in the view, creation and edit mode.

**Comment by Nunien** [comment]
I don't understand, Coil.java has a ManufacturerModel as a dependency, not an acquisition equipment.

* I corrected the view
* I corrected the display in acquisition equipment details & edit
