### ISSUE TITLE
[feature] how to separate datasets that one user can_see and can_download in solr result table 

### ISSUE THREAD

**Issue by ychiat35** [fli-iam/shanoir-ng#274]
In sh-ng, we separated the rights can_see and can_download for one user. According to the user's token, the backend of solr api could return us either a list of datasets that the user can_see, or a list of a datasets that the user can_download. How to display the difference between these two lists then in the solr result table? Could the table component grey out the lines can_see but not can_download, so that when we check multiple datasets to be downloaded, only the can_download datasets could be selected? @Nunien What's your opinion about the table component? Does it sound possible to implement? I have already discussed about it with MK and JC. It does not matter before the deployment since today can_see and can_download rights are put together. However, I noted it as feature since users could be disturbed during massive download after the deployment.

**Comment by Nunien** [comment]
I see. I can do something about it quick. Do you confirm that the front will get the rights into each solr row? like : 
```
[
     { 
        datasetId: 12,
        canDownload: true,
        ...
     },
    ....
]
```

**Comment by yyao1231** [comment]
@Nunien Yes I can add "canDownload" into each solr document but just in the front-end.
Thanks a lot if you could commit something, but take your time:)

**Comment by michaelkain** [comment]
Closed as old.
