### ISSUE TITLE
Nifti conversion: merge doNotSeparateDatasetsInSeries et convertAs4D properties

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#282]
In shanoir neurinfo, we had 2 different properties doNotSeparateDatasetsInSeries and convertAs4D to identify series which will be created as 4D volume instead of 3D. They are not exactly the same but they should be. I just changed it on shanoir-old. For ng, as discussed with Elise this morning, we would better keep just one property since they are the same. During the nii conversion, 4D dicom should also be converted into 4D nifti.

**Comment by yyao1231** [comment]
last conf in sh-old for both doNotSeparateDatasetsInSeries and convertAs4D properties:
doNotSeparateDatasetsInSeries=SeriesDescription==*ASL*;SeriesDescription==*asl*;ProtocolName==*ASL*;SeriesDescription==*VIBE*DYN*;SeriesDescription==*MoCoSeries*;SeriesDescription==*DIFF*;SeriesDescription==*Diff*;SeriesDescription==*diff*;SeriesDescription==*DTI*;SeriesDescription==*DWI*;SeriesDescription==*PERF*;SeriesDescription==*Perf*;SeriesDescription==*perf*;SeriesDescription==*BOLD*;SeriesDescription==*Bold*;SeriesDescription==*bold*;SeriesDescription==*intermediate t-Map*;ProtocolName==*DYN*;ProtocolName==*Dyn*;ProtocolName==*dyn*;SeriesDescription==*QSM*;SeriesDescription==*qsm*;ProtocolName==*QSM*;ProtocolName==*qsm*;SeriesDescription==*RELAXO*;SeriesDescription==*Relaxo*;ProtocolName==*RELAXO*;ProtocolName==*Relaxo*;SeriesDescription==*IRMf*;ProtocolName==*IRMf*;SeriesDescription==*irmf*;ProtocolName==*irmf*;
TODO: merge these 2 properties into 1

**Comment by yyao1231** [comment]
add _**SeriesDescription==*IRMF*;ProtocolName==*IRMF*;**_ as asked today by Elise

**Comment by michaelkain** [comment]
Hi Jean-Come, could you fusion this in your nifti converter work?

**Comment by jcomedouteau** [comment]
@michaelkain  I'm on it.

**Comment by yyao1231** [comment]
I just saw your commit @jcomedouteau 
It's good to add IRMF to the lists but what I noted for this issue is that, doNotSeparateDatasetsInSeries et convertAs4D properties should also be merged into only one property, that's say, "4DSerie" for example. That's why I reopen the ticket:)

**Comment by jcomedouteau** [comment]
Ok ! I don't really know how to test it... :-/

**Comment by yyao1231** [comment]
Jean-Côme, yes, please keep them the same, like this: 

> **new4DPropertyName**=SeriesDescription==ASL;SeriesDescription==asl;ProtocolName==ASL;SeriesDescription==VIBEDYN*;SeriesDescription==MoCoSeries;SeriesDescription==DIFF;SeriesDescription==Diff;SeriesDescription==diff;SeriesDescription==DTI;SeriesDescription==DWI;SeriesDescription==PERF;SeriesDescription==Perf;SeriesDescription==perf;SeriesDescription==BOLD;SeriesDescription==Bold;SeriesDescription==bold;SeriesDescription==intermediate t-Map;ProtocolName==DYN;ProtocolName==Dyn;ProtocolName==dyn;SeriesDescription==QSM;SeriesDescription==qsm;ProtocolName==QSM;ProtocolName==qsm;SeriesDescription==RELAXO;SeriesDescription==Relaxo;ProtocolName==RELAXO;ProtocolName==Relaxo;SeriesDescription==IRMf;ProtocolName==IRMf;SeriesDescription==irmf;ProtocolName==irmf;SeriesDescription==IRMF;ProtocolName==IRMF;

To test it, I don't have un zip for the moment. But Elise tested this config on Neurinfo so it should normally work.. Just don't forget to change them when they are called in the MS import or Datasets code.

**Comment by jcomedouteau** [comment]
This was done in nifti converters PR.
