### ISSUE TITLE
Import: StudyCard selection mandatory

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#296]
Hi Julien, I have been thinking again on the selection of a studycard in the (web GUI) import.
I think, we should keep it **mandatory**, for multiple reasons: 1) when we want to propose BIDS people must complete the studycard 2) in ShUp it is mandatory and I do not have the time to change this for v1.0 3) NIfTI converter selection is attached to studycard, what is a good thing and I do not want to change this. We could think of a faster creation of an empty studycard with the selection of a nifti converter, that people can complete later. Depending on the study and the data, the converter may vary and that is why it is good to have a studycard at least for this. 4) it is a key feature from sh-ng in comparison to other more "unstructured" tools, we should promote this. 5) If we find a way in the future to help with the study card edition/creation we will have them anyway.

**Comment by michaelkain** [comment]
Hi Julien, could you please remove the selection of the nifti converter from the import GUI, as this will be done via StudyCard? Thank you!

**Comment by Nunien** [comment]
Done in pr https://github.com/fli-iam/shanoir-ng/pull/305

**Comment by michaelkain** [comment]
solved
