### ISSUE TITLE
ShUp: download from Shanoir server: when using studyId, download turns long time and then stops

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#311]
I am having quite a few data on my machine, nothing in comparison with prod. When I start the download only on using a studyId, the download progress window appears and runs about 5-10 minutes and then throws an error and nothing happens after. In the logs:
ERROR [org.shanoir.uploader.service.rest.ShanoirUploaderServiceClientNG] [341] Could not get dataset of study 1 (status code: 406, message: unknown status code)
Maybe something to exchange on with Jean-Come. This issue does not have the highest priority for the v1.0. I am happy when people can download with the web GUI.

**Comment by jcomedouteau** [comment]
Is this still failing ?

**Comment by michaelkain** [comment]
we use shanoir-downloader now
