### ISSUE TITLE
Filter non preclinical examinations on exam list

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#314]
I can't keep the filtering line on that code : 
```
    getPage(pageable: Pageable): Promise<Page<Examination>> {
        return this.examinationService.getPage(pageable).then(function(page) {
                // Filter only preclinical exams
                page.content = page.content.filter(exam => !exam.preclinical);
                return page;
            });
    }
```

You can't remove elements from a page like that. The user has aked for a page of 20 elements, we cannot give him a page of 18 elements because 2 preclinical have been filtered. Not only that, the paging display system works with page object "metadata". It contains the number of elements in the page, the total number of elements in the table, etc. Here the total elements number will be X but actually the user can see only X-nbPreclinical.

The only solution if to filter in the backend, maybe using the pageable object which is made for that.

**Comment by jcomedouteau** [comment]
I think the method in the back is ready to be used. Do we keep this for later or am I doing it right now ?
