### ISSUE TITLE
User rights: user - type User - can not import data

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#318]
- new user created, type User (these are typcially the users, that actually import data)
- this user added into one study with the rights to import into this study
- log in with this user, the Import menu is not displayed, therefore use can not import

**Comment by michaelkain** [comment]
Dear Arthur, could you please start to fix this? I joined Julien, as he is the expert for rights. I think this is more a minor frontend issue than a real bug in the rights, I guess.

**Comment by michaelkain** [comment]
I confirm: when I use the URL /shanoir-ng/imports/upload, I can start an import for the study

**Comment by Nunien** [comment]
I think it will be solved in my studycards PR

**Comment by michaelkain** [comment]
solved, tested by me
