### ISSUE TITLE
Import: create new exam -> selections before lost

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#334]
Import from DICOM zip (and others probably): clinical context:
Study + StudyCard selected, new subject created, create new exam
coming back to clinical context: --> pre-selected items lost:
- e.g. selected TestStudyCard lost and StudyCard1 selected instead
- selected subject lost, and had to selecte subject again
- and after the exam (freshly created) has to be re-selected again

**Comment by Nunien** [comment]
I did not manage to reproduce the bug : 
* In clinical context I select StudyCard2 (StudyCard1 was preselected)
* I select subject2
* I create an examination
* When saving exam and going back, studycard, subject and examination are rightfully selected

Maybe you should show me the bug at the daily

**Comment by jcomedouteau** [comment]
I could reproduce it, I think you have to create a new subject before creating a new exam. :)

**Comment by michaelkain** [comment]
retested, fixed by Julien
