### ISSUE TITLE
StudyCard/UI fix => Missing menus

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#339]
- No Solr search menu
- Tasks update live is missing ( notifications.component.*)
- Dataset Acquisition menu is existing, but does not seems quite plugged (=> no results)

@Nunien I can do it if you want ;)

**Comment by Nunien** [comment]
@jcomedouteau I'm on it. By the way DatasetAcquisition pages work for me. You must have imported data to get datasetAcquisitions.
