### ISSUE TITLE
qualif issues with dataset_acquisition/acquisition_equipement

### ISSUE THREAD

**Issue by a-ba** [fli-iam/shanoir-ng#340]
on the qualif server:

- the page https://shanoir-qualif.irisa.fr/shanoir-ng/dataset-acquisition/list freezes because the XHR to https://shanoir-qualif.irisa.fr/shanoir-ng/datasets/datasetacquisition never replies (in background it generates a *lot* of traffic with the mysql database)

- unable to start an import : the form fails because https://shanoir-qualif.irisa.fr/shanoir-ng/studies/acquisitionequipments returns 404

**Comment by Nunien** [comment]
* The timetout will hopefully be fixed with #346 
* I don't knwo why, but the problem with acquisitionequipments is that there are no equipments in the db. I created one and it works.

**Comment by michaelkain** [comment]
Fixed
