### ISSUE TITLE
acquisition equipments: MR label missing

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#349]
There are no acquisition equipments in qualif after the migration

**Comment by michaelkain** [comment]
Thanks to Anthony the acquisition equipements are back, but there are some issues:
1. Numbers do not match: Neurinfo-Prod: **223** equipements (user admin), Neurinfo-Qualif: **155**.
For Neurinfo-Prod, I verified the data in sh-old and in sh-ng databases: both are 223.
2. The data, e.g. of the equipement -1- do not match:
<img width="348" alt="Bildschirmfoto 2020-06-24 um 09 11 21" src="https://user-images.githubusercontent.com/4560288/85513276-21666980-b5fb-11ea-9b9e-601d57c77f21.png">
<img width="488" alt="Bildschirmfoto 2020-06-24 um 09 10 18" src="https://user-images.githubusercontent.com/4560288/85513447-4fe44480-b5fb-11ea-993a-898330446724.png">

**Comment by michaelkain** [comment]
Fixed
