### ISSUE TITLE
Qualif : study cards list as USER bug

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#350]
On shanoir qualif as USER, page study cards list

code: 500
details: null
message: "Parameter value element [null] did not match expected type [java.lang.Long (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value element [null] did not match expected type [java.lang.Long (n/a)]"

**Comment by michaelkain** [comment]
Hi, not sure, if this is an important issue for the moment.

**Comment by michaelkain** [comment]
I saw my one study card available on qualif, so I close
