### ISSUE TITLE
Admin: click on index to Solr leads to an error

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#354]
Hi, on shanoir-qualif, when I click with the an admin rights user on index-to-solr I have an error (uncaught promise).

**Comment by jcomedouteau** [comment]
When I clicked on the button, the data is well re-idexed.
Maybe it's due to the fact that the request is too long? We should then manage this asynchronously and juste display an event stating when the indexing is over.

**Comment by michaelkain** [comment]
Have you tested on qualif?
Error from server at http://qualif-solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 404 Not Found</title>\n</head>\n<body><h2>HTTP ERROR 404</h2>\n<p>Problem accessing /solr/shanoir/update. Reason:\n<pre> Not Found</pre></p>\n</body>\n</html>\n; nested exception is org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://qualif-solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 404 Not Found</title>\n</head>\n<body><h2>HTTP ERROR 404</h2>\n<p>Problem accessing /solr/shanoir/update. Reason:\n<pre> Not Found</pre></p>\n</body>\n</html>\n"

**Comment by michaelkain** [comment]
Hi Anthony, is there maybe a name resolution problem too?

**Comment by michaelkain** [comment]
fixed by Anthony, PR accepted, to be tested after next deploy
