### ISSUE TITLE
Changes for import of multi-patients, multi-studies, series of multi-equipments

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#37]
For the moment, we do a check before the import, to be sure that in the zip file, this is only one patient, one study, one equipment; if not we display a message and stop the import.

For the futur, we should consider how to do the import of multiple things.
To clean code "this.patient.studies[0].series[0].equipment" of "fetchStudies" methode of clinical-context.component

**Comment by michaelkain** [comment]
I will close this issue, as I consider that the web interface import will remain with a single-patient-single-exam, BUT we will have to develop this feature from the command line using ShUp.
