### ISSUE TITLE
Import from dicom zip: clinical context: create new exam and click on "view/eye" icon, next to exam: empty page

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#384]
Qualif, with Firefox
User type: User
Import from dicom zip: sample.zip
Clinical context:
- DemoStudy_Public
- DemoStudyCard
- Create new subject
- Create new exam
- Click on "view/eye" icon, next to "new created" exam
Error, see screenshot:
<img width="1033" alt="Bildschirmfoto 2020-07-09 um 08 47 04" src="https://user-images.githubusercontent.com/4560288/87006611-4218ec80-c1c1-11ea-9730-d2663080ec5e.png">

**Comment by michaelkain** [comment]
for "new created" subject it works

**Comment by michaelkain** [comment]
This applies for all examinations, at least when opened with user type User

**Comment by Nunien** [comment]
I committed a fix directly on develop

**Comment by michaelkain** [comment]
tested, and works now
