### ISSUE TITLE
New search: imports done: introduce delta-feeds into search index

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#386]
Hi Jean-Come,
this is important to solve for v1.0.
When an import creates new datasets, we will have to feed them into Solr, that users can search them.
Normally, that is what I call Delta-Feeds in Solr to add the missing gap.
The same will apply for dataset deletion.

**Comment by jcomedouteau** [comment]
As this is blocking, I'll treat these solr problem first.
