### ISSUE TITLE
Qualif: EEG import: dataset creation+file download successful, but JS error thrown and The data is loading never finishes

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#387]
Qualif, Firefox
- user type: User, user mkain
- testEDF.zip
- DemoStudy_Public
- Import successful, datasets created
- Click on one dataset: error displayed, but download possible
- Data is loading never finishes
<img width="926" alt="Bildschirmfoto 2020-07-09 um 10 33 10" src="https://user-images.githubusercontent.com/4560288/87016909-9b881800-c1cf-11ea-9abe-9efb507b84cf.png">

**Comment by jcomedouteau** [comment]
I'm on it
