### ISSUE TITLE
Import from dicom zip: without dicomdir

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#388]
The idea is to upload a zip file, that contains only dicom files, or subdirectories with subdirectories with dicom files and to generate a dicomdir, and use this dicomdir in select series, that the user can see what the generated dicomdir looks like.
This will simplify the imports for users, that are today generating dicomdirs on their side before.

**Comment by jcomedouteau** [comment]
I'm on it.

**Comment by michaelkain** [comment]
Hi Jean-Come, might it be that you forgot the warning message in the GUI?
 Important notice : this archive must contain a DICOMDIR file at its root!

**Comment by michaelkain** [comment]
Hi JC, please add an explanation text: if dicomdir is present, it is used, if not we generate one using the dicom files.
BTW do all dicoms have to be on the root of the zip file, or can it be in sub-folders too. This should be explained too for the users.

**Comment by michaelkain** [comment]
Fixed and working
