### ISSUE TITLE
Adapt selenium tests to the new UI

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#397]
Selenium tests needs to be adapted to the new UI.

**Comment by jcomedouteau** [comment]
This issue is now dependent of the resolution of other issues.

**Comment by michaelkain** [comment]
I think we should step away to automate the GUI tests and test as much on the REST level automatically, to e.g. assure that imports work, and keep the GUI testing to our manual 1-2h sessions, as the effort is not in relation to the output from my point of view.
