### ISSUE TITLE
Qualif: values of dataset acquisitions are not displayed

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#409]
- user type: admin
![Bildschirmfoto 2020-07-30 um 10 21 25](https://user-images.githubusercontent.com/4560288/88899622-90645d00-d24e-11ea-91a1-35748168861d.png)

**Comment by michaelkain** [comment]
Hi Jean-Come, could you have a look on that?

**Comment by jcomedouteau** [comment]
Yep !
