### ISSUE TITLE
Acquisition equipment: Undefined

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#412]
![Bildschirmfoto 2020-07-30 um 15 30 40](https://user-images.githubusercontent.com/4560288/88928982-c7039d00-d279-11ea-9456-ac5a16563b23.png)

**Comment by jcomedouteau** [comment]
I'm on it !

**Comment by michaelkain** [comment]
Fixed, successfully tested on qualif

**Comment by michaelkain** [comment]
Hi Julien, your fix did not work.
![Bildschirmfoto 2020-09-24 um 09 11 34](https://user-images.githubusercontent.com/4560288/94112621-00095980-fe46-11ea-8e6c-bc889667f473.png)
