### ISSUE TITLE
Qualif: create new exam: study not preselected

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#424]
![Bildschirmfoto 2020-08-04 um 10 21 55](https://user-images.githubusercontent.com/4560288/89271048-7a82dd80-d63c-11ea-8383-157f9c86bc3a.png)

**Comment by jcomedouteau** [comment]
It's probably linked to the refactoring Julien has done to merge preclinical/clinical import => I'm on it with the subject list selection too.

**Comment by michaelkain** [comment]
Fixed, successfully tested on qualif
