### ISSUE TITLE
admin@shanoir.fr referenced on the wiki (Contribution-Workflow) failing

### ISSUE THREAD

**Issue by dmargery** [fli-iam/shanoir-ng#434]
https://github.com/fli-iam/shanoir-ng/wiki/Contribution-Workflow says committers can be reached at admin@shanoir.fr, but he address bounces:

> The following message to <admin@shanoir.fr> was undeliverable.
> The reason for the problem:
> 5.1.0 - Unknown address error 550-'5.1.1 <admin@shanoir.fr>: Recipient address rejected: User unknown in virtual mailbox table'
> 
> 
> Reporting-MTA: dns; mail3-relais-sop.national.inria.fr
> 
> Final-Recipient: rfc822;admin@shanoir.fr
> Action: failed
> Status: 5.0.0 (permanent failure)
> Remote-MTA: dns; [217.70.178.1]
> Diagnostic-Code: smtp; 5.1.0 - Unknown address error 550-'5.1.1 <admin@shanoir.fr>: Recipient address rejected: User unknown in virtual mailbox table' (delivery attempts: 0)
>

**Comment by Nunien** [comment]
I removed that address and put each person's inria address instead.
