### ISSUE TITLE
Small error messages within empty tables, with new users having no studies assigned

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#444]
- create a new user with admin and the web GUI, with user type User (as most of our users)
- change PW and login with this user
- user has access to no study, so his tables are all empty, BUT
there are a lot of errors displayed, instead of empty tables:
- Manage examinations
- Manage dataset acquistions
- Datasets
- StudyCards
- Preclinical all entities
- same for Solr search

It can take some time to add an user to a study, when the account is accepted.
All these errors give the impression, that something is not well implemented.

**Comment by Nunien** [comment]
@michaelkain 
* I couldn't reproduce any problem with the preclinical lists
* The problem with Solr is inherent to the Solr implementation in Shanoir I think we should fix that independently.

**Comment by jcomedouteau** [comment]
=> Should I create an issue for the solr problem ?
