### ISSUE TITLE
Keycloak: migrate to new version (e.g. 4.5.0)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#46]
For security reasons it is always positive to migrate to new version (normally).
To fix the GitHub Issue #42 an adapter has already been upgraded to a new version (4.5.0).
To harmonize it would be good to migrate the container to a new version of Keycloak and
the same for the Spring Boot libraries. Attention: it could happen that this task involves as
well the migration to Spring Boot 2.

**Comment by yyao1231** [comment]
done in pull request #131
