### ISSUE TITLE
Massive download: multiple datasets, download is possible if right on one dataset

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#489]
is this correct for security reasons

**Comment by jcomedouteau** [comment]
@michaelkain see my comment on the PR, I think it's OK

**Comment by jcomedouteau** [comment]
I tested it on shanoir-ng-dev, with a user that could download only from one study.
Whe I downloaded from 2 studies with solr search, I only got the datasets from the study it had the rights on.
