### ISSUE TITLE
StudyCards: re-apply study card rules on already imported and existing data

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#491]
Hi Julien, this is maybe more a question than a feature request, maybe. We introduced the idea of ORIGIN and UPDATED metadata into Shanoir-NG, in the idea, that we keep the original meta data from the dicoms in the db in ORIGIN and that we store and display the "computed" values in updatedMetadata. My question now is, how I can apply a studycard on a study and on the data of ?one machine? if I want to re-apply the new and better study card on the already present "old" metadata in the database? Have we implemented this, and if not, what would be necessary to provide this feature? We will put this on the roadmap to discuss the roadmap with the stakeholders. Cheers, Michael

**Comment by michaelkain** [comment]
This may be interesting too, to automatically construct a complete BIDS tree from existing and interesting data in Shanoir to know the RefMrDatasetNature field to name the nifti files in BIDS tree.

**Comment by jcomedouteau** [comment]
This would solve #1085 too. But this is not for now @Nunien am I wrong ?

**Comment by michaelkain** [comment]
Implemented.
