### ISSUE TITLE
Solr Search -> An unexpected error occured

### ISSUE THREAD

**Issue by pmaurel35** [fli-iam/shanoir-ng#500]
Hello,

I don't know what is "Solr Search" and what it is supposed to do but : when I click on it I have "An unexpected error occured"
<img width="1606" alt="SolRSearch" src="https://user-images.githubusercontent.com/17726410/93344298-ccb94000-f831-11ea-9557-8d399fc8c6e0.png">
on Mac with chrome

**Comment by michaelkain** [comment]
Hi Pierre, this worked already. We will check, maybe related to changes on the file system access on the qualif environment.

**Comment by michaelkain** [comment]
Hi Anthony, might this be related to the changes on the user rights? Solr worked when I tested on Monday.

**Comment by michaelkain** [comment]
2020-09-16 15:36:01.098 ERROR 1 --- [http-nio-9904-exec-8] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 

org.springframework.data.solr.UncategorizedSolrException: Error from server at http://qualif-solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/shanoir/select. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
; nested exception is org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://qualif-solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/shanoir/select. Reason:
<pre>    Not Found</pre></p>
</body>
</html>

**Comment by michaelkain** [comment]
Hi Anthony, I think there is a problem with the core "Shanoir" creation?

**Comment by a-ba** [comment]
The changes in 49ed285b1717d2 were not well replicated on the server.

It is fixed now, but the « An unexpected error » still occurs.

**Comment by michaelkain** [comment]
Hi Anthony, what is wired, as far as I know the search works on Jean-Comes and my dev machine.

**Comment by michaelkain** [comment]
Hi Anthony, maybe it is related: in your bootstrap.sh script on develop branch you do not start Solr, it is missing? It is strange, as the search worked already on qualif, and now not anymore. Do you use other codebases than we have?

**Comment by michaelkain** [comment]
Hi Anthony, Jean-Come confirms, that it works on our machines. I did a docker volume prune to clean up everything, and used your bootstrap.sh script (with Solr missing), than I started Solr using docker-compose and could test the PR of Jean-Come completely with Solr operational. Please let us know if we can be of further help. Thank you and cheers, Michael

**Comment by Nunien** [comment]
After hitting "index solr" on qualif, Solr works fine as well as nifti & dcm dowloads.
