### ISSUE TITLE
dcm2nii conversion failure

### ISSUE THREAD

**Issue by a-ba** [fli-iam/shanoir-ng#511]
The nifti conversion in the import container fails because the image is not user-agnostic.

Dcm2nii attempts to write a config file in the home dir (which is `/` in the image, therefore only writable by root)
```
DEBUG : dcm2nii 31 March 2008++ by Chris Rorden
DEBUG : An unhandled exception occurred at $0808CAF0 :
DEBUG : EFCreateError : Unable to create file "//.dcm2nii_2008-03-31/dcm2nii_2008-03-31.ini"
```

possible solution: set `HOME="/tmp/"` in the image

**Comment by michaelkain** [comment]
Hi Jean-Come, please try to fix this at first. Thank you, Michael

**Comment by jcomedouteau** [comment]
I've seen it, I'm on it !

That would be cool if we could have Anthony's configuration to be able to reproduce the bug.

**Comment by michaelkain** [comment]
Hi, I agree, it is difficult to fix bugs, that are not part of our repository or happening in code we do not have access to.

**Comment by jcomedouteau** [comment]
I think I'll do what Anthony said. It seems to be working locally.

**Comment by a-ba** [comment]
Actually, the mkdirs were a better solution. Changing HOME to `/tmp` is not ideal because `/tmp` needs to be mounted as an external volume, which would make the dcm2nii ini files leak outside de container.

I pushed #517, which keeps the HOME at `/` and makes the dcm2nii config dirs world writable (and fix their names).
