### ISSUE TITLE
Solr search: display process icon while download ongoing

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#512]
- User type: any
- Open Solr Search and select a dataset or more for download
- Nothing happens after click on nii or dcm button
Solution proposal:
- show something to the user, that his download is ongoing
- or at least grey the buttons as JC has implemented it in dataset details

**Comment by jcomedouteau** [comment]
@Nunien has developped a feature with the rolling gear when the back is working.
Closing this.
