### ISSUE TITLE
Error while opening dataset: 339961

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#516]
Error while opening dataset: https://shanoir-qualif.irisa.fr/shanoir-ng/dataset/details/339961

Caused by: javax.persistence.EntityNotFoundException:
Unable to find org.shanoir.ng.dataset.model.DatasetMetadata with id 333540 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:144)

**Comment by jcomedouteau** [comment]
This dataset does not exists anymore. Closing the issue then.
