### ISSUE TITLE
Prod: clinical assessments are not displayed

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#524]
Hi, this worked already. Maybe it has to do with the changes on exams, that removed the attached files too?
Open exam: 2869 in prod: clinical scores are not displayed, compare with sh-old.

**Comment by jcomedouteau** [comment]
I can correct this in the other PR if you want.

**Comment by michaelkain** [comment]
Thank you, good idea, so we test it onces, and it would be a shame to not display it after all our both work :-)

**Comment by michaelkain** [comment]
Successfully tested on qualif
