### ISSUE TITLE
Prod: provide access to processed datasets

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#525]
to investigate, see subject Aaaaaa in **Test

**Comment by Nunien** [comment]
@michaelkain I cannot investigate anything for the moment since I have a 503 from the prod server.

**Comment by jcomedouteau** [comment]
Me too !

**Comment by Nunien** [comment]
@michaelkain Ok, I could see that the DTO does not transfer the processing + processed datasets. 
So, we would like to see the processed dataset, can you confirm that is the issue ?
