### ISSUE TITLE
Prod: import: clinical context: create new subject (already anonymised)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#530]
Pour l'import d'examen déjà anonymisés (create new subject and check already anonymised), pouvez vous prendre le nom de patient et le mettre automatiquement dans COMMON NAME ou le laisser affiché (le nom qu'on a donné pour déidentifié est dans le champ nom prénom et disparait quand on clique sur anonymized data)

**Comment by michaelkain** [comment]
![Bildschirmfoto 2020-09-28 um 09 05 23](https://user-images.githubusercontent.com/4560288/94400697-d44de280-0169-11eb-8fb6-629599a0a7a9.png)
@Nunien I guess we should display the patientName here from the dicoms

**Comment by Nunien** [comment]
Just a remark : The common name line has recently been moved from a place to another and it has caused a bug, at least with phantom. I have just fixed it th the pr : https://github.com/fli-iam/shanoir-ng/pull/552

**Comment by michaelkain** [comment]
FIXED, deployed on 08.10.2020
