### ISSUE TITLE
Prod: new search Solr: dataset download

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#531]
Regarding SOLR, checking again this morning EMISEP was is the list of studies of the 5 results shown here, but I would then like to filter on subjects, and visits (examinations) and the subjects should only be those from EMISEP then. If I check other subject name, not in the study, I get an error message (an unexpected error occured, see screenshot). 
And, as reported yesterday if the study I am looking for is not in the first 5 answers nor in the following one clicking on the +, how can I find it (typing it in the research field does not work, as reported yesterday).

**Comment by jcomedouteau** [comment]
I'm on it, I'll try to reproduce this correctly.

**Comment by michaelkain** [comment]
@ebannier2018 Hi Elise, an update of the search has been deploayed. Can I close this issue? By the way Jean-Come still works on optimising the new search. Cheers, Michi

**Comment by michaelkain** [comment]
FIXED, deployed on the 15.10.2020
