### ISSUE TITLE
Import/display of datasets: keep initial acquisition order

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#534]
In the former manage research studies menus the series used to show in the order of acquisition. Accessing it through the studies menu is fine but the series show in a random order there. It is important to keep the acquisition order to more easily identify the sequences and what went wrong (dataset repeat).

**Comment by ebannier2018** [comment]
The list of sequences it still not in the acquisition order and this is very confusing for the users. The issue was closed but the problem is still there.

**Comment by jcomedouteau** [comment]
Not solved!

**Comment by Nunien** [comment]
@jcomedouteau is the metioned pr (#683) is supposed to fix the issue? It's not clear. If not I will work on it.

**Comment by ebannier2018** [comment]
Hi, 
I do not see the link between issue 534 and 683. Do you need some input from my side there? 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by Nunien** [comment]
@ebannier2018 not for the moment, thank you Elise. By the way I had a few questions for you on Discord but it's not urgent.

**Comment by jcomedouteau** [comment]
@Nunien yes I think it resolves it but I'm not sure it's perfect, you may check it.
@ebannier2018  the link julien wrote is falsy, he is speaking of https://github.com/fli-iam/shanoir-ng/pull/683
(pull request number 683 and not issue number 683 !)

**Comment by Nunien** [comment]
@jcomedouteau which dataset acquisition list needs to be ordered exactly?  @michaelkain talks about "studies menu" but your pr is only changing the solr page front controller.

**Comment by Nunien** [comment]
@michaelkain You talk about "the order of acquisition" but is it about the date of the examination (datasets and acquisition have no date, only the examination) or about the ids of the acquisitions?

**Comment by jcomedouteau** [comment]
> @jcomedouteau which dataset acquisition list needs to be ordered exactly? @michaelkain talks about "studies menu" but your pr is only changing the solr page front controller.

My bad, I missed something wen linking issues !
https://github.com/fli-iam/shanoir-ng/pull/695

**Comment by Nunien** [comment]
@michaelkain nevermind I'have just found out about the sortingIndex property

**Comment by ebannier2018** [comment]
Here I meant in Study detail >> Subject tree >> Examination >> 
The sequences should be displayed by 
Acquisition order (Time of Acquisition), and the reconstructed images for one series just after the series itself. 
I believe this is the SeriesNumber (0020, 0011) for the native acquisition and another field to identify for the DICOM datasets with the same Series Number that are derived from this native acquisition (reconstruction in other orientation,  _ADC, or other),  
Elise

**Comment by jcomedouteau** [comment]
Solved too (the production had a regression on the 10th of February but it should come back on the 17th)
