### ISSUE TITLE
Study details: tree: download directly from the tree

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#535]
Via this manage research studies menu we had the habit of downloading the series one by one, thereby renaming and arranging them in our local hierarchy by placing the mouse over the plus symbol and selecting dicom or nifti. Is this functionality gone? I know many users sticked to that instead of going to the dataset menu because they could more easily select the datasets they were interested in.

**Comment by jcomedouteau** [comment]
Resolved by @Nunien with the new implementation of trees
