### ISSUE TITLE
Preclinical examinations: should we see human exams?

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#536]
Going through the preclinical menu : all the examinations from human data show up in preclinical examinations.

**Comment by jcomedouteau** [comment]
That's weird, I'm on it

**Comment by jcomedouteau** [comment]
Locally and on shanoir-ng-dev, we correctly have the separation between preclinical and clinical. I feel that it may be a side effect of the data migration (?) I would need to have a check on the data here. (it is also the case on qualif).
It may be linked to https://www.baeldung.com/hibernate-notnull-vs-nullable and the fact that the column may already exist and is initially nullable.
In that case, the solution would be to set 'preclinical' to false for all examinations.
