### ISSUE TITLE
Can't find data imported with previous Shanoir version

### ISSUE THREAD

**Issue by hgarcia86** [fli-iam/shanoir-ng#537]
I can still find these data (.pdf and .zip files) in shanoir-old.irisa.fr attached to the corresponding subjects, but not in NG.

**Comment by michaelkain** [comment]
Hi Hector, thx for your message. I think you imported these data as extra data to an exam, we already have the fix and will bring it to production this week. Sorry for the issue, cheers, Michael

**Comment by michaelkain** [comment]
see issue #508

**Comment by michaelkain** [comment]
tested and fixed in qualif

**Comment by michaelkain** [comment]
deployed in prod on 05.10.2020
