### ISSUE TITLE
SOLR : unexpected error

### ISSUE THREAD

**Issue by icorouge** [fli-iam/shanoir-ng#538]
Please see screen capture attached :
OS : mac os Mojave 10.14.6
Browser : firefox 80.0

I tried a simple search in SOLR to retrieve the study called IMANES. After several trials with the application returning "unexpected error", it displays the IMANES study.
Then I can not reorder according to Name, ID, ... --> unexpected error
And also the info on the left do not. I expected that once IMANES is on, the the Syubject name on the list shows the IMANES subjects.

**Comment by michaelkain** [comment]
Hi Isabelle, yes, there is a problem with the studyName:xxx filter, that is not well implemented. We will work on this. Please use this as intermediary solution, it should work: The small + symbol allows you to skip through the study and to REALLY select one study, then the download should work.
<img width="398" alt="Bildschirmfoto 2020-09-28 um 16 37 41" src="https://user-images.githubusercontent.com/4560288/94446553-13e7ef00-01a9-11eb-8ab4-4f87af067e4f.png">

**Comment by michaelkain** [comment]
thx for the screenshot, I removed it as it exposes a lot of internal data

**Comment by michaelkain** [comment]
somehow linked with Prod: new search Solr: dataset download #531

**Comment by jcomedouteau** [comment]
Hello @icorouge,
Could you try again the search you did to get this error ? 
We want to see if it has been resolved by our changes or not.
Thanks !

**Comment by michaelkain** [comment]
FIXED, deployed on 14.10.2020

**Comment by icorouge** [comment]
Hi,
This bug is still not resolved. Please see screenshot.
Thank you,
Isabelle.
![Capture d’écran 2020-12-10 à 11 27 17](https://user-images.githubusercontent.com/8049026/101760632-69127c00-3adb-11eb-95f8-529630788ea0.png)

**Comment by jcomedouteau** [comment]
Bonjour,
Il est nécessaire de mettre un ; à la fin de la requête et d'utiliser studyName (sans majuscule).
studyName:HED-O-SHIFT;

Cette utilisation de la barre de recherche n'est pas du tout intuitive, nous sommes en cours de remodelage.
Jean-Côme

**Comment by yyao1231** [comment]
Hi Isabelle!
Je confirme ce que dit Jean-Côme. La syntaxe de requête déployée actuellement est celle qui a été définie en mars:
```
Query syntax example: studyName:test;subjectName:xxxx;datasetName:*restingstate*; 
Multiple character wildcard searches are allowed by adding * to keyword
```
On va travailler dessus pour déployer une barre de recherche beaucoup plus user-friendly, promis:)

Yao

**Comment by icorouge** [comment]
Merci mais j'obtiens la même erreur avec le ';' (copier-coller du message de Jean-Côme). J'ai retesté après avoir vidé mon historique et le cache (voir capture jointe)
![Capture d’écran 2020-12-10 à 12 08 59](https://user-images.githubusercontent.com/8049026/101764945-f1dfe680-3ae0-11eb-84a3-d1870dfe6967.png)

**Comment by yyao1231** [comment]
Je pense que c'est lié aux caractères spéciaux.. En attendant une nouvelle barre de recherche, essaye avec "**studyName:HED*;**" 
![image](https://user-images.githubusercontent.com/12045953/101765743-0bcdf900-3ae2-11eb-96be-4e96f171de64.png)

**Comment by icorouge** [comment]
Ah ça marche !!!!
Merci :)
