### ISSUE TITLE
Prod: import from pacs: use exam date to sort request answer after Pacs query

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#540]
I meant when importing data from PACS : the result of the request sorts the examination without the dates. If they are several examinations the date helps to identify which one is which.

**Comment by michaelkain** [comment]
Result of analysis:
1) the Dicom study date (-> Exam in Shanoir) is not correctly interpreted and displayed in the GUI
2) the Dicom study date is not used to list the Dicom studies by date
@ebannier2018: would you prefer to order chronologically (2009,12,19...) or the newest exam on top?
![Bildschirmfoto 2020-10-01 um 10 29 45](https://user-images.githubusercontent.com/4560288/94786657-889d7200-03d1-11eb-8657-6b26493939b7.png)
![Bildschirmfoto 2020-10-01 um 10 29 20](https://user-images.githubusercontent.com/4560288/94786683-90f5ad00-03d1-11eb-9183-6a46b1b65a19.png)
![Bildschirmfoto 2020-10-01 um 10 28 54](https://user-images.githubusercontent.com/4560288/94786686-918e4380-03d1-11eb-9b17-d13677187fdc.png)

**Comment by ebannier2018** [comment]
Newest exam on top would be better but the explicit date at the examination or dataset level ideal as used to be in shanoir-old. You can try with the following requests :

Import from PACS : Patient Name : PHANTOM QUALITE 20200925 in Shanoir-NG
returns examination with PHANTOM or QUALITE or 20200925 but we want "PHANTOM QUALITE 20200925" as implemented in Shanoir old : 
For comparison : Import from PACS : Patient Name : PHANTOM QUALITE 20200925 in Shanoir-old 

And the date filter does not help (same answer as without date)


Import from PACS : Patient Name : PHANTOM QUALITE 20200925 + date 20200925 in Shanoir-NG

<img width="1680" alt="ShanoirNG_ImportFromPACS_PHANTOM QUALITE 20200925" src="https://user-images.githubusercontent.com/36895591/94793734-3d885c80-03db-11eb-8df3-c255e4b953ed.png">

<img width="1680" alt="ShanoirOld_ImportFromPACS_PHANTOM QUALITE 20200925" src="https://user-images.githubusercontent.com/36895591/94793726-395c3f00-03db-11eb-95aa-7f6e341fa81e.png">

**Comment by michaelkain** [comment]
I fixed it in the code. @ebannier2018 I let you know as soon as we have the fix on qualif, that you could have a look.

**Comment by michaelkain** [comment]
my implementation requires the usage of the study date in the dedicated study date field

**Comment by ebannier2018** [comment]
That's ok for me. Thanks a lot! 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by michaelkain** [comment]
@ebannier2018 Hi Elise, it went in prod on Monday. Can I close the issue?

**Comment by michaelkain** [comment]
FIXED, deployed on 12.10.2020
