### ISSUE TITLE
Missing dataset metadata in ShanoirTK API access

### ISSUE THREAD

**Issue by albangaignard** [fli-iam/shanoir-ng#542]
Metadata such as "slice thickness" or "slice spacing" used to be acessible through the JSON produced by the Shanoir API. These metadata disappeared on shanoir-old.irisa.fr . 

They are very useful to filter datasets to be further anaylsed (vessel segmentation).

**Comment by michaelkain** [comment]
Hi Alban, your required slice thickness and slice spacing is already part of /datasets/datasetacquisition REST-API, see my screenshot. Hope this helps. Let me know if I can close the issue.
![Bildschirmfoto 2020-10-07 um 09 27 01](https://user-images.githubusercontent.com/4560288/95300461-7a42d080-087f-11eb-97d7-d30379fef760.png)

**Comment by albangaignard** [comment]
Thanks, they were in the dataset API in the previous ShanoirTK version. I'm still missing a reference to the dataset ID so that the raw image can be downloaded. 

Thanks for your help.
