### ISSUE TITLE
404 not found when testing shanoir REST API

### ISSUE THREAD

**Issue by albangaignard** [fli-iam/shanoir-ng#543]
Based on the URLs descibed in https://shanoir.irisa.fr/shanoir-ng/datasets/swagger-ui.html, 

 curl -X GET --header 'Accept: text/html' 'https://shanoir.irisa.fr/datasetacquisition' leads to a 404 not found error.

**Comment by michaelkain** [comment]
Hi, you will have to use https://shanoir.irisa.fr/datasets/datasetacquisition

**Comment by michaelkain** [comment]
Hi Alban, does it work and can I close the issue?

**Comment by albangaignard** [comment]
Thanks Michael, I can now get access to slice thickness metadata. However I can't find a reference to a dataset ID so that  I can download a dataset based on a query on a datasetacquisition object. 

Any idea ?

**Comment by Nunien** [comment]
datasets/examinations/subject/1/study/1 

gives you a list of examinations for subject id=1 and study id=1
inside it you will find datasets acquisitions

That's what is used for the tree in the study page

**Comment by michaelkain** [comment]
Hi Alban, did it work and can I close the issue?

**Comment by albangaignard** [comment]
Thanks Michael, Julien, I can browse the dataset IDs associated to a subject.
