### ISSUE TITLE
Already imported extra data not visible

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#546]
Hi, 
I understand the import extra data is not deployed yet but will come soon. However, we noticed (Hector first) that the extra data imported in the past was not there, for example in the IMANES study. 
![Screenshot_BrowseThroughViaStudies](https://user-images.githubusercontent.com/36895591/94574293-3f371080-0273-11eb-943e-152b01fed1e0.png)
Also when clicking on the examination itself to see if the extra data was there, the list of datasets does not appear : 
![Screenshot_DetailsExamination](https://user-images.githubusercontent.com/36895591/94574300-41996a80-0273-11eb-817e-a2af43e17b43.png)
Elise
PS : Could you tell us when the extra data import will be available?

**Comment by michaelkain** [comment]
Hi Elise, this is the third issue now for the same topic. We are aware of the problem and work on it. If you want you can see our last state on shanoir-qualif.irisa.fr. I just finished my tests: the download of existing extra data is not working yet, I will have to see with Anthony today on which side we will have to solve this. The import of new extra data is working on qualif. I will discuss this with Anthony too today and we try to deploy this hopefully this week.

**Comment by michaelkain** [comment]
but thx for your test infos, I used it for my tests to have an example

**Comment by michaelkain** [comment]
I currently put our focus on the extra data

**Comment by ebannier2018** [comment]
What was new to me in that issue is that the already imported extra data was not visible. 
The previous issue was that we could not import new extra data. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by michaelkain** [comment]
Hector already created that issue: #537

**Comment by michaelkain** [comment]
:-), but I agree his issue is not very explicit

**Comment by michaelkain** [comment]
tested and fixed in qualif
