### ISSUE TITLE
dataset acquisition menu 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#549]
Hi, 
To me the list of information given in the dataset acquisition menu is not very relevant (equipement, study, study card. Actually, I think we do not need this dataset acquisition menu.

**Comment by Nunien** [comment]
@ebannier2018  Maybe we should only display it for admins ?
Or do you think it could be relevant with other informations ?

**Comment by ebannier2018** [comment]
I never used this dataset acquisition menu myself. No idea whether some other users find it useful. I do not. 
I use the examination menu in case of wrong import, and the dataset acquisition I used to search and download datasets.

**Comment by jcomedouteau** [comment]
We'll keep it for the moment, to keep the structure clear for users (keep it logical with study tree)
