### ISSUE TITLE
download all datasets in a study 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#550]
<img width="1680" alt="Capture d’écran 2020-09-30 à 16 51 07 (2)" src="https://user-images.githubusercontent.com/36895591/94703278-f8165180-033e-11eb-9021-145a6ad19de9.png">

Hi, I was very happy to discover the download datasets icon in the medical data > studies menu but unfortunately got an error message when trying to download the files.

**Comment by michaelkain** [comment]
Hi Jean-Come, I guess the rights rule is miss-configured. As this will be limited to 50 datasets download at the moment to avoid that the server takes to hard, we have to think of how to size this feature and to propose it to which type of user.
We had the idea to prepare multiple 5Gb packages with datasets and propose a download via the task menu, when the data preparation is finished. In any case we will have to take a small example study and test this, as we collect a lot of data at once.

**Comment by michaelkain** [comment]
for the moment, I propose to not display the button until we have a solution that really allows that?

**Comment by Nunien** [comment]
@ebannier2018 : 

I think the error is not related to the download but still is very important to fix, thank you.

Did the downloading fail or did it success ?

**Comment by drh-git** [comment]
i had the same problem -- i got "access denied" whether i tried to download 20 datasets or even a single dataset.  michaelkain's proposed 5GB chunking solution would be fine for me.  my username is dhaynor.

**Comment by ebannier2018** [comment]
the download failed (see error message in red on the screenshot)

**Comment by jcomedouteau** [comment]
The right check was deficient, I created a pull request to correct this.
For the 5Gb chunk, we will discuss this, for the moment solr search should be used.

**Comment by ebannier2018** [comment]
Just a quick comment : unless fixed since last week, SOLR search is not working properly for our usage (filtering on subjects in a study with so many potential studies). We need to download several datasets at a time or successively/quickly, this only works in Shanoir old via the Manage Research studies or the dataset menu (allowing search in Shanoir old). 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
