### ISSUE TITLE
checkboxes in dataset menu

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#551]
What are the checkboxes for on the left in the dataset menu? Only action I found is to view the details of a dataset by clicking on the eye icon. Checking the checkbox does not allow any additional action. We used to be able to download datasets from there but this can be done differently now.

**Comment by michaelkain** [comment]
as we have to bring Solr Search to perfection, I guess we can remove these checkboxes? we should group some smaller GUI optimisation like this one to one task, after the fixes of the more urgent issues

**Comment by Nunien** [comment]
I propose to create a task "design and ergonomics for Solr search" and assign myself on it.

**Comment by Nunien** [comment]
Oh, I understand the issue now. I don't know which commit it is but I removed those checkboxes a few days ago. It will be on prod soon.

**Comment by jcomedouteau** [comment]
Resolved by @Nunien
