### ISSUE TITLE
DICOM download

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#557]
I downloaded the same DICOM datasets twice in a row the folder name is a random set of numbers 
- as mentionned per email it would be better to name the folder with the series description (could not find the issue here on git, sorry if it was already there)
- in the meanwhile as an early patch, if downloading it twice the folder should have the same name

**Comment by michaelkain** [comment]
@jcomedouteau I think the download here comes from the dataset details, where we have not changed the naming of the file for the download (remains random id), as done for the other download ways. I think we have to align it here with the other download e.g. via the search. Maybe use the datasetId as file name or something other? and I agree with Elise she already expressed her requirements on GitHub, maybe in a already closed issue: to investigate. Thank you!

**Comment by ebannier2018** [comment]
Yes the download came from the dataset details...only way I currently manage to download data...dataset by dataset. Will the SOLR search issue be improved in the upcoming deploy? 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by icorouge** [comment]
Also on the naming of dowloaded data :
For instance I just dowloaded this one : HOS-2017-126_T1 3D MPRAGE_2_25.nii
I guess the "2" at the end of the name is the series number (dicom field 0020,0011) ? 
What is the "25" ?

Plus : when downloading datasets  250645 to 250649 they all got the same downloaded names. In the old Shanoir, this type of series ('M0' files) was suffixed by a letter : none for the first one, A for the second one, B for the third one, ... It makes it much easier to find your way around.

Plus : when downloading multiple lots of data, it is not convenient that all of them are automatically called Datasets.zip. I do not know if adding the date+hour would be a nice/quick solution ? other ideas ?

Thank you,
Isabelle.

**Comment by icorouge** [comment]
Another point : is it useful to have one file per directory ? rather than all downloaded files in ONE directory ? 
As for me, my preference goes to the second option but all users may not agree.

**Comment by jcomedouteau** [comment]
Alors pour information au niveau du nom de sujet
NomSujet_SeriesDescription_SeriesNumberInProtocol_SeriesNumberInSequence.nii

For the second question, it is done to be able two datasets with the same name.

I'm on it for the single dataset name !

**Comment by ebannier2018** [comment]
Bonjour, 
A la réunion de Mars on avait demandé les informations suivantes dans le nom du nifti : 

    * Name should contain subject name, series number (Isabelle requirement, allows to identify repeated sequences), and visit number if any (M0, M6) to allow massive download. 

    * Currently via 3 ways to access to nifti files: 

    * manage my research studies : NomSujet_SeriesDescription_SeriesNumberInProtocol_SeriesNumberInSequence.nii : 1RO100 ND 183_T2FLAIRAXIALs006a001.nii 

    * Dataset : 

    * Single file : just like via manage my research studies eg : 1RO100 ND 183_T2FLAIRAXIALs006a001.nii 

    * Several files : Selection.tar selection2937655924978595908.tar containing .zip files named Nifti-single-file.1RO100_ND_183.T2_FLAIR_AXIAL.id121826.dcm2nii_2008-03-31.zip containing 1RO100 ND 183_T2FLAIRAXIALs006a001.nii --> Poupées russes à simplifier, mettre des nii.gz plutôt que des zip. --> I did not see this in your spec. Can this be implemented? 
    * 
Le pad est encore accessible : 
[ https://pad.inria.fr/p/np_vWkknyyJ0kQTm7i6 | https://pad.inria.fr/p/np_vWkknyyJ0kQTm7i6 ] 

Il avait aussi été question de nii.gz si possible plutôt que zip ou nii (on réduit le volume à 1/3). 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by ebannier2018** [comment]
More info to dcm2niix file naming here : https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md
Could we have a short brainstorming on what we want for Shanoir ? 
Testing on a FLAIR dataset
I would go for dcm2niix -f %n_%p_%s_%c%t%u -a y -z o 
to have the date and time at least if the visit is not possible
that is if we cant gz file (choose optimal mode or other?)
Can you try with the datasets you are interested in Isabelle ? 
JC can you tell us how dcm2nii_2014 was used in Shanoir-old ?

**Comment by jcomedouteau** [comment]
For dcm2nii:
// no anonymization (already done)
-a n
// no date in fileName
-d n
// output nii single file
-n y
// no id in the filename
-i n
// no event name in the output file name
-e y
// procol name in the output file name
-p y
// no gzip compression
-g n
// no file source name in destination file name
-f n
// no reorientation no croping
-x n
// no reorientation
-r n
SI 4D
// create 4D volumes
-4 y

for dcm2niix
//BIDS sidecar
-b y
// ignore derived and 2D images
-i n
// text notes includes private patient details
-t n
// merge 2D slices from same series regardless of study time, echo, coil, orientation, etc.
-m n
// Philips precise float (not display) scaling
-p n
// single file mode, do not convert other images in folder
-s n
// no gzip compression
-z n
// no reorientation no croping
-x n

For the nii.gz it's a topic we have to discuss and try with @michaelkain, we'll see if it's truly worth, but it could really be interesting!

For file naming, we override the naming with our own definition before download, but maybe we should not ?

**Comment by jcomedouteau** [comment]
The nifti download name has been changed, and we keep for the moment the "one folder by dataset", because some niftis used to have the same name.
This may evolve with https://github.com/fli-iam/shanoir-ng/issues/690, let's discuss about this on it eventually.

**Comment by ebannier2018** [comment]
HI, I am reopening this issue since it initially targeted the DICOM file naming and we moved to nifti file naming . Could you also modify the DICOM folder naming when downloading multiple datasets or just one ? 

Besides, I could not test the nifti download the same way since I got an error message (see screenshot) telling me : you can't download more than 50 datasets, with only 34 selected, and also did not work selecting only one nifti dataset : the previously selected datasets remain selected as written on the screenshot. 
![Capture d’écran 2021-05-28 à 11 36 47](https://user-images.githubusercontent.com/36895591/119964128-266d2f00-bfa9-11eb-9b7a-4212573ddbf3.png)
![Capture d’écran 2021-05-28 à 11 36 44](https://user-images.githubusercontent.com/36895591/119964143-2a00b600-bfa9-11eb-861f-9704e4235120.png)
Maybe we can discuss this in a short visio if you want a demo, 
Elise
.
