### ISSUE TITLE
Dicomifier not working

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#563]
Dicomifier seems not to work, for burker upload and dicomifier conversion to nifti.

Probably linked to 
https://github.com/fli-iam/shanoir-ng/issues/486 ?

@michaelkain Can you check that:
- dicomifier is (not) running => preclinical_bruker2dicom
- The docker-compose file is in adequation with the one on develop  (see my comment to change preclinical_bruker2dicom execution path on https://github.com/fli-iam/shanoir-ng/issues/486 )

Thanks

**Comment by jcomedouteau** [comment]
I actually could reproduce it localy:

preclinical                 |   at org.shanoir.ng.preclinical.bruker.BrukerApiController.startBruker2Dicom(BrukerApiController.java:151)
preclinical                 |   ... 113 common frames omitted
preclinical                 | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to preclinical-bruker2dicom:5000 [preclinical-bruker2dicom/172.19.0.15] failed: Connection refused (Connection refused)

I'm on it seeing what's wrong.

**Comment by jcomedouteau** [comment]
It's linked to a problem with dicomifier.ws => It is launched on 127.0.0.1 and should be launched on 0.0.0.0 => It use to be the case  with /root/run.py but not anymore.
I'm changing the dockerhub image

**Comment by michaelkain** [comment]
I will check on qualif tomorrow

**Comment by jcomedouteau** [comment]
Still not working on the qualif.

**Comment by jcomedouteau** [comment]
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
Traceback (most recent call last):
  File "/opt/dicomifier.ws/run.py", line 12, in <module>
    use_debugger=True, use_reloader=True)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 751, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "/usr/lib/python3/dist-packages/werkzeug/debug/__init__.py", line 271, in __init__
    if self.pin is None:
  File "/usr/lib/python3/dist-packages/werkzeug/debug/__init__.py", line 281, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "/usr/lib/python3/dist-packages/werkzeug/debug/__init__.py", line 161, in get_pin_and_cookie_name
    username = getpass.getuser()
  File "/usr/lib/python3.7/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 500'

=> pwd.getpwuid()
AS anthony said, maybe we should disable the debugger

**Comment by michaelkain** [comment]
FIXED, deployed on 15.10.2020
