### ISSUE TITLE
Account "reactivation": request account in case of existing+deactivated account

### ISSUE THREAD

**Issue by rhedouin** [fli-iam/shanoir-ng#566]
Hi, 

I just want to report a bug which is now solved. I asked for an account and I tried maybe 15 times to click on the request account button but nothing seemed to happen and indeed, nobody received anything. I directly asked Elise who reactivate my account (and suggested me to report this bug). I don't know if it happened in the past

Best, 
Renad

**Comment by ebannier2018** [comment]
When an account is not active, the user can click on forgot password but no request will be sent and the user will not be warned. It would have save Renaud some time to get a notification that his login had expired and he had to request an extension (not automatic once the login is expired, you need to know the admins )
In Renaud's case, he was not clicking on forgot password but on request account : is the same thing happening (account request is blocked?) : a notification : this email is already registered could be helpful.

**Comment by michaelkain** [comment]
Hi, to be honest, it would have saved time to Renaud, if you would just have re-activated his account. I keep this as a potential optimisation, as I agree the flow is somehow wrong for this special case. And this is a special case, but to request a new acount, when the account still exists is not either the meaning to "request an account". With kind regards, Michael

**Comment by michaelkain** [comment]
FIXED, deployed in prod 15.10.2020
