### ISSUE TITLE
Data download : trouble with SOLR 

### ISSUE THREAD

**Issue by icorouge** [fli-iam/shanoir-ng#569]
Hello,
I want to download datasets (3DT1 + ASL data + M0 data) from 10 subjects of a given study.
When I go to SOLR, I can select my study and the datasets appear on the right --> good :)
Then I need to select my subjects which I do by scrolling the Subject Name on the left and clicking those I am interested in.
The trouble is that the panel on the left does not refresh --> on the right, I don't see the data set I selected (see screenshot) even after clincking the Search button.
The other problem is that the columns on the right can not be enlarged with the mouse --> since the dataset names are quite long and start with the same titles, I can't know which one is which (for instance see datasets 250645 to 250649 in the screenshot).
Thanks for your help,
Isabelle.
![Trouble_download_SOLR_20201006](https://user-images.githubusercontent.com/8049026/95221596-e37f0100-07f7-11eb-952f-b15eed541fff.png)

**Comment by jcomedouteau** [comment]
@michaelkain @Nunien J'ai l'impression qu'il y a un soucis au niveau des données, tous les sujets ont l'air d'avoir le même ID.
Le filtrage par sujet se base sur l'ID et fonctionne correctement, mais sur le screenshot l'ID de tous les sujets est le même...

@Nunien Pour la colonne, on ne pourrait pas faire en sorte que si la colonne ne permet pas d'afficher l'élément en entier, on ai une toolbox du contenu au survol ?

**Comment by icorouge** [comment]
All subjects do not have the same ID (i i understand what you mean correctly). If you browse the pages on the right, you will see the other subjects.

**Comment by jcomedouteau** [comment]
My bad, you are right !

**Comment by icorouge** [comment]
The problem is the refreshment. When you need data from only one or a few subjects you do not want to browse all the pages.

**Comment by jcomedouteau** [comment]
Ok think I got it, for solr the "-" in the subject name is parsed (I tested it directly in solr search admin interface) => full text search should be used instead of fuzzy search.
This will normally be corrected after the next deployment by https://github.com/fli-iam/shanoir-ng/pull/562/

**Comment by icorouge** [comment]
Another thing:
When I filter by Dataset Name, as soon as I have selected one dataset name (eg : t1_mprage_....) it displays all  the t1_mprage... which is nice.
BUT I can not select another dataset name, the search is done ! whereas I would like to select all my datasets of interest at once. For instance t1_mprage... AND ep2d_pcasl_...
It would be a real gain of time.
Thanks

**Comment by icorouge** [comment]
Hello,
About the naming of .nii downloaded files : it is not practicable as it is. For instance, I just downloaded 5 M0 distinct files and I get 5 directories with one .nii file per directory, each file file having the same name. It means that I have to rename each of them as they are different and put them back in one directory only to process them afterwards. Moreover, as they are named the same I don't know which is which.
Please see screenshot.
Thanks,
Isabelle.
![download_nii_names_all_the_same](https://user-images.githubusercontent.com/8049026/95315097-5a68d800-0892-11eb-9c0f-450e8f6f7287.png)

**Comment by icorouge** [comment]
Because they are different : it is 
![download_nii_names_in_SOLR](https://user-images.githubusercontent.com/8049026/95330848-6dd36d80-08a9-11eb-8540-869cd92b4c60.png)
5 different repetitions within one sequence. If you look at the SOLR page (see screenshot) you will see that they are 5 different datasets with 5 different numbers, which is lost once downloaded.

About the naming, I get the SeriesNumberInProtocol but could you tell me what is the SeriesNumberInSequence ? I had imagined that it was what I am talking about with the 5 numbers...

Once again, it is not convenient in my opinion and in my usage to have one dataset per directory.

**Comment by jcomedouteau** [comment]
I don't know if it means something for you (I'm quite lost I have to admit..) but
SeriesNumberInProtocol => metadata.sortingIndex
SeriesNumberInSequence => metadata.Rank

I'll try to check if we can get these number somewhere. As it is 'old' data, maybe the data is not well correlated with the new version..

> Once again, it is not convenient in my opinion and in my usage to have one dataset per directory.
I think we got your point, we may propose a solution (checkbox) to download all the data in the same folder, but for the moment we'll keep our way of doing it as it is more safe as we can currently have two datasets with the same name.

If you want to move all files from subfolders in a parent directory, it's not quite hard.
open a terminal in the parent directory (unzipped folder)
Linux/mac: `cp **/* .` (if you are on windows, it's quite different, you can look on google)

**Comment by michaelkain** [comment]
Hi, @icorouge + @ebannier2018: I have the impression, that each user would require his perfect solution. Could you provide us a unified definition how it should look like? by the way, please open a new issue for different topics, thank you! As like this we will never solve issues...

**Comment by michaelkain** [comment]
FIXED, deployed on the 15.10.2020
