### ISSUE TITLE
Nifti converter 

### ISSUE THREAD

**Issue by icorouge** [fli-iam/shanoir-ng#573]
Hello,
I have a question about the nifti converter:
-- how do I know which converter has been used for my data ?
-- can I choose as in Shanoir-old which one to use at the download step ?
Obviously, in the study I am working on, two different converters are used but I have no obvious intel and/or choice about this.
Thank you,
Isabelle.

**Comment by jcomedouteau** [comment]
The nifti converter used is the one in the study card. You can change it on the studycard, but not during the import anymore. We did this to keep a consistency in a study.

**Comment by ebannier2018** [comment]
In Shanoir old, the nifti converter used at import is indeed the one specified in the study card (should not change throughout the study) but as Isabelle said, we can convert the data with another converter (both nifti files will be kept, converter version should be in the file name I would say). Or we stop converting at import and only convert at data download, will require a bit more time but since Shanoir-NG is faster it may be acceptable.

**Comment by jcomedouteau** [comment]
I think we are now quite dependent of the conversion during the import... Is there a real interest to use different converters on one dataset ?

**Comment by michaelkain** [comment]
Hi, we have not yet migrated the feature to chose a converter during the moment of the download, as in sh-old: within the dataset details display (and maybe even in the datasets overview table). We could migrate this feature too, if important and used.
I think, it is a good point to have a converter by default for the study, to assure the availibility of the niftis from the beginning, e.g. have a complete BIDS tree in case of a good studycard by default. I think using the new search and selecting a converter, in case, could be cool?
If we propose this, we will create a new task, that the user does not have to wait before the screen, and display a download link in the manage tasks overview -> similar as for the imports today. All should by async for user comfort. Shanoir-NG prepares then in the backend the zip file.
@icorouge + @ebannier2018 : could you send us a short list of your most important issues, ordered by priority?

**Comment by jcomedouteau** [comment]
This is linked to #690
