### ISSUE TITLE
ShUp: certificate issue

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#582]
Hi Anthony,

the below is a serious problem with ShanoirUploader. He does not work at all, because of this. This seems to have worked last week somehow. But I tested on my machine and it does not work at all anymore.

My problem is, that for a starting study we have to start the imports as soon as possible, this week at the lastest, and I will install ShUp next week in a hospital in Paris for that reason. With kind regards, Michael

PS: I know, that I can deactivate host name verification in my code, but for security reasons I am not hot on it.

**2020-10-12 09:27:10 ERROR [org.shanoir.uploader.service.rest.HttpService] [86] hostname in certificate didn't match: <shanoir.irisa.fr> != <shanoir-2016.irisa.fr> OR <shanoir-2016.irisa.fr>**

javax.net.ssl.SSLException: hostname in certificate didn't match: <shanoir.irisa.fr> != <shanoir-2016.irisa.fr> OR <shanoir-2016.irisa.fr>
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:231)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:152)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:133)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:291)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:262)

**Comment by a-ba** [comment]
There were no changes on server-side.

The likely cause is that shanoir-uploader no longer sends the [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) extension in its TLS hanshake.

**Comment by michaelkain** [comment]
Concerning the certificate issue, I never had this issue with sh-old, and please see below a validated
stackoverflow post summary from https://stackoverflow.com/questions/25854543/how-to-enable-sni-in-http-request-using-apache-httpcomponents-httpclient, and I am using Java 8:
SNI should work completely transparently when running on Java 1.7 or newer. No configuration is required. If for whatever reason SSL handshake with SNI enabled server fails you should be able to find out why (and whether or not the SNI extension was properly employed) by turning on SSL debug logging as described here [1] and here [2]

'Debugging SSL/TLS Connections' may look outdated but it can still be useful when troubleshooting SSL related issues.

**Comment by michaelkain** [comment]
Hi, I guess, I found a solution. For whatever reason Apache HttpClient does not seem to use the same HostnameVerifier and related code as provided by JDK/JRE. I use now the Verifier within Apache HttpClient that comes from the outside JDK/JRE, and it seems to work with prod and qualif. Thx for your help, Michael

**Comment by michaelkain** [comment]
Hi, I fixed the issue in ShUp in HttpService. Now in case of prod envs, the verifier of the JDK/JRE is used, in case of dev envs a simple trust manager is used to avoid problems with self-signed certs.

**Comment by michaelkain** [comment]
I tested with prod, and with my local dev env. Both work. Good point: now with an complete new local dev env from scratch, we will not have to import the cert everytime back into cacerts to bring ShUp to run: EASY.
