### ISSUE TITLE
Unable to create a new manufacturer

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#590]
Create a new acquisition equipement as an expert
Add a new manufacturer model => First JS error

>  ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
>       formGroup's partner directive "formControlName" instead.  Example:
> 
>       
>     <div [formGroup]="myGroup">
>       <input formControlName="firstName">
>     </div>
> 
>     In your class:
> 
>     this.myGroup = new FormGroup({
>        firstName: new FormControl()
>     });
> 
>       Or, if you'd like to avoid registering this form control, indicate that it's standalone in ngModelOptions:
> 
>       Example:
> 
>       
>     <div [formGroup]="myGroup">
>        <input formControlName="firstName">
>        <input [(ngModel)]="showMoreControls" [ngModelOptions]="{standalone: true}">
>     </div>

Then add a new manufacturer => ERROR in the back. (not retrieved yet)

**Comment by jcomedouteau** [comment]
In the database, auto_increment is not set for ID column in
- manufacturer
- manufacturer_model

`ALTER TABLE manufacturer MODIFY id bigint(20) NOT NULL AUTO_INCREMENT;`

=> Do we do this directly in database @michaelkain ?

**Comment by michaelkain** [comment]
@jcomedouteau Normally the annotation in JPA creates this for the db, that is why it should work on dev env. For qualif and prod you will have to contact Anthony, that he applies your change on the qualif and on the prod. Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
Waiting for Anthony to update the DB.
