### ISSUE TITLE
Import from PACS: implement front-end in Angular

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#60]
Import from PACS:
For the import from PACS a new menu item will have to be added, see sh-old.
The menu item leads to the start of the import, where 1. Upload is replaced with
"1. Query PACS". In this screen the 5 fields below will have to be displayed. At least
one of them has to be present. Two are date fields. For input validation see the
corresponding dicom fields. A button with the content Query or a loup will have
to be used to send the query to „/importer/query_pacs“ as JSON post, see my
PR in GitHub. We search the dates with precise values, format is "20161016.
* PatientName
* PatientID
* PatientBirthDate
* StudyDescription
* StudyDate

* Check user right : can import from PACS
* Import PACS : disable papaya preview

**Comment by yyao1231** [comment]
resolved in pull request 112
