### ISSUE TITLE
BIDS export with extra "session"

### ISSUE THREAD

**Issue by cmaumet** [fli-iam/shanoir-ng#605]
Hi Shanoir-NG dev team!

It's very nice to see the BIDS export available, thanks for putting this together! 

I think there there is an extra session sub-folder that should not be present: 

<img width="385" alt="Screen Shot 2020-10-16 at 11 02 02" src="https://user-images.githubusercontent.com/5374264/96239214-b96bd280-0f9f-11eb-8800-22dc845d5ffc.png">
 
According to the [BIDS spec](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html): "Defining multiple sessions is appropriate when several identical or similar data acquisitions are planned and performed on all -or most- subjects, often in the case of some intervention between sessions (for example, training)". 

So, in most cases, the session sub-folder should be omitted. Session folders are usually only needed when we have multiple 'visits' (longitudinal studies) and in that case, the session names are common across subjects (or at least across a subset of the subjects).

**Comment by jcomedouteau** [comment]
That's an interesting point, I hadn't read this !
It actually allows us to keep the examination level/logic from Shanoir, but you are right on the fact that it's not necessary on a majority of datasets.

We cannot really know (can we?) when we are in this case: "several identical or similar data acquisitions are planned and performed on all -or most- subjects" => So when in doubt we actually apply the rule more strictly and add the session level, that's how I see it, but it's clearly open to discussion :)

**Comment by cmaumet** [comment]
Thanks for the prompt reply @jcomedouteau!

I completely understand the constraints on the development end and the idea of keeping the same logic for all studies. 

On the analysis end having the extra folder when not required, does add (a little bit) more complexity and I *think* that in most BIDS studies I have seen, the session folder is omitted as often as possible. 

But I think the main issue in the current setup is that we end up with different session names for each subject (which is not consistant with the [definition of BIDS sessions](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html) "Session - a logical grouping of neuroimaging and behavioral data **consistent across subjects**.").

Do you think that checking whether the sessions are available across subjects could help deciding whether or not we should have a session folder?

**Comment by jcomedouteau** [comment]
> But I think the main issue in the current setup is that we end up with different session names for each subject (which is not consistant with the definition of BIDS sessions "Session - a logical grouping of neuroimaging and behavioral data consistent across subjects.").

Okay, I get it now, so my implementation is clearly bad! So maybe we can adopt the other point of view: if the acquisitions are not specifically based on sessions, we don't use the session folder by default. 

> Do you think that checking whether the sessions are available across subjects could help deciding whether or not we should have a session folder?

If we can do it for every group of datasets, it could be really interesting. I don't have the technical knowledge to know where to check this (In MR datasets, but also for EEG or scans) if you can help me on this ?

**Comment by cmaumet** [comment]
> If we can do it for every group of datasets, it could be really interesting. I don't have the technical knowledge to know where to check this (In MR datasets, but also for EEG or scans) if you can help me on this ?

I am happy to help! But not sure I follow this one... Could you use the session name that was extracted earlier and check whether it's the same across subjects in a given study?

**Comment by jcomedouteau** [comment]
My question was more or less, where is stored (in DICOM or anywhere else ?) this session name ? (Where do we "extract it from ?)

**Comment by michaelkain** [comment]
Hi Jean-Come, as discussed in the daily, the dicom studyDescription is used as comment on the exam in Shanoir. I think we will have to use this value, as it is the only one we have. The importing user can modify the exam comment to unify this if desired. With best regards, Michael

**Comment by jcomedouteau** [comment]
One "simple" solution for us to implement this would be:
- If there is 1 exam for every subject, no session folder (so most of the time)
- If there are multiple exam, we add the session layer, based on the studyDescription/examination comment.

As the our Bids folder is updated at every step of the study (creation, new import, dataset deletion, etc), it seems not logic to me to check the consistency between subjects. 
If ONE inconsistency between subjects means no session folder, there will be no session folder displayed during most of the import part of the study => Is it really a pb ?

Or maybe we can display a warning stating that the session level is not consistent between subjects, and that it's up to the responsible to name the examinations appropriately to get the consistency. (And this warning will be displayed until all the data are fully loaded, which is normal)

What do you think @cmaumet ?

**Comment by cmaumet** [comment]
Discussed on meeting on Nov 2 w/ @ebannier @michaelkain @Nunien: 
 - we need to use Shanoir "comment" field rather than the session id to generate BIDS session.

 - we are unsure what to do with test data / repeat when quality is not enough.

 - we also discuss the possibility to consider timepoints in Shanoir.

**Comment by ebannier2018** [comment]
Test data is a rare use but repeat is more frequent (is the first repetition or the second repetition better, should we export both and how to label them for the data processing people to choose)

**Comment by cmaumet** [comment]
For the test data, here is a relevant thread on how to handle this in BIDS: https://neurostars.org/t/poor-quality-images-in-bids-format/1373.

**Comment by jcomedouteau** [comment]
I don't think test data adaptation will be a top priority development, let's get something that works correctly first, then we'll handle these special adjustments.
Concerning the func/anat/dwi/fmap folder => do we have a clean study card that I can take as example ? (and can you add me on the study as an observer @ebannier2018 ? thanks!)

**Comment by cmaumet** [comment]
@jcomedouteau - sounds good to me! The dataset we are looking at is TransIRMf I think it has all you need. Do you have access to this one?

**Comment by jcomedouteau** [comment]
No I don't have the access to this one ! If I remember well, the dispatch anat/func/dwi will be done according to MrSequenceApplication if I'm not wrong ? Could you help me dispatch these ?
	CALIBRATION(1),
	MORPHOMETRY(2),
	ANGIOGRAPHY(3),
	CONTRAST_AGENT_ANGIO(4),
	TIME_OF_FLIGHT_ANGIO(5),
	VELOCITY_ENCODED_ANGIO(6),
	PERFUSION(7),
	DIFFUSION(8),
	BOLD(9),
	SPECTROSCOPY(10),
	H1_SINGLE_VOXEL_SPECTROSCOPY(11),
	H1_CHEMICAL_SHIFT_IMAGING_SPECTROSCOPY(12);

**Comment by cmaumet** [comment]
> No I don't have the access to this one ! 

I don't think I can give you access but @ebannier2018 should be able to help :)

> If I remember well, the dispatch anat/func/dwi will be done according to MrSequenceApplication if I'm not wrong ? Could you help me dispatch these ?

Yes! See below:

> MORPHOMETRY(2), ==> anat
> DIFFUSION(8), , ==> diffusion
> BOLD(9), , ==> functional

The other ones are not yet represented in BIDS as far as I am aware.

**Comment by ebannier** [comment]
Just gave you access to Transirmf. 

My answers below for the dispatch. 
Not in BIDS ? comment is to be checked...maybe upcoming ? 
-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
Thanks a lot !

**Comment by jcomedouteau** [comment]
What should we use for undefined/default data ? (for people that doesn't use correctly MrSequenceApplication for example )
=> create a "datatype" generic folder
or 
=> Put all datasets in one of the possible folder (anat/func/dwi/fmap?) 

or another idea ? Do not put any folder ? (not BIDS compliant I think)

**Comment by cmaumet** [comment]
I would say ignore that data?

**Comment by ebannier** [comment]
Well if there is something coming up for ASL or EEG that is not implemented yet or people want to use BIDS and also the other datasets it can be interesting to keep them.... 
Or add it as an option when downloading? 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
I don't think everybody uses correctly the studycards yet, but they may want to be able to use bids too. If there is no better idea for the moment I'll let it as it is for the moment I think => all datasets in "anat" folder.

**Comment by cmaumet** [comment]
I'm afraid all datasets in anat will be misleading to data processors... I am still leaning towards excluding those data (and suggest updating the study card?).

**Comment by ebannier** [comment]
+ 1. I would keep them but in an undefined folder. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
This was corrected, using study card for modality folder (and no more session folder for single session).
I'm closing it.
