### ISSUE TITLE
Questions regarding Edit study 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#607]
Hi, 
2 very minor comments arising when editing a study : 
- I wanted to change the false boolean to receive import email to true but pressing enter opens the finder (see screenshot). 
- There is a possibility to download dataset even when editing a study. I would only allow this when opening the study but temporarily not when editing it (see screenshot again). 
Elise

![Capture d’écran 2020-10-16 à 14 23 51](https://user-images.githubusercontent.com/36895591/96258178-e62de300-0fbb-11eb-8907-051603d70205.png)
![Capture d’écran 2020-10-16 à 14 23 58](https://user-images.githubusercontent.com/36895591/96258189-e8903d00-0fbb-11eb-89cd-b47792b9b77b.png)

**Comment by jcomedouteau** [comment]
I'll have a look at it, thanks.
