### ISSUE TITLE
Prod: receive import notification mail

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#611]
Hi Jean-Come, SJ, that is responsible for the study UCAN told me, that she does not receive any import notification mail (the flag is true and she can administrate the study), same as AA?. May you please have a look on that? With kind regards, Michael

**Comment by jcomedouteau** [comment]
I really have no clue why it does not work => Essentially due to the fact there is a lot a silent failures and not enough logs.
Locally, messages are sent

I think the first step will be to better logging.

**Comment by michaelkain** [comment]
PR accepted, waiting for next deployment

**Comment by michaelkain** [comment]
see same issue #620
