### ISSUE TITLE
Logout: error message displayed

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#612]
Hi, with every logout an error message is displayed, it would be great to remove this as it looks weird. Users have the impression, that something went wrong. This is not giving confidence especially with login-logout scenarios.

**Comment by jcomedouteau** [comment]
I don't have this error on local, qualif, and prod @michaelkain, could you investigate a little bit more on this error you have ?

**Comment by jcomedouteau** [comment]
Not reproduced @michaelkain ?
