### ISSUE TITLE
No email notification when remote participating centers upload data

### ISSUE THREAD

**Issue by albangaignard** [fli-iam/shanoir-ng#620]
Since the last update, our colleague from Nantes CHU does not receive email notifications anymore. 
Thanks for your help, we may have missed an option / configuration in the “shanoir.irisa.fr" instance.

**Comment by jcomedouteau** [comment]
Thanks for the feedback, we are actively working on this problem ! It's not a configuration issue.

**Comment by michaelkain** [comment]
PR accepted, waiting for next deployment
