### ISSUE TITLE
Extra data import rights

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#624]
Hi, 

Can you tell me how to deal with the rights to import extra data ?  I have them but the MR techs do not and I would need them too. In Shanoir old there was a dedicated right for that for each study, even for users (no experts) : and modify the study parameters. 
![ModifyStudyParameters](https://user-images.githubusercontent.com/36895591/97194704-c1e7b880-17aa-11eb-9921-e70c63c3d170.png)
Is it limited to experts now? 

I believe people allowed to import images should also be allowed to import extra data, but this also goes with modifying rights. To that, I think modifying the subject name via the edit menu should be prevented since the DICOM data themselves are not modified when modifying the subject names in Shanoir and this can be misleading when downloading DICOM data. All other information can be modified at less risk so I would say we can grant modification rights to those performing import.

**Comment by michaelkain** [comment]
Hi Elise, I tested with my account (user type: User) and I could use the import to add extra data to a newly created exam (related to right can_import in study), but I agree, I could not add extra data to an existing exam. It behaves as specified with you: https://github.com/fli-iam/shanoir-ng/wiki/Roles-and-rights-specification, the edition of an exam is only possible for admin user (at least what the spec says). to summarise: you would prefer, that edit exam is related to can_import into study, in case of adding extra data after the original data import, right?

I will open another issue for your second question.

**Comment by ebannier2018** [comment]
Hi, 

Thanks for checking in. 

I would prefer the addition of extra data to be linked to import rights, but not the edit exam rights (at list as long as edit rights allow to change the subject name and other information we do not want to be modified because the DICOM data itself is not modified adequately) 

If this cannot be changed easily : 
- 1. we teach the users to import extra data at import and not afterwards. Not sure it will be sufficient. 
or 
- 2. you can link it temporarily to edit exam but keeping in mind to improve that later / allow attaching extra data without giving edition rights or review the edition rights 
I would go for solution 2 for now. 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by michaelkain** [comment]
Hi Elise, thx for your good proposal. I will have to discuss this with Julien and Jean-Come.

**Comment by ebannier2018** [comment]
Hi, 
Thanks for answering. How can we give a user the right to edit a study right now? Could not find it...in the meanwhile the MR techs cannot import Extra data / only my account allows to do so. 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by ebannier2018** [comment]
Hi there, 
Has this bug been solved....can you update us on the status ? 
Elise

**Comment by ebannier2018** [comment]
Just tested with the MR techs and still cannot access the edit button to import extra data. They do it with my account in the meanwhile and this is not a good option.

**Comment by jcomedouteau** [comment]
@ebannier2018 Currently a user/expert can edit an examination if he has the right to import on the study, so he can upload extra-data (just tested it on prod)
At the moment, you cannot update directly for examination list but only from examination detail.
Jean-Côme

**Comment by ebannier2018** [comment]
Hi Jean Come, can we have a short discussion on this, I tested yesterday with the Mr Techs and did not succeed. 
https://meet.jit.si/Shanoir 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
