### ISSUE TITLE
Modification of examination date at import should not be possible

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#625]
I can see that it is possible to modify the examination date **at import** and I think this should not be allowed since the date is already in the DICOM files automatically. There is no reason it should be wrong and we should not allow changing it. 
![ModifyExaminationDate](https://user-images.githubusercontent.com/36895591/97195798-0758b580-17ac-11eb-9681-57baec2e4421.png)

**Comment by michaelkain** [comment]
fixed by Jean-Come in the code, waiting for next deploy to be tested by @ebannier2018
