### ISSUE TITLE
Failed import - no details 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#640]
Hi, 
I performed 2 imports in a row today and did not see any error message but it seems the second one (3/11) went wrong : 
- if I did not check I would not know
- I do not know why it went wrong nor to which of the two imports this apply (what is the number in brackets?)
![FailedImport](https://user-images.githubusercontent.com/36895591/97992369-e19e6280-1de2-11eb-8194-d38b4b855379.png)
Can you check
Elise

**Comment by ebannier2018** [comment]
> Hi,
> I performed 2 imports in a row today and did not see any error message but it seems the second one (3/11) went wrong :
> 
> * if I did not check I would not know
> * I do not know why it went wrong nor to which of the two imports this apply (what is the number in brackets?)
>   ![FailedImport](https://user-images.githubusercontent.com/36895591/97992369-e19e6280-1de2-11eb-8194-d38b4b855379.png)
>   Can you check
>   Elise

**Comment by jcomedouteau** [comment]
For the one 03/11/2020 14:29

> 2020-11-03 14:29:43.424  INFO 1 --- [SimpleAsyncTaskExecutor-1] o.s.n.i.s.d.MrDatasetAcquisitionStrategy : Generating DatasetAcquisition for   : *fl3d1_ns - AAHead_Scout_64ch-head-coil - Rank:0
> 2020-11-03 14:29:43.441 ERROR 1 --- [SimpleAsyncTaskExecutor-1] o.s.n.i.s.d.MrDatasetAcquisitionStrategy : Unable to retrieve dicom attributes in file /tmp/4/6456581785196041200/SERIES/1.3.12.2.1107.5.2.43.166066.30000020110312232003100001842/dataset0/1.3.12.2.1107.5.2.43.166066.30000020110312232003100001841.dcm
> 2020-11-03 14:29:43.445 ERROR 1 --- [SimpleAsyncTaskExecutor-1] o.s.ng.importer.service.ImporterService  : Error during import for exam: 13276 : {}
> 2020-11-03 14:29:43.446 ERROR 1 --- [SimpleAsyncTaskExecutor-1] .s.n.d.c.DatasetAcquisitionApiController : Unexpected error during the import: null, please contact an administrator.
> 2020-11-03 14:29:43.447 ERROR 1 --- [SimpleAsyncTaskExecutor-1] o.s.ng.importer.service.ImporterService  : cleanTempFiles: /tmp/4 does not exist
> 2020-11-03 14:29:43.450  WARN 1 --- [SimpleAsyncTaskExecutor-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

The exception seems not to be logged correctly..

Code failing:
```
		try {
			// TODO ATO : should always be a dicom: add check
			dicomAttributes = dicomProcessing.getDicomObjectAttributes(serie.getFirstDatasetFileForCurrentSerie(),serie.getIsEnhancedMR());
		} catch (IOException e) {
			LOG.error("Unable to retrieve dicom attributes in file " + serie.getFirstDatasetFileForCurrentSerie().getPath(),e);
		}
```
=> the data may not be consistent ? I'll check if the import folder is still existing.

**Comment by jcomedouteau** [comment]
@ebannier2018 Could you send me the involved DICOM ? Or try to import it on the qualif so that I can access the import files to see the consistency of the files ?
Thanks !

**Comment by jcomedouteau** [comment]
@ebannier2018 can you help me ? :) (cf my older message)
