### ISSUE TITLE
[Study creation] Center selection search blocking selection

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#643]
Create a new study
Search for a center in the search bar (such as "gin")
Select the corresponding center (GIN for example)
=> In the search bar, "gin"
=> Error when creating the study linked to the center

This must be linked with the search-list @Nunien

**Comment by jcomedouteau** [comment]
I can't find what's happening, may we discuss this @Nunien

**Comment by Nunien** [comment]
@jcomedouteau Ok I'm on it
