### ISSUE TITLE
Shanoir account expiration

### ISSUE THREAD

**Issue by ecaruyer** [fli-iam/shanoir-ng#665]
The email I just received to notify the upcoming expiry of my account says:

> If you need to extend the validity of your account, request an extension on Shanoir home page.

I cannot see any such option on the Shanoir home page, either before or after logon. Is the feature implemented yet on shanoir-ng? 

PS: I actually received 2 emails, with a slightly different text, but from the same email address.

**Comment by michaelkain** [comment]
Hi Manu! Thx for your issue. We are already working on this issue, see https://github.com/fli-iam/shanoir-ng/issues/172
I will therefore close your issue, but we are on it. Thank you, Michael
