### ISSUE TITLE
Failed import - no error message 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#670]
We imported 5 examinations in Shanoir for the COMASCORESubStudy, got no error message but there is no list of sequences in the imported examinations and we did not get any error message either....we still have the data to import it again but we do not want to risk losing data if the import is not reliable. Could you please check what happened (we performed another import yesterday afternoon at 3pm ? 
Elise

**Comment by jcomedouteau** [comment]
Elise,

I found out what was the problem for these imports:
The imageOrientationPatientArray in the DICOM is null for these images. Is it normal ?

We need this field not t be null for the import (reconstructing the dicom), maybe we can put something "by default" if it's null ?

Jean-Côme

**Comment by ebannier2018** [comment]
Thanks for checking and following up. 
Are you refering to the field 0020, 0037 which is 
ImageOrientationPatient (0020,0037) 1\0\0\0\1\0
value 1
value 0
value 0
value 0
value 1
value 0
for the diffusion data in this study ?

**Comment by jcomedouteau** [comment]
Yep, this seems to be null, but I think the problem is more "profound", I'm checking this !

**Comment by jcomedouteau** [comment]
The problem seems to be linked to the specific entry:

Id | 1.3.12.2.1107.5.2.43.166066.2020100918445548724057954.0.0.0

Description | TENSEUR_64DIR_AP_ColFA
Series date | 09/10/2020
Series number | 9
Modality | MR

The import works when I import everything but this one.

**Comment by jcomedouteau** [comment]
@ebannier2018 Could you check this entry when you have some time ? It seems to be "broken" (I don't have the technical knowledge around this..)

**Comment by ebannier2018** [comment]
Peux tu faire un point de vive voix ici rapidement : [ https://meet.jit.si/Shanoir | https://meet.jit.si/Shanoir ] 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by ebannier2018** [comment]
I confirm the import of all series but the _ColFA series works fine. Issue with _ColFA remains to investigate.

**Comment by jcomedouteau** [comment]
@ebannier2018 There's definitely a problem with this serie => I cannot open it with all dicom viewers.
for image C-008-005.MR.COMASCORE.0009.0040.2020.10.29.14.41.29.979741.268707213.IMA
the tag ImageOrientationPatient seems not to be defined which causes an error on our side.

Could you check it ? Maybe it's normal for this kind of data ?

Thanks !
Jean-Côme

**Comment by ebannier2018** [comment]
I an open it and view it in Horos. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by jcomedouteau** [comment]
Yes, I managed to open it too, but could not find the ImageOrientationPatient value (which is theoretically mandatory https://dicom.innolitics.com/ciods/ct-image/image-plane/00200037)
 => Is it normal ?
=> Should we define a default value if it does not exists ?

**Comment by ebannier2018** [comment]
Hi, So we identified thanks to Jean-Côme's investigation that the issue lied in the _ColFA series. Unchecking this series and the upload works. Remains to solve : 
-why is that ? it happened also on OxyTC datasets and this is an old study where the import of the whole examination used to work. 
- an error message should be displayed when one series fails / and makes the whole import fail (right now no error message at all)

**Comment by jcomedouteau** [comment]
@ebannier2018 -why is that ?  => Because on these series  ImageOrientationPatient value is missing in DICOM.
=> Is it normal ?
=> Should we define a default value if it does not exists ?

And yes I'll be working on the error message !

Jean-Côme
