### ISSUE TITLE
Link from MyTask to study/subject/examination

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#672]
I was wondering whether it would be possible to click on the imported examination in MyTasks (when the import is done) and be redirected to the examination itself to check that all the series are there. Since Christmas is coming.....

![image](https://user-images.githubusercontent.com/36895591/100105279-7686ff80-2e67-11eb-9449-1c01ca30c4c4.png)

**Comment by jcomedouteau** [comment]
linked to  #938
