### ISSUE TITLE
Import (zip): json for startImportJob contains "service" object: to delete (if still remaining)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#68]
"service": {
          "http": {
            "handler": {
              "next": {
                "next": {
                  "xhrFactory": {}
                },
                "interceptor": {
                  "keycloakService": {
                    "gettingToken": false
                  }
                }
              },
              "interceptor": {
                "tokenService": {
                  "doc": {
                    "location": {
                      "href": "https://shanoir-ng-nginx/shanoir-ng/imports/finish",
                      "origin": "https://shanoir-ng-nginx",
                      "protocol": "https:",
                      "host": "shanoir-ng-nginx",
                      "hostname": "shanoir-ng-nginx",
                      "port": "",
                      "pathname": "/shanoir-ng/imports/finish",
                      "search": "",
                      "hash": ""
                    },
                    "__zone_symbol__keypressfalse": [
                      {
                        "type": "eventTask",
                        "state": "scheduled",
                        "source": "HTMLDocument.addEventListener:keypress",
                        "zone": "angular",
                        "runCount": 0
                      }
                    ],
                    "__zone_symbol__clickfalse": [
                      {
                        "type": "eventTask",
                        "state": "scheduled",
                        "source": "HTMLDocument.addEventListener:click",
                        "zone": "angular",
                        "runCount": 30
                      }
                    ]
                  },
                  "platform": "browser",
                  "cookieName": "XSRF-TOKEN",
                  "lastCookieString": "",
                  "lastToken": null,
                  "parseCount": 0
                },
                "headerName": "X-XSRF-TOKEN"
              }
            }
          },
          "API_URL": "https://shanoir-ng-nginx/shanoir-ng/studies/subjects"
        },

**Comment by yyao1231** [comment]
corrected in bugCorrection branch
