### ISSUE TITLE
Field comment should be displayed next to examination date

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#681]
Hi, 
In shanoir-old the field comment was displayed next to the examination date and could be used to label the examination (Visit 1, visit 2, or brain and spinal cord). In Shanoir-NG, this is not the case anymore and this is a problem, since the field used in a default field selected by the MR tech and not rigourously chosen. 
![ScreenshotCommentField](https://user-images.githubusercontent.com/36895591/100372255-44ad9e80-3009-11eb-9cdf-c0bec76db67c.png)
Can you change that asap ? 
Elise

**Comment by jcomedouteau** [comment]
Change examination.pipe.ts not to be ENCEPHALIQUE everytime (use examination comment)
