### ISSUE TITLE
Solr search improvements specification

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#684]
Let's discuss here the solr search page possible improvements.
The goal is to produce a precise ui specification.

**Comment by Nunien** [comment]
The left side search items (study, subject) could be user friendly. Maybe with the shanoir select component. But we should probably know precisely what we want to to with those facets/criteria first.

**Comment by jcomedouteau** [comment]
The second thing for me is to have a more user-friendly search bar allowing to search in all fields at the same time. (This implies changes in the back too).

**Comment by jcomedouteau** [comment]
I would add:
- filter by center
- Allow deletion from solr interface

**Comment by Nunien** [comment]
note : long study names don't display properly

**Comment by Nunien** [comment]
I'm putting this here : 
* space before the study name facet :
![image](https://user-images.githubusercontent.com/21199767/105327754-9751a400-5bcf-11eb-80c2-00151a7c1fea.png)
* space between buttons : 
![image](https://user-images.githubusercontent.com/21199767/105327934-cd8f2380-5bcf-11eb-9b6d-a200cfda36f0.png)
* Solr Search tooltips: text exceeds frame

**Comment by Nunien** [comment]
Needed bu Elise and Benoit :
* search by healthy volunteer / patient

**Comment by Nunien** [comment]
Done : https://github.com/fli-iam/shanoir-ng/wiki/Solr-User-Interface-Specification

**Comment by Nunien** [comment]
I'm closing this, new issue(s) will be created for the implementation
