### ISSUE TITLE
bug with dataset processing deserialization

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#685]
Any attempt to get a dataset processing object leads to :

```
org.hibernate.type.SerializationException: could not deserialize
Caused by: java.io.StreamCorruptedException: invalid stream header: 32303134
```
32303134 means '2014' in hexadecimal. It's actually a date stored in the database as a tinyblob which can not be deserialized as a Java Date. See the table's details : 

```
mysql@shanoir-2016 qualif-datasets> show columns from dataset_processing;
+-------------------------+--------------+------+-----+---------+----------------+
| Field                   | Type         | Null | Key | Default | Extra          |
+-------------------------+--------------+------+-----+---------+----------------+
| id                      | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| comment                 | varchar(255) | YES  |     | NULL    |                |
| dataset_processing_type | int(11)      | YES  |     | NULL    |                |
| processing_date         | tinyblob     | YES  |     | NULL    |                |
| study_id                | bigint(20)   | NO   |     | NULL    |                |
+-------------------------+--------------+------+-----+---------+----------------+

```

**Solution :** 
A script that changes the column type and converts its data from tinyblob to data.

**Comment by Nunien** [comment]
To help with the conversion : 
* Exemple of DATE type data : 2014-05-21
* Exemple of TINYBLOB type data : 2014-05-21 18:42:00

**Comment by Nunien** [comment]
actually it's because the java type is JodaTime's LocalDate. So : 
* change to java.time.LocalDate
* check if there are other JodaTime.LocalDate
* prepare a ALTER TABLE for Anthony to run at the updgrade

**Comment by Nunien** [comment]
```
alter table dataset_processing add column processing_date_new DATE after processing_date;
update dataset_processing set processing_date_new = convert(substr(processing_date, 1, 10), DATE);
```

check the new column is created an correctly filled

**Comment by yyao1231** [comment]
scripts launched on qualif db.

classes which use jodaTime:
DatasetApiController.java
BidsApiController.java
DatasetProcessing.java

**Comment by yyao1231** [comment]
bug corrected on qualif. the script above should be sent to Anthony for the futur prod deploy.

**Comment by yyao1231** [comment]
corrected on prod
