### ISSUE TITLE
[Download] Allow download of all datasets from an examination

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#688]
Allow download of all datasets of an examination
=> From exam detail
=> From study tree

**Comment by Nunien** [comment]
@jcomedouteau @michaelkain 
Is it possible that an examination contains both dicoms and eegs?
What do we do in this case?

**Comment by jcomedouteau** [comment]
I think there is quite a hole in the download dataset process concerning EEG.
At this time it is not considered at all (but for BIDS)
We should totally discuss  about this :)

**Comment by jcomedouteau** [comment]
I'm re-opening this issue after a discussion with Michel Dojat:
- When downloading all an examination, all data should be in ONE folder named after the examination
- Same with study (have many folders by exams/ subjects ?)
