### ISSUE TITLE
[Examination] Examination update (extra files) not possible for users

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#689]
On app.routing.ts, for examination update, you have to be at least expert or admin. Change this, as examination update is now protected by the 'CAN IMPORT' role on study.

**Comment by Nunien** [comment]
Is has been decided that only an admin can edit an examination, see https://github.com/fli-iam/shanoir-ng/wiki/Roles-and-rights-specification . It may be an error in the wiki though. We should discuss that in the next dsu.

**Comment by jcomedouteau** [comment]
The point of Elise was that a user that imported data (so that created the examination) can edit this examination or at least add extra data.
All the code was ready for this (based on "CAN_IMPORT" right) but for one specific line of code.
