### ISSUE TITLE
[unit tests] cross platform unit tests failures

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#705]
Here are some unit tests failures that I met while doing a build on windows 10. On linux they seem to be passed without error. I note them here to see if we could do something simple to better manage the cross platform filesystem naming.
- MS datasets: BidsServiceTest.testAddDataset:220
Error: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://C:\Users\yyao\AppData\Local\Temp\tmpTest\test.test
- MS import:  ImporterApiControllerTest.testUploadEEGZipFile:163 Response content
Expected: a string containing "/brainvision (copy)/ROBEEG_BACGU020_dlpfc_l_0002.vhdr\""
     but: was "{"workFolder":"5125108126323597836","examinationId":null,"studyId":null,"subjectId":null,"acquisitionEquipmentId":null,"datasets":[{"channels":[{"name":"Fp1","resolution":0.5,"referenceUnits":"µV","lowCutoff":0,"highCutoff":1000,"notch":0.0,"x":9.27344,"y":2.4899077,"z":2.5810034}],"events":[{"type":"New Segment","description":"","position":"1","points":1,"channelNumber":0,"date":1404723132039}],"name":"ROBEEG_BACGU020_dlpfc_l_0002","files":["C:\\tmp\\3\\5125108126323597836\\brainvision (copy)\\ROBEEG_BACGU020_dlpfc_l_0002.pos","C:\\tmp\\3\\5125108126323597836\\brainvision (copy)\\ROBEEG_BACGU020_dlpfc_l_0002.vhdr","C:\\tmp\\3\\5125108126323597836\\brainvision (copy)\\ROBEEG_BACGU020_dlpfc_l_0002.vmrk"],"samplingFrequency":1,"channelCount":1,"coordinatesSystem":"true"}],"subjectName":null,"studyName":null}"

**Comment by michaelkain** [comment]
Hi Yao, as you are the only developer with Windows, could you please solve these issues? Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
as I wrote already in my email

**Comment by yyao1231** [comment]
For cross-platform deployment problems related to bash scripts, here is explications and solutions:
https://stackoverflow.com/questions/39527571/are-shell-scripts-sensitive-to-encoding-and-line-endings

**Comment by michaelkain** [comment]
Hi Yao, thank you for the above link. As you are the only Windows developer, did you make progress with this issue? It agree with you when opening the issue, it is important that it works for Windows too. Please let me know, when you can fix it, thank you and with kind regards, Michael

**Comment by yyao1231** [comment]
I used -skipTests option to progress :) But I will work on it! By the way, as discussed with Anthony by mail, the bootstrap.sh does not work on windows. I will create another issue about the deployment script and work on that also.

**Comment by michaelkain** [comment]
Thank you, great!

**Comment by michaelkain** [comment]
Hi Yao, could you make some progress on that issue?

**Comment by yyao1231** [comment]
Hi Michi, not this one yet. I worked on other issues and pet import.

**Comment by yyao1231** [comment]
corrected on PR #788
