### ISSUE TITLE
Relaxometry 4D volumes get separated

### ISSUE THREAD

**Issue by ocommowi** [fli-iam/shanoir-ng#708]
Hi,

We had created in the old shanoir a special case for relaxometry sequences, which are 4D volumes but with different TR and TEs. I remember it was some tag called "Do not separate" in shanoir. We have a new sequence, called mc_gse, that also does relaxometry and gets separated in many 3D volumes in shanoir. Would it be possible to add this sequence in the "Do not separate" tag.

Thanks

**Comment by yyao1231** [comment]
Hi Olivier,

No pb. Actually for relaxo sequences, we have this config to keep them 4D volumes: `SeriesDescription==RELAXO;SeriesDescription==Relaxo;ProtocolName==RELAXO;ProtocolName==Relaxo;`
Could you please check the SeriesDescription and/or ProtocolName tags and tell us if the keyword to put is well "mc_gse"?

Thanks,
Yao

**Comment by ocommowi** [comment]
The series description indeed contains mc_gse. An example: 

(0008, 103e) Series Description                  LO: 'mc_gse_1p8iso_76slc_32contrasts'

Protocol name also contains mc_gse : 

(0018, 1030) Protocol Name                       LO: 'mc_gse_1p8iso_76slc_32contrasts'

**Comment by yyao1231** [comment]
Ok, thanks a lot!

**Comment by yyao1231** [comment]
merged in PR #710
