### ISSUE TITLE
Download from search results limited to 50 items

### ISSUE THREAD

**Issue by ocommowi** [fli-iam/shanoir-ng#709]
Hi,

When I try to download more than 50 items from a search result in shanoir, I get an error saying that the download of more than 50 items is forbidden. Is there a specific reason for this or could we increase this number ?

Thanks

**Comment by jcomedouteau** [comment]
Hello,
Some datasets are really "heavy", we made this choice to avoid having to download huge files (4/5b)  that slows down the server and the connection.
With Solr search (or study detail tree), you can easily search trough your datasets and download them 50 by 50.

We are currently thinking of a way to smooth the datasets download.

Jean-Côme Douteau

**Comment by michaelkain** [comment]
Benoit has expressed the same limit during our open support meeting, that he is already **limited for one patient download**. We will have to think of this.

**Comment by michaelkain** [comment]
See other issues with same idea and issue for roadmap Mass Download
