### ISSUE TITLE
[Download][Solr Search] Multiple datasets, same serie, similar names

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#722]
Hi Jean-Come, we had a very good support meeting this morning. Please find an optimisation proposed by IC.
Concerned studyId: 116, subjectName:*415*; searched
See my screenshots:
<img width="400" alt="Bildschirmfoto 2020-12-18 um 10 17 58" src="https://user-images.githubusercontent.com/4560288/102597265-ad74cc00-411a-11eb-923a-012947d5c46c.png">
Download of nifti files:
![Bildschirmfoto 2020-12-18 um 10 00 12](https://user-images.githubusercontent.com/4560288/102597470-fc226600-411a-11eb-94be-aff0d24b1a74.png)
The issue is, that all file names have the same name. _1, _2, _3, _4, _5 would be preferred by IC.

**Comment by icorouge** [comment]
Thank you michie, this is correctly reported :)
I like the solution you propose. 
Thanks for letting me know whether it is possible (otherwise we'll have to think to an alternative).
Isabelle.

**Comment by michaelkain** [comment]
Hi Isabelle, Jean-Come has solved the issue. Normally it will be deployed in production shanoir.irisa.fr next week on Wednesday, 13.01.2021. We will try to deploy once a week in 2021.
