### ISSUE TITLE
[deployment script] bootstrap.sh does not work on windows

### ISSUE THREAD

**Issue by ychiat35** [fli-iam/shanoir-ng#724]
As discussed with Anthony by mail, the deployment script bootstrap.sh does not work on docker desktop, windows os. 
The script is launched via gitbash, working for some moments and then gitbash is closed without any log.
The script needed to be debugged and then modified.

**Comment by yyao1231** [comment]
Note: For cross-platform deployment problems related to bash scripts, here is explications and solutions:
https://stackoverflow.com/questions/39527571/are-shell-scripts-sensitive-to-encoding-and-line-endings
