### ISSUE TITLE
Unit of mesure not migrated to Shanoir NG

### ISSUE THREAD

**Issue by ychiat35** [fli-iam/shanoir-ng#729]
The units of mesure are missing in Shanoir NG. It seems to me that in Shanoir old, they could be displayed and edited. Maybe only the display could be enough for Shanoir NG's use, to be discussed..

**Comment by youennmerel** [comment]
See also https://github.com/fli-iam/shanoir-ng/issues/271

**Comment by youennmerel** [comment]
I've identified the following fields that need units of measurement :
- Mr type acquisition
  - MR protocol fields
  - MR protocol metadata fields
- Pet type acquisition
  - Pet protocol fields
- Manufacturer model
  - Magnetic field
- Examination
  - Subject weight
