### ISSUE TITLE
[Datasets] filter on id not working

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#730]
On https://shanoir.irisa.fr/shanoir-ng/dataset/list page, where I enter in the filter zone "37445" to filter "id" for example, nothing is filtered indeed..

**Comment by Nunien** [comment]
The problem is that the search field should be deactivated. We cannot do filtering with backend paging for now.

[browserSearch]="false" have to be added in dataset-list.component.html
