### ISSUE TITLE
Downloading individual data not working on Safari (Mac OS)

### ISSUE THREAD

**Issue by benoit-combes** [fli-iam/shanoir-ng#734]
Dear developers,

Clicking "download as nifti" on safari (and MacOS) in
![image](https://user-images.githubusercontent.com/9528034/103756113-2dea6680-500f-11eb-8089-508514f56191.png)

Gives :
![image](https://user-images.githubusercontent.com/9528034/103756134-393d9200-500f-11eb-9f34-12d040ca6872.png)

The same procedure works with another browser (chrome in our case).

**Comment by Nunien** [comment]
@benoit-combes Thanks Benoit ! As I said this will has a low priority since for the moment we focus on Chrome and Firefox.

**Comment by michaelkain** [comment]
Hi @benoit-combes, hi @julien-louis, I am closing this issue as we focus on Firefox and Chrome. With kind regards, Michael
