### ISSUE TITLE
angular10 test : css bugs

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#741]
(some bugs might not be the consequence of the angular10 pr)

* check police

* side menu : 
    * arrows alignment
    * scroll y on side menu
    * element vertical margin ?

* checkbox : 
![image](https://user-images.githubusercontent.com/21199767/103874838-f264a080-50d1-11eb-9ec4-5d36d6610cdd.png)

* dropdown : 
![image](https://user-images.githubusercontent.com/21199767/103875417-ae25d000-50d2-11eb-9199-d53aec89abd6.png)

* slider broken on select boxes

**Comment by jcomedouteau** [comment]
![image](https://user-images.githubusercontent.com/7604176/103874413-66527900-50d1-11eb-9e85-a19ee7ea0078.png)

Space between buttons

**Comment by yyao1231** [comment]
![image](https://user-images.githubusercontent.com/12045953/103875261-7dde3180-50d2-11eb-9f4a-449c08c09713.png)

space before the study name facet

**Comment by jcomedouteau** [comment]
![image](https://user-images.githubusercontent.com/7604176/103875361-9f3f1d80-50d2-11eb-8534-671e93875da3.png)

Yes no are not aligned with checkbox (subject creation)

**Comment by yyao1231** [comment]
![image](https://user-images.githubusercontent.com/12045953/103875680-08269580-50d3-11eb-9ca5-c72e66832f16.png)

maybe same pb with the space between buttons

**Comment by yyao1231** [comment]
Solr Search tooltips: text exceeds frame
