### ISSUE TITLE
Import (all): clean up all temporary files after each import

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#75]
This is important as these temporary data consume space and contain patient identifiers.

**Comment by yyao1231** [comment]
Question: 
1. The workfolder found in importJob does not correspond to the real work folder path in /tmp. How to identify one workfolder of one import?
2. How to know that the import is done? Actually I added my methods right after createAllDatasetAcquisition, but are them async methods?

**Comment by yyao1231** [comment]
corrected in pull request #127
