### ISSUE TITLE
Datasets: Nifti download pb when nii file name contains special characters + conversion done by dicomifier

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#759]
Nifti download does not work well with dicomifier, when the series description dicom tag contains special characters. 
In fact, Dicomifier keeps special characters from series description dicom tag to nifti file name.
The same dicom is converted by dicomifier as
`1.3.46.670589.28.2.12.4.9172.4427.2.200.0.1223906269/%5BRG-WB_CTAC_2mm%5D%20Pulmo%20PET%20Body0_1.json`
but is converted by dcm2niix as `1.3.46.670589.28.2.12.4.9172.4427.2.200.0.1223906269_RADIOTHERAPI_ETUDE_X_20081013000000_62690.nii`

The nifti conversion is done by dicomifier and the nii file is well created. However, the nii files with special characters in their names could not be found to be copied. See error logs: 
`datasets | java.nio.file.NoSuchFileException: /tmp/3/5862852404255335322/SERIES/1.3.46.670589.28.2.12.4.9172.4427.2.200.0.1223906269/%5BRG-WB_CTAC_2mm%5D%20Pulmo%20PET%20Body0_1.json`
That's why the nifti download contains no available nii file.

**Comment by jcomedouteau** [comment]
I'm adding some dicomifier notes for a problem of Michel DOJAT here

Sur le patient 05 BSP
=> Import avec Archive.zip => 3 datasets qui n'ont pas de fichers .nii
=> Export des dicom avec hosirix => On import => les niftis sont là (dcm2niix too)

Avec le dicomifier, ils sont null aussi à l'import

Avec le dicomifier, patient 04 BSP, serie 401 => la série n'est pas terminée
Elle doit contenir moins d'images
Or avec le dicomifier, le nifti contient autant d'images (générées ?) et fait le même poid
(comparaison 401/501)
=> Tester le dicomifier à vide

**Comment by jcomedouteau** [comment]
There is a huge problem with dicomifier and the way:-
- it creates files (linked to the name)
- The files are furtherly treated

For the upper example, file names for series 401 and 501 are the same => the data is the same whereas IT SHOULD ABSOLUTLY NOT !

**Comment by jcomedouteau** [comment]
Files created have the same name for both series.
Spaces and special characters are not well considered in the code.

solution ? -> Give a specific name for every generated nifti file (doesn't matter as it is renamed furtherly when downloading them)

**Comment by jcomedouteau** [comment]
+ dcm2niix by default
