### ISSUE TITLE
[Challenge/Feature] Challenge users subscription

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#764]
For the next challenge, we want user to be able to subscribe and retrieve data using Shanoir.

- User subscribe using Shanoir interface
- He is automatically part of a study where the data is already loaded
-  He can download all data with one click ?
- At the end of the challenge, the study is not accessible anymore => How to do this? 

Update Study object to have a boolean value "isChallenge"
This option is only visible for admin users
=> Check on front side
=> Check on back side

If the study is a challenge, the data is accessible only between startDate and endDate

This is quite fast to do (0.5 day?)

Propose an alternate subscription button => subscribe to a challenge
Then the list of open challenges is displayed (otherwise, an error occurs stating that no challenge are currently active)
=> Select study name where isChallenge is true and endDate<now()
The subscription screen:
![image](https://user-images.githubusercontent.com/7604176/104429443-e8391b00-5585-11eb-82a9-f43628283d6c.png)

AccountRequestInfo is updated with a challenge field (ID of study or name ?)

Then, on user microservice, if the user subscribed to a challenge (check challenge field), send a rabbitMQMessage to subscribe the study MS to subscribe this user to the challenge study. (can download  data only ? => to be tested)

When the user is accepted then created, he directly has access to this study and only this one, with the data.

This is quite fast to do too (1 or 2 days maybe because of screen definition AND out of identification SQL request)

**Comment by michaelkain** [comment]
Hi Jean-Come, thank you for the issue creation. Please see my comments below:
- normally a challenge once run, remains open in a way, that others can afterwards quite easily access at least to the training data
(training data -> public/shared with all challengers to train/optimise their algos, testing data -> hidden/used at first internally to compare the algos)
- I think an account request will have to be validated in any case, but it would be great if the challenger would already be part of the challenge (isChallenge) study, that has been proposed to him in a dropdown box to choose the open challenges with the rights can_see + can_download during the account request (-> name of study to be used)
- as very often the challenges data -> niftis files are specially produced/configured ones, we should not use the standard niftis generated automatically with the dicoms during mr zip import, but maybe to discuss with Arthur we could optimise this -> @arthursw 
- either we import again the dicoms and generate perfect niftis and propose a standard sh-ng download for the challengers using e.g. your implementation with the 5Gb packages (that would be great too to have a great show case for this) OR we propose a "big file" download containing all patients available from the Shanoir "home page" (the one after standard login) (I think a big file download would be a great extension too, for the upload we could manually copy it on the server ssh access)

**Comment by michaelkain** [comment]
It is a good idea to only show OPEN/running challenges to the outside world, what you wrote above

**Comment by arthursw** [comment]
Nice description Jean Come 👍 

Yes, the nifti files will be preprocessed and not necessarily related to DICOM files. 

To me, there is no need to upload the DICOMs on Shanoir.

In this sense, the download process for challenge could be different from the normal Shanoir download process ; we just need a button to download the file(s), right?

Do we need to record whether each user has downloaded the files? And how many times? I don't think it's really useful, although it could keep help tracking user participation...

Do we need to create a study with rights for the challenge?

**Comment by ocommowi** [comment]
Following Michel comments in an email (and my email to Michael), I think it would be nice to keep ended challenges as we wish to put the data for the first MS challenge open to the world soon. And so people may still want to register and download the data for afterwards.

Another thing: it is also important I think especially for the ofsep data to use only nifti files and not import the dicoms. Is that possible ?

**Comment by michaelkain** [comment]
@arthursw  and @ocommowi we will provide a way without the dicoms, as I understand for legal reasons, that the OFSEP does not want to share the dicoms that open
And yes we will have to create a special study in sh-ng, flagged isChallenge for that. As long as we have a log file "datasets.log" and we keep the log files for a long time we trace it already, so no worries for me from that side.

**Comment by arthursw** [comment]
👍

**Comment by michaelkain** [comment]
Hi, deployed in prod, shanoir.irisa.fr yesterday, 22.02.2021, I therefore close the issue now. Thank you all and cheers, Michael
