### ISSUE TITLE
Delete subject: does dcm4che archive 5 support deletion

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#77]
1. Does dcm4che archive 5 provide (or DICOM protocol in general == DIMSE) a remote delete call? I found N-DELETE, but not sure if it is the right action to use. When we delete a subject in sh-ng we could using this call automatically delete the data in the PACS.
2. Does the web interface of da5 provide a delete button, as dcm4chee2 (used today), to delete patients? If 1. does not work to clean up afterwards with the PACS web interface?

**Comment by michaelkain** [comment]
Hi Jean-Come, no hurry on this, but we should consider to really delete the dicoms within the next release hopefully, to free the disk space, what could become an issue with the GME FLI. I was thinking to work on a dicomWeb support now of sh-ng, please let me know if you want me to continue this issue. Cheers, Michael

**Comment by jcomedouteau** [comment]
HI Michael,
No problem, I can have a look at this one.

**Comment by jcomedouteau** [comment]
Rest interface existing to delete a study:
curl -X DELETE http://localhost:8081/dcm4chee-arc/aets/DCM4CHEE/rs/studies/{studyId}

For this to work, either:
- Reject the study first (By using another API ?)
- Allow the study deletion by using dcmAllowDeleteStudyPermanently option (where to configure this ?)

**Comment by jcomedouteau** [comment]
Every time we delete a dataset, call a specific method (along with "deleteFromSolr()")
deleteData() {
- Delete nifti/EEG files
- If another dataset exists in SQL database with same Study_ID (regex) do nothing
- Else, reject then delete the Study_ID from the PACS.

In that case, deleting a simple dataset that has others datasets in the same examination won't gain space.

Reject study:
https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/RejectStudy
/aets/{aet}/rs/studies/{study}/reject/{codeValue}^{codingSchemeDesignator}
{study} -> Study Instance UID for a single Study
{codeValue} -> 113039 for EXPIRED
{codingSchemeDesignator} -> DCM for dicom

Delete study that was rejected:
https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/DeleteStudy
curl -X DELETE http://localhost:8081/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.4.9.12.34.1.8527.6035486820697358315414572131982691336993

Second solution:
1) Reject Specific serie
https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/RejectSeries

2) Delete all rejected instances
https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/deleteRejectedInstancesPermanently 

Problem: A serie can be linked to multiple datasets 

Third solution
1) Reject specific instances:
https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/rejectMatchingInstances

2) Delete all rejected instances
https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/deleteRejectedInstancesPermanently 

-> Good way to delete only a study
-> We may keep the subject/study/serie in PACS even with no instance inside.
