### ISSUE TITLE
Error with nifti downlad [emisep]

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#780]
https://shanoir.irisa.fr/shanoir-ng/dataset/details/178740

Download as Nifti : leads to an error. The backend respond an extensive error message, here is some of it : 
```
{
	"code": 422,
	"message": "Error while retrieveing dataset data.",
	...
		"file": "/var/datasets-data/old/subject_2231/examination4777/examination/dcm2nii_2008-03-31/3DFLAIRs011a001.nii",
        ...
	}
}
```
Maybe the import didn't work properly

**Comment by jcomedouteau** [comment]
That's quite weird, the nii file exists but here:
/var/datasets-data/old/subject_2231/examination4777/examination/dcm2nii_2014-08-04/

It seems that there is a confusion between dcm2nii_2008 and dcm2nii_2014-08-04 during the conversion (?)

**Comment by Nunien** [comment]
Quentin F. has listed the data he cannot download : (emisep)
08_01= M60 3DT2 impossible à chargé
08_05= M12 impossible à chargé (3DT1 Mprage/ axialT2 2è echo/ 3D flair)
08_10= M12 impossible de chargé M60 3DT2 impossible à chargé
08_12= M12 impossible à chargé (3DT1 Mprage/ axialT2 2è echo/ 3D flair) M60 impossible à chargé (3DT2)
08_16= M12 impossible à chargé (AxT2 /3D flair) M36/60 impossible à chargé (3DT2)
08_19= M36/60 impossible à chargé (3DT2)
08_21= M36/60 impossible à chargé (3DT2)
08_23= introuvable
08_24= introuvable
08_26= introuvable
08_27= introuvable
08_28= M36/60 impossible à chargé (3DT2)
08_30= M36/60 impossible à chargé (3DT2)
08_33= M36 impossible à chargé (3DT2)
08_34= M36/60 impossible à chargé (3DT2)
08_36= introuvable
08_41= M36/60 impossible à chargé (3DT2)
08_42= introuvable
08_45= M36/60 impossible à chargé (3DT2)
08_46= M36 impossible à chargé (3DT2)
08_48= M36 impossible à chargé (3DT2)
08_49= M36 impossible à chargé (3DT2)
08_50= M36 impossible à chargé (3DT2)
08_51= M36 impossible à chargé (3DT2)
08_58= M36 impossible à chargé (3DT2)
08_60= M36 impossible à chargé (3DT2)
08_62= M36 impossible à chargé (3DT2)
08_63= M36 impossible à chargé (3DT2)
08_67= M36 impossible à chargé (3DT2)
08_72= M36 impossible à chargé (3DT2)
08_73= M36 impossible à chargé (3DT2)
08_74= M36 impossible à chargé (3DT2)

**Comment by jcomedouteau** [comment]
Maybe some of them are linked to https://github.com/fli-iam/shanoir-ng/issues/778 too?

At first, we need to correct: https://github.com/fli-iam/shanoir-ng/issues/759
Then we may need to implement  https://github.com/fli-iam/shanoir-ng/issues/690 to correct this problem..

**Comment by michaelkain** [comment]
Closed as considered too old.
