### ISSUE TITLE
[Tutorial] Create a tutorial / video to help users import and share data

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#790]
The idea would be to have an example at least on how to import data on Shanoir-NG to give as an example.

**Comment by michaelkain** [comment]
Hi Jean-Come, we have an user tutorial: https://docs.google.com/document/d/1kfsYJXxm3Ts0_qxCxDIPeSdwZnvjh2qhzb9jQbpobt4/edit?ts=5f745be6#

**Comment by jcomedouteau** [comment]
Great news, thanks !
