### ISSUE TITLE
[Study Management] Study deletion: protect fast deletion

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#793]
Possibilities, given by EB
1 - specify on the button : delete study (to avoid confusion with delete selected dataset) 
2 - as you suggest a double check
3 - forbid to delete a study with existing examinations 
4 - only allow admins to delete studies ? 

I would go for solution 1+2+3+4, to be safe.

**Comment by jcomedouteau** [comment]
It seems a little bit too much for me to allow the deletion only to admin. (an expert can make a mistake)
=> If there is no examination linked to it anymore, it does not costs that much to re-create it.
=> Do not delete from list but from detail only
=> Double check is already existing

**Comment by jcomedouteau** [comment]
I'm on it

**Comment by ebannier** [comment]
I would say only the study responsible should be able to delete the study, not any expert. 
And then only if the study is empty. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
