### ISSUE TITLE
[Import] Add T2_STAR reference to AcquisitionContrast

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#794]
Unexpected error during the import: No enum constant org.shanoir.ng.datasetacquisition.model.mr.AcquisitionContrast.T2_STAR, please contact an administrator.

**Comment by jcomedouteau** [comment]
Do not merge now - wait for Elise response

**Comment by jcomedouteau** [comment]
This has to be merged, this field is set by the machine.

Following reference it should be T2_STAR and not T2STAR (bu we keep it in doubt)
https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image/00089209

@yyao1231

**Comment by yyao1231** [comment]
Ok Jean-Côme! I merge the PR.
