### ISSUE TITLE
[Bruker import] Create exam error

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#800]
user type: expert
browser: Firefox

I have created my new subject during the import and want to create a new examination, then I get the error:
Error: Uncaught (in promise): $w: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"OK","url":"https://shanoir.irisa.fr/shanoir-ng/datasets/examinations","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://shanoir.irisa.fr/shanoir-ng/datasets/examinations: 403 OK","error":{"code":403,"message":"Accès refusé","details":null}}

**Comment by jcomedouteau** [comment]
at org.shanoir.ng.examination.controler.ExaminationApiController$$EnhancerBySpringCGLIB$$5ecfcfab.saveNewExamination(<generated>)

I'll check it :)

**Comment by michaelkain** [comment]
solved, to be finally tested by me on qualif+prod
