### ISSUE TITLE
[Challenge] Download data from challenge

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#801]
-Update front to allow multiple files (and add files to the path, not replacing it)

On the back, we already have a List<String> as protocolFilePath => No need to change anything in DB.

We just need to manage the way we upload / retrieve / delete it.
StudyApiManager: Update 
- uploadProtocolFile => Allow more than 50Mb files + just "add" a file (don't delete the old one)

On studies/application.yml => Allow download of files of more than 500mb:
  http:
    multipart:
      maxFileSize: 500Mb
      maxRequestSize: 500Mb

In nginx.conf, we can change the value to upload files of more than 1Gb and download more than 5gb

**Comment by michaelkain** [comment]
Hi, deployed in prod, shanoir.irisa.fr yesterday, 22.02.2021, I therefore close the issue now. Thank you and cheers, Michael
