### ISSUE TITLE
[Bruker import] upload not working

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#804]
user type: expert
browser: Firefox

Bruker import completely down, file upload with demo_appning.zip did not work during Euris demo.

**Comment by michaelkain** [comment]
<img width="1425" alt="Bildschirmfoto 2021-02-05 um 10 00 57" src="https://user-images.githubusercontent.com/4560288/107012494-6362ab00-6799-11eb-852f-9ebf3d61af1f.png">

**Comment by jcomedouteau** [comment]
I'll have a look at it this morning.

**Comment by jcomedouteau** [comment]
We updated the dicomifier, and there is now a problem with the bruker conversion..

I think i'll have to update it

**Comment by michaelkain** [comment]
solved, to be finally tested by me on qualif+prod

**Comment by michaelkain** [comment]
Hi, I have tested in on qualif and it does not yet work. I assume related to AB deploy scripts, that do maybe not take into consideration the change in our d-c.yml, cheers, Michael

**Comment by michaelkain** [comment]
Hi Anthony, could you take the update of dicomifier into consideration in your scripts please? Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
I went to check on the server and you are right, the qualif-preclinical-bruker2dicom image was not updated.

**Comment by jcomedouteau** [comment]
It has been updated on qualif => you can now normally test
