### ISSUE TITLE
Preclinical : import large files

### ISSUE THREAD

**Issue by marjolaineBodin** [fli-iam/shanoir-ng#84]
While importing large files,
- step2 : visualization (freeze, to be checked)
- step4 : error while calling the dataset microservice (422) 
I/O error on POST request for "http://datasets:9904/datasetacquisition": Connection reset; nested exception is java.net.SocketException: Connection reset

**Comment by marjolaineBodin** [comment]
Regarding the step 4, a better solution can be implemented instead of increasing realm settings token in keycloak, by changing the restTemplate post to async rabbitmq communication.
See todo in org.shanoir.ng.importer.ImporterManagerService.manageImportJob(), l.130

**Comment by michaelkain** [comment]
Solved.
