### ISSUE TITLE
[Challenge] Account Request Email: include challenge info

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#854]
The account request email for challengers does not mention the challenge, what is complicated for admins to know what the request is about.

**Comment by jcomedouteau** [comment]
Do I do a very simple thing (juste add the 'challenge' to the template) or do I create a new template in your mind ?

**Comment by michaelkain** [comment]
successfully tested on qualif; it will help us already to separate challenge account request from normal account requests
