### ISSUE TITLE
[Account extension request] Account expired? data not arriving in db

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#863]
Hi Jean-Come,
I tested the account expired feature this morning.
The information I have entered into the extension request did not end up in my local database.
I had an exception because of the emailService, but in the code all the other logic happens before, so could you please have a look on that? Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
I guess the email is send, but the data are not stored

**Comment by jcomedouteau** [comment]
![image](https://user-images.githubusercontent.com/7604176/111766703-231d3f00-88a6-11eb-848d-46fee7987614.png)
![image](https://user-images.githubusercontent.com/7604176/111766759-316b5b00-88a6-11eb-9800-09895208af12.png)

Only the date was not saved in database.

This is linked to a commit of @Nunien to correct some CSS I guess: https://github.com/fli-iam/shanoir-ng/commit/c6d4dcbd69c5808897908eba9c5cf6d1f716ae03

I'm creating a  pull request :)
