### ISSUE TITLE
Solr search is not working (macOS, Safari web browser)

### ISSUE THREAD

**Issue by albangaignard** [fli-iam/shanoir-ng#867]
Writing in the search text area is very slow, and ends with an unexpected error. 

![Capture d’écran 2021-03-18 à 11 12 32](https://user-images.githubusercontent.com/10667536/111609701-da4c8400-87da-11eb-9330-089342911a7a.png)

![Capture d’écran 2021-03-18 à 11 11 25](https://user-images.githubusercontent.com/10667536/111609535-b12bf380-87da-11eb-8d6a-601b829e51c4.png)

**Comment by jcomedouteau** [comment]
Hello @albangaignard, thanks for all the feedbacks !

We have multiple problems with safari at the moment, and we decided not to focus on this as Shanoir is optimized for chrome, which is installable on every OS.

Also, I think the requests you are trying to do should finish with a ";"
studyName:ICAN;subjetName:AIC_17;

subjetName:AIC_17;

Can you try with these and tell us if it works ?

Thanks,

Jean-Côme Douteau

**Comment by albangaignard** [comment]
Hello @jcomedouteau, 

Thanks for your feedback, I tried both options and they are both failing. 
Exactly the same errors with Google Chrome. 

![Capture d’écran 2021-04-13 à 08 50 34](https://user-images.githubusercontent.com/10667536/114509001-51880300-9c35-11eb-811a-e9977a9340b2.png)

![Capture d’écran 2021-04-13 à 08 49 28](https://user-images.githubusercontent.com/10667536/114508876-2a313600-9c35-11eb-8f55-22391da965cb.png)

**Comment by jcomedouteau** [comment]
That's totally my bad, it subjectName and not subjetName..
Can you try:
studyName:ICAN;subjectName:AIC_17;
subjectName:AIC_17;

**Comment by albangaignard** [comment]
Thanks for your quick feedback. It's working fine, also on Safari. 
Here is the working query `subjectName:AIC_17*;datasetName:*TOF*;`
