### ISSUE TITLE
How to search data provided by a set of contributing centers ? 

### ISSUE THREAD

**Issue by albangaignard** [fli-iam/shanoir-ng#871]
Now it's not possible to search for data provided by given study centers. 
![Capture d’écran 2021-03-18 à 11 25 21](https://user-images.githubusercontent.com/10667536/111611330-a1adaa00-87dc-11eb-9ab2-b3b655bd1050.png)

**Comment by jcomedouteau** [comment]
Same, this can be part of the full 'refonte' of solr that is necessary and that Elise put on the table at the consortium meeting.
We started to discuss with @Nunien here, but we need to make a proper specification:
#684

I already had noted the 'filter by center' (and maybe by equipement too) request !

**Comment by jcomedouteau** [comment]
This is now possible.
