### ISSUE TITLE
Issue with nifti (dcm2nixx) conversion of tfl_b1map series

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#876]
Hi, 
tfl_b1map Series in the MS-TRACTS study are converted in 2 nifti files, one with odd and one with even slices. Converting the DICOM data offline with dcm2niix 20200331 gives only 1 nifti file. Could you check the dcm2niix version used in Shanoir and add the more recent version ? Generally speaking, a single converter should be used for one study, or at least one acquisition equipment but this makes it difficult to update the converters. 
Thanks in advance, 
Elise

**Comment by jcomedouteau** [comment]
You are right, we currently use a 2017 version of dcm2niix, I'll check if we can easily update the version

**Comment by jcomedouteau** [comment]
Speaking of this, for new imports, we should propose only dcm2niix or dicomifier as the others are quite outdated.
Nifti converters are currently linked to study cards, every user is free to chose, but should be advised to use one (probably dcm2niix)

**Comment by ebannier2018** [comment]
I fully agree. add a recent version of dcm2nixx (e.g. march 2020) and recommend using dcm2niix or dicomifier. 
Speaking of remotely sending a link to download the data selected in the GUI, I would also propose to only convert the data there, and not at import, so that we do use the lastest nifti conversion, e.g. for older studies. 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
