### ISSUE TITLE
New unexpected error during the import

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#879]
![Captureshanoir22mar21](https://user-images.githubusercontent.com/72256970/112010000-31c65900-8b27-11eb-9e8f-337c174665ef.JPG)
see attached screenshot

**Comment by jcomedouteau** [comment]
@solene2020, thanks a lot for this submission. A configuration is missing in the code, we'll add it as soon as possible.

You can follow this resolution of this issue to know when it'll be resolved.

Jean-Côme Douteau for the Shanoir's development team.

**Comment by michaelkain** [comment]
Hi Solène, Jean-Come has fixed the issue.
We would deploy it normally tomorrow, but as there is the maintenance, we will deploy it as soon as possible afterwards.
Thx, Michael

**Comment by solene2020** [comment]
OK, it works now, perfect!
thank you
