### ISSUE TITLE
Issue with nifti conversion of sequences with special characters

### ISSUE THREAD

**Issue by Lou-SdC** [fli-iam/shanoir-ng#889]
I tried do download diffusion data with ">" character in their name (see for example sequence cmrr_mbep2d_diff cusp66 b3000 A>P TE62 2mm in the NeuroFB_AVC study, dataset ID is 299702).
The conversion seems to start and I get the wheel rolling in the top right corner of the navigator, it takes some time then I can download the .zip file and a file does appear in my downloads folder : 299702-cmrr_mbep2d_diff cusp66 b3000 A P TE62 2mm-cmrr_mbep2d_diff cusp66 b3000 A P TE62 2mm.zip. Unfortunately, the .zip file is empty.
The download of the DICOM files and conversion directly on my computer worked fine.
Thank you in advance,
Lou Scotto di Covella

**Comment by Nunien** [comment]
Thank you for reporting this Lou. Is this blocking your work?

**Comment by jcomedouteau** [comment]
I don't think this is coming from the name of the dicom, I'll check !
