### ISSUE TITLE
Import BIDS

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#89]
It would be good to have a demo of a simple BIDS import with sh-ng for the INCF workshop,
from the 27.-29.03.2019 in Montreal:
- Integrate Import from BIDS into sh-ng frontend/backend (upload of zip file or BIDS folder)
- Integrate BIDS Validator (JS) into sh-ng Angular 5 frontend and validate upload
- BIDS files will be stored on the disk in a named volume, dedicated to BIDS data
- MySQL - Shanoir: very less informations (Study - BIDSSubject) in the shanoir database, BIDSSubjects could be stored and added to studies, with a special icon.
- Below a BIDS subject the BIDS tree is displayed as stored on the hard disk, if necessary, or only propose download of files

**Comment by jcomedouteau** [comment]
I'm closing this as this is now done. I'm creating a new issue for the bids validator.
