### ISSUE TITLE
[Resting state upload] Resting state data cannot be downloaded as dicom are duplicated after import

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#895]

**Comment by jcomedouteau** [comment]
Philips DATA for resting states in 4D is organized in folder/subfolder and data with same name for images in subfolders:
- IM001
- IM002
- /1/IM001
- /1/IM002
- ...

When preparing the images for the import, see these lines of code (DatasetCreatorAndNiftiConverter.java l.819)
`
			String filePath = image.getPath();
			File oldFile = new File(workFolder.getAbsolutePath() + File.separator + filePath);
			if (oldFile.exists()) {
				File newFile = new File(serieIDFolder.getAbsolutePath() + File.separator + oldFile.getName());
				oldFile.renameTo(newFile);

`
Donc si on a les deux fichiers suivants:
- IM001
- /1/IM001

Le fichier IM001 sera à priori écrasé (ou le "renameTo" échouera silencieusement)

De plus, ce fichier sera donc référencé DEUX FOIS dans les datasetFile, provoquant une erreur (FileAlreadyExistsException) au téléchargement.

Il faut donc modifier cette gestion des dicoms à l'import !

**Comment by jcomedouteau** [comment]
This is due to Philips way of organizing files. it should be all flat

**Comment by ebannier2018** [comment]
On Siemens there are 2 options : either all flat or all all files should be within subfolders. Both are possible, but to my knowledge they are not partly in subfolders (2048 files max), partly at the root...
The subfolders correspond to sequences then. The diffusion and resting state data are exported in mosaic format with all slices on one volume on one file, less files and either to go through volumes and check for motion at the console.

**Comment by michaelkain** [comment]
successfully tested on qualif with example from JC, did two regression tests with sample.zip two (1 serie only + 2 series), all worked
