### ISSUE TITLE
Acquisition equiment serial number should be unique?

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#9]
In the front code it seems like acquisition equiment serial number should be unique. But no error is raised by the backend when update an acquisition equipment using a taken serial number. Then if it should be unique :
* Implement the constraint in the database
* Throw a well formated error as a rest reponse
* Catch it in the front and display an error as a form error (the display seems to be ready)

**Comment by ebannier** [comment]
I confirm that serial numbers are unique. Serial number was not entered sometimes (e.g. in the ICAN study, where expert role is given outside Neurinfo, serial number 0000 given when they could not get the info at first) leading to : 
- creation of several acquisition equipments for the same scanner by different experts for different studys 
- no possibility to check at import whether the serial number in the study card matches the dicom tags, i.e. if the data came from the scanner we expect it to come from. Only quality check currently in Shanoir, can prevent errors when multiple study cards are defined for a study and a wrong study card selected by the user importing data, or when for some centers/subjects data comes from different scanners (clinical routine scans) and only one study card is defined.
An idea would be to send a warning sent to the person responsible for the study when importing a non matching SERIAL NUMBER in a dataset. Currently there is a warning for the person importing the data but unless the study card was chosen by error and this user cares/ stops and restarts the import, this is not corrected and the the person creating the study cards (responsible for the study) who may care is not informed.
