### ISSUE TITLE
Examination download (limited to 50 datasets)

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#904]
Hi, 

I would like to download the complete examination with id = 15151 but I cannot because there are more than 50 datasets....is there another solution but to download them (all 50) individually ? 
Thanks in advance for your help, 

Elise

**Comment by jcomedouteau** [comment]
Multiple solutions:
- From solr search, find your examination with its comment / date and download datasets 50 by 50.
- From study detail, deploy subject arborescence to your examination, deploy all datasets, then select up to 50 datasets and click on "Download selected datasets" and download them 50 by 50.

Jean-Côme

**Comment by ebannier2018** [comment]
Great thanks !
