### ISSUE TITLE
view the studies a user has access to 

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#910]
Hi, 

Is it possible to easily visualize which studies a user has access to ? 
The only way I know of is to check all studies one by one, which can be very tedious for an admin with access to many studies, 
Thanks in advance for your answer

Elise

**Comment by jcomedouteau** [comment]
We are working on it. The development I made wasn't good, but when you go to the detail of a user as an admin, you will be able to see all the studies he has access to.

**Comment by jcomedouteau** [comment]
see #909 #598
