### ISSUE TITLE
Download of extra data

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#914]
Hi, 

Following a question from Lou, I am trying to download an extra data in the Neurofeedep study (subject Neurofeedep 01 XX) but the download button is grey and nothing happens when clicking on it. Is the data there, did something go wrong when importing it, or is there an issue at download ?  
In another study (AMYNET) I have no problem downloading extra data (smaller extra data though this time)
Regards,
Elise

**Comment by jcomedouteau** [comment]
Hello Elise,
You are right, the file is referenced in the database but not present in the file system. Something must have failed while uploading it.
How big was this file ?
I'll try to have a look on when it was uploaded to see if I can get an error from the logs.

Jean-Côme

**Comment by jcomedouteau** [comment]
Hello,
The examination comes from shanoir old,  but there was no file linked to it in the old database. We can imagine that it was added 
 later (2021-03-16 09:15:42 is date of the last referenced update for this examination, but it was probably before)
There is no log for the file upload, which means it may have been done before 2020/05.

In that case, the extra data files where not correctly handled by Shanoir and may never have been saved.
Can you have access to the reference file @ebannier2018 ?

Jean-Côme

**Comment by ebannier2018** [comment]
Hi, 
Thanks for getting back. I am adding Lou in cc since she did the upload. 
Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
