### ISSUE TITLE
[dcm2niix] Update version to last available (2021/03)

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#920]
Update last dcm2niix using adapted tag (and not commit ?) in import/DockerFilewith:
https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20210317

**Comment by ebannier** [comment]
Hello, 

Merci pour cette update. Pouvez vous préciser le changement apporté ? La version dcm2niix ancienne a été mise à jour (cela veut dire que dans une même étude les données seront dorénavant converties avec dcm2nixx 2021) ou bien une nouvelle version est disponible ? De manière générale comment voyez vous la gestion de ces mises à jour régulières ? de la possibilité d'avoir d'autres convertisseurs disponibles au téléchargement ? Ou de ne convertir qu'au téléchargement ? Peut on prévoir d'en discuter à la réunion du consortium de Septembre ? 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
