### ISSUE TITLE
Account extension request not working directly - Should be directly available after first mail

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#923]
On qualif > extension request : 

What we should have : 
* fill the form
* click button "Request an extension"
    - a msg replace the form : "An email has been sent to the administrator who will validate your request."
    - OK button
    - email is recieved by the user
        - new password
    - user set to "On Demand"
  
But we have : 
        - no msg
        - no ok button
        - no email sent
        - error msg (500)
        - user is not set to "On Demand"

**Comment by jcomedouteau** [comment]
I'm checking this.
Jean-Côme

**Comment by jcomedouteau** [comment]
I have no such problem :/
![image](https://user-images.githubusercontent.com/7604176/116877375-25e9ae80-ac1e-11eb-91a5-cfbe8c078684.png)

On the other hand, I don't know if any mail is sent. Could you check @Nunien  ?

**Comment by jcomedouteau** [comment]
Could you retry @Nunien so we can close this issue or go further ? 
Thanks !

**Comment by jcomedouteau** [comment]
Up @Nunien

**Comment by jcomedouteau** [comment]
I think i have what we want: the extension request can be done only AFTER the account was disabled.
It should be available since the first mail.

**Comment by jcomedouteau** [comment]
I think i have what we want: the extension request can be done only AFTER the account was disabled.
It should be available since the first mail.
