### ISSUE TITLE
[Import] dicom zip: Next button -> back to home page

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#926]
- start a fresh import, e.g. user type admin or other normally
- upload dicom zip and select serie afterwards
- create a new subject, but do NOT select the subject type (keep it empty)
- create a new examination, now next button remains disabled
- select subject type to progress, e.g. patient
- click on Next ---> back to home page send, import broken and data to enter completely again

**Comment by Nunien** [comment]
Wow, it closed automatically! Is it because I named the commit "fix #XXX"? Does it work with pull requests?

Anyway, I think it is fixed and you can test it on qualif.

**Comment by jcomedouteau** [comment]
Arg, did you commit directly on develop ?

**Comment by michaelkain** [comment]
successfully tested on qualif
