### ISSUE TITLE
[Study] Study deletion (with study cards) leaves wrong study cards

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#927]
Hi Jean-Come, during my tests I found a bug, not urgent, but not so nice.
I created a study and an empty studycard afterwards to make an import with a dicom.zip into it.
As the study is empty from subjects and exams I can directly delete it, so far fine, BUT now when
I open the list of study cards an error is thrown and I can not open the study card attached to the
deleted study. I propose to delete the studycards during study deletion too, to avoid this problem.
Centers, acq equipements and converters should be kept independently. I hope this sounds logic.
Cheers, Michael

**Comment by jcomedouteau** [comment]
Yep it's totally logic.
Let's discuss this this afternoon if you want me to integrate this with th other issue
