### ISSUE TITLE
Import date in dataset / acquisition

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#937]
* Should the import date should be on dataset or dataset acquisition ?
* add the property in the java model
* a sql migration script might be necessary to add the column
* display the date on
    * dataset / dataset acquisition details
    * dataset / dataset acquisition list ?

**Comment by jcomedouteau** [comment]
I think we can store it only once in datasetAcquisition that is not used a lot instead of storing it multiple time (repeatidly) in dataset.
