### ISSUE TITLE
Spectro/ Tensor data are not saved in Shanoir

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#969]
If we have a look at:
https://github.com/fli-iam/shanoir-ng/commit/1ed87c920f860c1674183d7a6bc1c50d2baa1418
and comment
// Added Temporary check on serie in order not to generate dataset acquisition for series without images.

This temporary check has become eternal and so all non-images .dcm files are ignored. It means tensor and spectro data stored in .dcm are completely ignored.

They should'nt be.

How to reproduce:
- Pick a dicom archive with spectro data
- Import it completly
- The spectro data is missing at the end of the import

+ Add physiolog data

**Comment by jcomedouteau** [comment]
This was done because we want to avoid clinical data (Medical report for example) to be loaded in Shanoir.
We need to have a way to identify such data (tensor, spectro) to load it in Shanoir.

**Comment by jcomedouteau** [comment]
To know if spectro: based on (0018, 9008) (not null)
To know if tensor: => Not possible with only the dicom => Use study description ?

**Comment by ebannier** [comment]
Hi, 

Great if you can identify spectro data ! 
Tensor data can be reconstructed from the native diffusion data. The data is not completely lost as is the case for spectroscopy data, so if you can solve that one already it is great! 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays
