### ISSUE TITLE
Error while importing data /ICAN

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#988]
![Captureshanoir aic_12_0031](https://user-images.githubusercontent.com/72256970/126140770-2cd34f60-a738-4292-a6e6-b91e17e3107a.JPG)
Import data impossible ( done by Nantes for Poitiers)

**Comment by Nunien** [comment]
I might have found the problem. I could be caused by the study card (462). I fixed it, could you try it again ?

**Comment by solene2020** [comment]
![Captureshnaoir aic_12_0031 bis](https://user-images.githubusercontent.com/72256970/126170712-77ff2d2e-fa5e-4467-8a23-846c757d6a4f.JPG)
I just tried: the same error message

**Comment by solene2020** [comment]
Dear Julien,



I tried it again, but I get the same error message.

Could you help me please ?

Solène Jouan

TEC-UIC imagerie

CHU de Nantes

02 44 76 85 39 (68539) absente le mercredi



________________________________
De : Julien Louis ***@***.***>
Envoyé : lundi 19 juillet 2021 15:16
À : fli-iam/shanoir-ng
Cc : JOUAN Solene; Author
Objet : Re: [fli-iam/shanoir-ng] Error while importing data /ICAN (#988)


I might have found the problem. I could be caused by the study card (462). I fixed it, could you try it again ?

-
