### ISSUE TITLE
Spring Boot 2 Migration: cacerts access issue

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#997]
Hi Jean-Come,
could you please try to reproduce this issue on your machine?
I am struggeling with the solution. I have put my latest dev on my PR Spring Boot 2 Migration.
The issue indicates, that the Tomcat within Spring Boot 2.4.5 does not seem to find cacerts...
What is weird, when I connect into the container e.g. of ms users "keytool -list -cacerts" does
list me all certs + the cert shanoir-ng-nginx OR only the cert shanoir-ng-nginx (I tried both options).
I have tried trustStore options, both on java command level or on application.yml level, but still no breakthrough.
Could you just try to clean your volumes, put shanoir_migration=init, run it until all ms are killed and wait for KC some time,
change to migration=auto and run again d-c up -d?
Thank you and with kind regards,
Michael
PS: hopefully the more required memory, as I removed all jdk13 alpine refs, does not cause you troubles...

users                       | 2021-08-04 08:09:17.118  WARN 1 --- [nio-9901-exec-3] o.keycloak.adapters.KeycloakDeployment   : Failed to load URLs from https://shanoir-ng-nginx/auth/realms/shanoir-ng/.well-known/openid-configuration
users                       | 
users                       | javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
users                       | 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
users                       | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
users                       | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
users                       | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
users                       | 	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1313)
users                       | 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
users                       | 	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:570)
users                       | 	at org.keycloak.adapters.SniSSLSocketFactory.createLayeredSocket(SniSSLSocketFactory.java:119)
users                       | 	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:554)
users                       | 	at org.keycloak.adapters.SniSSLSocketFactory.connectSocket(SniSSLSocketFactory.java:114)
users                       | 	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:415)
users                       | 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
users                       | 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
users                       | 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
users                       | 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
users                       | 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
users                       | 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
users                       | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
users                       | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
users                       | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
users                       | 	at org.keycloak.adapters.KeycloakDeployment.getOidcConfiguration(KeycloakDeployment.java:230)
users                       | 	at org.keycloak.adapters.KeycloakDeployment.resolveUrls(KeycloakDeployment.java:182)
users                       | 	at org.keycloak.adapters.KeycloakDeployment.getRealmInfoUrl(KeycloakDeployment.java:246)
users                       | 	at org.keycloak.adapters.rotation.AdapterTokenVerifier.createVerifier(AdapterTokenVerifier.java:107)
users                       | 	at org.keycloak.adapters.rotation.AdapterTokenVerifier.verifyToken(AdapterTokenVerifier.java:47)
users                       | 	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:103)
users                       | 	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:88)
users                       | 	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:67)
users                       | 	at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter.attemptAuthentication(KeycloakAuthenticationProcessingFilter.java:154)
users                       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:222)
users                       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
users                       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
users                       | 	at org.keycloak.adapters.springsecurity.filter.KeycloakPreAuthActionsFilter.doFilter(KeycloakPreAuthActionsFilter.java:96)
users                       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
users                       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
users                       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
users                       | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
users                       | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
users                       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
users                       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
users                       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
users                       | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
users                       | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
users                       | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
users                       | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
users                       | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
users                       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
users                       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
users                       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
users                       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
users                       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
users                       | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)
users                       | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
users                       | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
users                       | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
users                       | 	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:398)
users                       | 	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:257)
users                       | 	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:352)
users                       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
users                       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
users                       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
users                       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
users                       | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
users                       | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
users                       | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
users                       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
users                       | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
users                       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
users                       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
users                       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
users                       | 	at java.base/java.lang.Thread.run(Thread.java:834)
users                       | Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
users                       | 	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
users                       | 	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
users                       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
users                       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
users                       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
users                       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
users                       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1316)
users                       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1207)
users                       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1150)
users                       | 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
users                       | 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
users                       | 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
users                       | 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
users                       | 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
users                       | 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
users                       | 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
users                       | 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
users                       | 	... 74 common frames omitted
users                       | Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
users                       | 	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
users                       | 	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
users                       | 	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
users                       | 	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:99)
users                       | 	... 90 common frames omitted

**Comment by jcomedouteau** [comment]
I'm on it !

**Comment by jcomedouteau** [comment]
@michaelkain Everything starts but I have the same error as you.

**Comment by michaelkain** [comment]
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.703 UTC|TrustStoreManager.java:161|Inaccessible trust store: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/jssecacerts
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.704 UTC|TrustStoreManager.java:112|trustStore is: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts
users                       | trustStore type is: pkcs12
users                       | trustStore provider is: 
users                       | the last modified time is: Wed Aug 04 07:29:06 UTC 2021
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.704 UTC|TrustStoreManager.java:311|Reload the trust store
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.729 UTC|TrustStoreManager.java:318|Reload trust certs
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.729 UTC|TrustStoreManager.java:323|Reloaded 0 trust certs
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.737 UTC|X509TrustManagerImpl.java:79|adding as trusted certificates
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.738 UTC|SSLContextImpl.java:1088|keyStore is : 
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.738 UTC|SSLContextImpl.java:1089|keyStore type is : pkcs12
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.738 UTC|SSLContextImpl.java:1091|keyStore provider is : 
users                       | javax.net.ssl|ALL|01|main|2021-08-04 13:08:56.739 UTC|SSLContextImpl.java:1126|init keystore
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:08:56.739 UTC|SSLContextImpl.java:1149|init keymanager of type SunX509
users                       | javax.net.ssl|ALL|01|main|2021-08-04 13:08:56.749 UTC|SSLContextImpl.java:115|trigger seeding of SecureRandom
users                       | javax.net.ssl|ALL|01|main|2021-08-04 13:08:56.751 UTC|SSLContextImpl.java:119|done seeding of SecureRandom
users                       | javax.net.ssl|DEBUG|03|Finalizer|2021-08-04 13:08:59.786 UTC|SSLSocketImpl.java:473|duplex close of SSLSocket
users                       | javax.net.ssl|WARNING|03|Finalizer|2021-08-04 13:08:59.806 UTC|SSLSocketImpl.java:494|SSLSocket duplex close failed (
users                       | "throwable" : {
users                       |   java.net.SocketException: Socket is not connected
users                       |   	at java.base/java.net.Socket.shutdownOutput(Socket.java:1571)
users                       |   	at java.base/sun.security.ssl.BaseSSLSocketImpl.shutdownOutput(BaseSSLSocketImpl.java:232)
users                       |   	at java.base/sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:561)
users                       |   	at java.base/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:479)
users                       |   	at java.base/sun.security.ssl.BaseSSLSocketImpl.finalize(BaseSSLSocketImpl.java:275)
users                       |   	at java.base/java.lang.System$2.invokeFinalize(System.java:2120)
users                       |   	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:87)
users                       |   	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)}
users                       | 
users                       | )
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:09:03.299 UTC|TrustStoreManager.java:161|Inaccessible trust store: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/jssecacerts
users                       | javax.net.ssl|DEBUG|01|main|2021-08-04 13:09:03.300 UTC|TrustStoreManager.java:112|trustStore is: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts

**Comment by jcomedouteau** [comment]
With JAVA 8

javax.net.ssl|FINE|01|main|2021-08-04 13:28:12.020 UTC|TrustStoreManager.java:161|Inaccessible trust store: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/jssecacerts
javax.net.ssl|FINE|01|main|2021-08-04 13:28:12.027 UTC|TrustStoreManager.java:112|trustStore is: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
trustStore type is: jks
trustStore provider is: 
the last modified time is: Wed Aug 04 11:59:35 UTC 2021
javax.net.ssl|FINE|01|main|2021-08-04 13:28:12.037 UTC|TrustStoreManager.java:311|Reload the trust store
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.455 UTC|TrustStoreManager.java:318|Reload trust certs
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.472 UTC|TrustStoreManager.java:323|Reloaded 1 trust certs
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.586 UTC|X509TrustManagerImpl.java:79|adding as trusted certificates (
  "certificate" : {
    "version"            : "v1",
    "serial number"      : "00 DD C7 D1 42 DD 2B 11 24",
    "signature algorithm": "SHA256withRSA",
    "issuer"             : "CN=shanoir-ng-nginx",
    "not before"         : "2021-08-04 11:59:32.000 UTC",
    "not  after"         : "2023-08-04 11:59:32.000 UTC",
    "subject"            : "CN=shanoir-ng-nginx",
    "subject public key" : "RSA"}
)
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.601 UTC|SSLContextImpl.java:1076|keyStore is : 
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.606 UTC|SSLContextImpl.java:1077|keyStore type is : jks
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.612 UTC|SSLContextImpl.java:1079|keyStore provider is : 
javax.net.ssl|ALL|01|main|2021-08-04 13:28:21.616 UTC|SSLContextImpl.java:1114|init keystore
javax.net.ssl|FINE|01|main|2021-08-04 13:28:21.634 UTC|SSLContextImpl.java:1137|init keymanager of type SunX509
javax.net.ssl|ALL|01|main|2021-08-04 13:28:21.665 UTC|SSLContextImpl.java:115|trigger seeding of SecureRandom
javax.net.ssl|ALL|01|main|2021-08-04 13:28:21.695 UTC|SSLContextImpl.java:119|done seeding of SecureRandom
javax.net.ssl|FINE|01|main|2021-08-04 13:29:15.986 UTC|TrustStoreManager.java:161|Inaccessible trust store: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/jssecacerts
javax.net.ssl|FINE|01|main|2021-08-04 13:29:16.028 UTC|TrustStoreManager.java:112|trustStore is: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
trustStore type is: jks
trustStore provider is: 
the last modified time is: Wed Aug 04 11:59:35 UTC 2021
javax.net.ssl|FINE|01|main|2021-08-04 13:29:16.038 UTC|X509TrustManagerImpl.java:79|adding as trusted certificates (
  "certificate" : {
    "version"            : "v1",
    "serial number"      : "00 DD C7 D1 42 DD 2B 11 24",
    "signature algorithm": "SHA256withRSA",
    "issuer"             : "CN=shanoir-ng-nginx",
    "not before"         : "2021-08-04 11:59:32.000 UTC",
    "not  after"         : "2023-08-04 11:59:32.000 UTC",
    "subject"            : "CN=shanoir-ng-nginx",
    "subject public key" : "RSA"}
)
javax.net.ssl|ALL|01|main|2021-08-04 13:29:16.039 UTC|SSLContextImpl.java:115|trigger seeding of SecureRandom
javax.net.ssl|ALL|01|main|2021-08-04 13:29:16.041 UTC|SSLContextImpl.java:119|done seeding of SecureRandom

**Comment by michaelkain** [comment]
Solved!
Very helpful to find issue: **"-Djavax.net.debug=all"**
**Solution: "-Djavax.net.ssl.trustStorePassword=changeit"**, see my commit into all Dockerfiles

**Explanation:**
From openjdk-9 upwards the default keystore type changed from 'jks' to 'pkcs12' [1] by means of JEP 229 [2]. A JKS keystore can be read without supplying a password (or by supplying an empty one) while a PKCS12 keystore requires a password to be set.
Thus a /etc/ssl/certs/java/cacerts created in the pkcs12 format will fail to be loaded as, by default, the truststore password is empty - in order to avoid that the user must set -Djavax.net.ssl.trustStorePassword=<passwd> or define it in /etc/java-XX-openjdk/management/management.properties. A JKS keystore will work normally, as the certificates in it can be ready when the truststore password is empty.
Ubuntu does *not* set the javax.net.ssl.trustStorePassword by default
thus any user that got a cacerts generated in JKCS12 won't be able
to use any secure connections from java.
More infos here: https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631

**Comment by michaelkain** [comment]
works with all 5 microservices, tested on my machine
