### ISSUE TITLE
Spring Boot 2 Migration: Solr not working anymore

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#998]
nested exception is org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html.

datasets                    | 2021-08-06 12:46:22.378 ERROR 1 --- [nio-9904-exec-9] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 
datasets                    | 
datasets                    | org.springframework.dao.DataAccessResourceFailureException: Error from server at http://solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>
datasets                    | <head>
datasets                    | <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
datasets                    | <title>Error 404 Not Found</title>
datasets                    | </head>
datasets                    | <body><h2>HTTP ERROR 404</h2>
datasets                    | <p>Problem accessing /solr/shanoir/shanoir/update. Reason:
datasets                    | <pre>    Not Found</pre></p>
datasets                    | </body>
datasets                    | </html>
datasets                    | ; nested exception is org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>
datasets                    | <head>
datasets                    | <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
datasets                    | <title>Error 404 Not Found</title>
datasets                    | </head>
datasets                    | <body><h2>HTTP ERROR 404</h2>
datasets                    | <p>Problem accessing /solr/shanoir/shanoir/update. Reason:
datasets                    | <pre>    Not Found</pre></p>
datasets                    | </body>
datasets                    | </html>
datasets                    | 
datasets                    | 	at org.springframework.data.solr.core.SolrExceptionTranslator.translateExceptionIfPossible(SolrExceptionTranslator.java:84)
datasets                    | 	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:169)
datasets                    | 	at org.springframework.data.solr.core.SolrTemplate.delete(SolrTemplate.java:249)
datasets                    | 	at org.springframework.data.solr.core.SolrOperations.delete(SolrOperations.java:228)
datasets                    | 	at org.springframework.data.solr.repository.support.SimpleSolrRepository.deleteAll(SimpleSolrRepository.java:212)
datasets                    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
datasets                    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
datasets                    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
datasets                    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
datasets                    | 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
datasets                    | 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
datasets                    | 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
datasets                    | 	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:524)
datasets                    | 	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
datasets                    | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:531)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:156)
datasets                    | 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
datasets                    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
datasets                    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
datasets                    | 	at com.sun.proxy.$Proxy173.deleteAll(Unknown Source)
datasets                    | 	at org.shanoir.ng.solr.service.SolrServiceImpl.deleteAll(SolrServiceImpl.java:85)
datasets                    | 	at org.shanoir.ng.solr.service.SolrServiceImpl.indexAll(SolrServiceImpl.java:93)
datasets                    | 	at org.shanoir.ng.solr.service.SolrServiceImpl$$FastClassBySpringCGLIB$$898e9c41.invoke(<generated>)
datasets                    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
datasets                    | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
datasets                    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
datasets                    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
datasets                    | 	at org.shanoir.ng.solr.service.SolrServiceImpl$$EnhancerBySpringCGLIB$$b742dcf6.indexAll(<generated>)
datasets                    | 	at org.shanoir.ng.solr.controler.SolrApiController.indexAll(SolrApiController.java:55)
datasets                    | 	at org.shanoir.ng.solr.controler.SolrApiController$$FastClassBySpringCGLIB$$c4ecff37.invoke(<generated>)
datasets                    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
datasets                    | 	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
datasets                    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
datasets                    | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
datasets                    | 	at org.shanoir.ng.solr.controler.SolrApiController$$EnhancerBySpringCGLIB$$c47eb601.indexAll(<generated>)
datasets                    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
datasets                    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
datasets                    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
datasets                    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
datasets                    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
datasets                    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
datasets                    | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
datasets                    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
datasets                    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
datasets                    | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
datasets                    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
datasets                    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
datasets                    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
datasets                    | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
datasets                    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
datasets                    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
datasets                    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticatedActionsFilter.doFilter(KeycloakAuthenticatedActionsFilter.java:57)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakSecurityContextRequestFilter.doFilter(KeycloakSecurityContextRequestFilter.java:61)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakPreAuthActionsFilter.doFilter(KeycloakPreAuthActionsFilter.java:96)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter.successfulAuthentication(KeycloakAuthenticationProcessingFilter.java:214)
datasets                    | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:232)
datasets                    | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
datasets                    | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
datasets                    | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
datasets                    | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
datasets                    | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticatedActionsFilter.doFilter(KeycloakAuthenticatedActionsFilter.java:74)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakSecurityContextRequestFilter.doFilter(KeycloakSecurityContextRequestFilter.java:92)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
datasets                    | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter.successfulAuthentication(KeycloakAuthenticationProcessingFilter.java:214)
datasets                    | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:232)
datasets                    | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.keycloak.adapters.springsecurity.filter.KeycloakPreAuthActionsFilter.doFilter(KeycloakPreAuthActionsFilter.java:96)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
datasets                    | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
datasets                    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
datasets                    | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
datasets                    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
datasets                    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
datasets                    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
datasets                    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
datasets                    | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
datasets                    | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
datasets                    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
datasets                    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
datasets                    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
datasets                    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
datasets                    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
datasets                    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
datasets                    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
datasets                    | 	at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:67)
datasets                    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
datasets                    | 	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
datasets                    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
datasets                    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
datasets                    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
datasets                    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
datasets                    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
datasets                    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
datasets                    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
datasets                    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
datasets                    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
datasets                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
datasets                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
datasets                    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
datasets                    | 	at java.base/java.lang.Thread.run(Thread.java:834)
datasets                    | Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://solr:8983/solr/shanoir: Expected mime type application/octet-stream but got text/html. <html>
datasets                    | <head>
datasets                    | <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
datasets                    | <title>Error 404 Not Found</title>
datasets                    | </head>
datasets                    | <body><h2>HTTP ERROR 404</h2>
datasets                    | <p>Problem accessing /solr/shanoir/shanoir/update. Reason:
datasets                    | <pre>    Not Found</pre></p>
datasets                    | </body>
datasets                    | </html>
datasets                    | 
datasets                    | 	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:629)
datasets                    | 	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:265)
datasets                    | 	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)
datasets                    | 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:211)
datasets                    | 	at org.apache.solr.client.solrj.SolrClient.deleteByQuery(SolrClient.java:940)
datasets                    | 	at org.apache.solr.client.solrj.SolrClient.deleteByQuery(SolrClient.java:903)
datasets                    | 	at org.springframework.data.solr.core.SolrTemplate.lambda$delete$6(SolrTemplate.java:249)
datasets                    | 	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:167)
datasets                    | 	... 167 common frames omitted

**Comment by michaelkain** [comment]
solved by adapting application.yml, now back to work in GUI
one exception remains in log files, but maybe already on develop before
@Nunien Hi Julien, could you please verify this?
datasets                    | Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://solr:8983/solr: sort param field can't be found: datasetId
datasets                    | 	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:665)
datasets                    | 	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:265)
datasets                    | 	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)
datasets                    | 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:211)
datasets                    | 	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:1035)
datasets                    | 	at org.springframework.data.solr.core.SolrTemplate.lambda$executeSolrQuery$9(SolrTemplate.java:519)
datasets                    | 	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:167)
datasets                    | 	... 156 common frames omitted

**Comment by jcomedouteau** [comment]
Closing this as solr is now working correctly with Spring boot 2
